package com.fategrinder.barracks;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class CommandsContainer {

	static CommandPer cAcknowledgeEvent = new CommandPer("acknowledge-event", "Action", "AoC");
	static CommandPer cAcknowledgeTaunt = new CommandPer("acknowledge-taunt", "Action", "AoC");
	static CommandPer cAttackNow = new CommandPer("attack-now", "Action", "AoC");
	static CommandPer cAttackSoldierCount = new CommandPer("attack-soldier-count", "Fact", "AoC");
	static CommandPer cAttackWarboatCount = new CommandPer("attack-warboat-count", "Fact", "AoC");
	static CommandPer cBuild = new CommandPer("build", "Action", "AoC");
	static CommandPer cBuildForward = new CommandPer("build-forward", "Action", "AoC");
	static CommandPer cBuildGate = new CommandPer("build-gate", "Action", "AoC");
	static CommandPer cBuildWall = new CommandPer("build-wall", "Action", "AoC");
	static CommandPer cBuildingAvailable = new CommandPer("building-available", "Fact", "AoC");
	static CommandPer cBuildingCount = new CommandPer("building-count", "Fact", "AoC");
	static CommandPer cBuildingCountTotal = new CommandPer("building-count-total", "Fact", "AoC");
	static CommandPer cBuildingTypeCount = new CommandPer("building-type-count", "Fact", "AoC");
	static CommandPer cBuildingTypeCountTotal = new CommandPer("building-type-count-total", "Fact", "AoC");
	static CommandPer cBuyCommodity = new CommandPer("buy-commodity", "Action", "AoC");
	static CommandPer cCanAffordBuilding = new CommandPer("can-afford-building", "Fact", "AoC");
	static CommandPer cCanAffordCompleteWall = new CommandPer("can-afford-complete-wall", "Fact", "AoC");
	static CommandPer cCanAffordResearch = new CommandPer("can-afford-research", "Fact", "AoC");
	static CommandPer cCanAffordUnit = new CommandPer("can-afford-unit", "Fact", "AoC");
	static CommandPer cCanBuild = new CommandPer("can-build", "Fact", "AoC");
	static CommandPer cCanBuildWithEscrow = new CommandPer("can-build-with-escrow", "Fact", "AoC");
	static CommandPer cCanBuildGate = new CommandPer("can-build-gate", "Fact", "AoC");
	static CommandPer cCanBuildGateWithEscrow = new CommandPer("can-build-gate-with-escrow", "Fact", "AoC");
	static CommandPer cCanBuildWall = new CommandPer("can-build-wall", "Fact", "AoC");
	static CommandPer cCanBuildWallWithEscrow = new CommandPer("can-build-wall-with-escrow", "Fact", "AoC");
	static CommandPer cCanBuyCommodity = new CommandPer("can-buy-commodity", "Fact", "AoC");
	static CommandPer cCanResearch = new CommandPer("can-research", "Fact", "AoC");
	static CommandPer cCanResearchWithEscrow = new CommandPer("can-research-with-escrow", "Fact", "AoC");
	static CommandPer cCanSellCommodity = new CommandPer("can-sell-commodity", "Fact", "AoC");
	static CommandPer cCanSpy = new CommandPer("can-spy", "Fact", "AoC");
	static CommandPer cCanSpyWithEscrow = new CommandPer("can-spy-with-escrow", "Fact", "AoC");
	static CommandPer cCanTrain = new CommandPer("can-train", "Fact", "AoC");
	static CommandPer cCanTrainWithEscrow = new CommandPer("can-train-with-escrow", "Fact", "AoC");
	static CommandPer cCcAddResource = new CommandPer("cc-add-resource", "Action", "AoC");
	static CommandPer cCcPlayersBuildingCount = new CommandPer("cc-players-building-count", "Fact", "AoC");
	static CommandPer cCcPlayersBuildingTypeCount = new CommandPer("cc-players-building-type-count", "Fact", "AoC");
	static CommandPer cCcPlayersUnitCount = new CommandPer("cc-players-unit-count", "Fact", "AoC");
	static CommandPer cCcPlayersUnitTypeCount = new CommandPer("cc-players-unit-type-count", "Fact", "AoC");
	static CommandPer cChatLocal = new CommandPer("chat-local", "Action", "AoC");
	static CommandPer cChatLocalToSelf = new CommandPer("chat-local-to-self", "Action", "AoC");
	static CommandPer cChatLocalUsingId = new CommandPer("chat-local-using-id", "Action", "AoC");
	static CommandPer cChatLocalUsingRange = new CommandPer("chat-local-using-range", "Action", "AoC");
	static CommandPer cChatToAll = new CommandPer("chat-to-all", "Action", "AoC");
	static CommandPer cChatToAllUsingId = new CommandPer("chat-to-all-using-id", "Action", "AoC");
	static CommandPer cChatToAllUsingRange = new CommandPer("chat-to-all-using-range", "Action", "AoC");
	static CommandPer cChatToAllies = new CommandPer("chat-to-allies", "Action", "AoC");
	static CommandPer cChatToAlliesUsingId = new CommandPer("chat-to-allies-using-id", "Action", "AoC");
	static CommandPer cChatToAlliesUsingRange = new CommandPer("chat-to-allies-using-range", "Action", "AoC");
	static CommandPer cChatToEnemies = new CommandPer("chat-to-enemies", "Action", "AoC");
	static CommandPer cChatToEnemiesUsingId = new CommandPer("chat-to-enemies-using-id", "Action", "AoC");
	static CommandPer cChatToEnemiesUsingRange = new CommandPer("chat-to-enemies-using-range", "Action", "AoC");
	static CommandPer cChatToPlayer = new CommandPer("chat-to-player", "Action", "AoC");
	static CommandPer cChatToPlayerUsingId = new CommandPer("chat-to-player-using-id", "Action", "AoC");
	static CommandPer cChatToPlayerUsingRange = new CommandPer("chat-to-player-using-range", "Action", "AoC");
	static CommandPer cChatTrace = new CommandPer("chat-trace", "Action", "AoC");
	static CommandPer cCheatsEnabled = new CommandPer("cheats-enabled", "Fact", "AoC");
	static CommandPer cCivilianPopulation = new CommandPer("civilian-population", "Fact", "AoC");
	static CommandPer cCivSelected = new CommandPer("civ-selected", "Fact", "AoC");
	static CommandPer cClearTributeMemory = new CommandPer("clear-tribute-memory", "Action", "AoC");
	static CommandPer cCommodityBuyingPrice = new CommandPer("commodity-buying-price", "Fact", "AoC");
	static CommandPer cCommoditySellingPrice = new CommandPer("commodity-selling-price", "Fact", "AoC");
	static CommandPer cCurrentAge = new CommandPer("current-age", "Fact", "AoC");
	static CommandPer cCurrentAgeTime = new CommandPer("current-age-time", "Fact", "AoC");
	static CommandPer cCurrentScore = new CommandPer("current-score", "Fact", "AoC");
	static CommandPer cDeathMatchGame = new CommandPer("death-match-game", "Fact", "AoC");
	static CommandPer cDefendSoldierCount = new CommandPer("defend-soldier-count", "Fact", "AoC");
	static CommandPer cDefendWarboatCount = new CommandPer("defend-warboat-count", "Fact", "AoC");
	static CommandPer cDeleteBuilding = new CommandPer("delete-building", "Action", "AoC");
	static CommandPer cDeleteUnit = new CommandPer("delete-unit", "Action", "AoC");
	static CommandPer cDifficulty = new CommandPer("difficulty", "Fact", "AoC");
	static CommandPer cDisableRule = new CommandPer("disable-rule", "Action", "AoC");
	static CommandPer cDisableSelf = new CommandPer("disable-self", "Action", "AoC");
	static CommandPer cDisableTimer = new CommandPer("disable-timer", "Action", "AoC");
	static CommandPer cDoctrine = new CommandPer("doctrine", "Fact", "AoC");
	static CommandPer cDoNothing = new CommandPer("do-nothing", "Action", "AoC");
	static CommandPer cDropsiteMinDistance = new CommandPer("dropsite-min-distance", "Fact", "AoC");
	static CommandPer cEnableRule = new CommandPer("enable-rule", "Action", "AoC");
	static CommandPer cEnableTimer = new CommandPer("enable-timer", "Action", "AoC");
	static CommandPer cEnableWallPlacement = new CommandPer("enable-wall-placement", "Action", "AoC");
	static CommandPer cEnemyBuildingsInTown = new CommandPer("enemy-buildings-in-town", "Fact", "AoC");
	static CommandPer cEnemyCapturedRelics = new CommandPer("enemy-captured-relics", "Fact", "AoC");
	static CommandPer cEscrowAmount = new CommandPer("escrow-amount", "Fact", "AoC");
	static CommandPer cEventDetected = new CommandPer("event-detected", "Fact", "AoC");
	static CommandPer cFalse = new CommandPer("false", "Fact", "AoC");
	static CommandPer cFoodAmount = new CommandPer("food-amount", "Fact", "AoC");
	static CommandPer cGameTime = new CommandPer("game-time", "Fact", "AoC");
	static CommandPer cGameType = new CommandPer("game-type", "Fact", "AoC");
	static CommandPer cGateCount = new CommandPer("gate-count", "Fact", "AoC");
	static CommandPer cGenerateRandomNumber = new CommandPer("generate-random-number", "Action", "AoC");
	static CommandPer cGoal = new CommandPer("goal", "Fact", "AoC");
	static CommandPer cGoldAmount = new CommandPer("gold-amount", "Fact", "AoC");
	static CommandPer cHoldKohRuin = new CommandPer("hold-koh-ruin", "Fact", "AoC");
	static CommandPer cHoldRelics = new CommandPer("hold-relics", "Fact", "AoC");
	static CommandPer cHousingHeadroom = new CommandPer("housing-headroom", "Fact", "AoC");
	static CommandPer cIdleFarmCount = new CommandPer("idle-farm-count", "Fact", "AoC");
	static CommandPer cLog = new CommandPer("log", "Action", "AoC");
	static CommandPer cLogTrace = new CommandPer("log-trace", "Action", "AoC");
	static CommandPer cMapSize = new CommandPer("map-size", "Fact", "AoC");
	static CommandPer cMapType = new CommandPer("map-type", "Fact", "AoC");
	static CommandPer cMilitaryPopulation = new CommandPer("military-population", "Fact", "AoC");
	static CommandPer cPlayerComputer = new CommandPer("player-computer", "Fact", "AoC");
	static CommandPer cPlayerHuman = new CommandPer("player-human", "Fact", "AoC");
	static CommandPer cPlayerInGame = new CommandPer("player-in-game", "Fact", "AoC");
	static CommandPer cPlayerNumber = new CommandPer("player-number", "Fact", "AoC");
	static CommandPer cPlayerResigned = new CommandPer("player-resigned", "Fact", "AoC");
	static CommandPer cPlayerValid = new CommandPer("player-valid", "Fact", "AoC");
	static CommandPer cPlayersBuildingCount = new CommandPer("players-building-count", "Fact", "AoC");
	static CommandPer cPlayersBuildingTypeCount = new CommandPer("players-building-type-count", "Fact", "AoC");
	static CommandPer cPlayersCiv = new CommandPer("players-civ", "Fact", "AoC");
	static CommandPer cPlayersCivilianPopulation = new CommandPer("players-civilian-population", "Fact", "AoC");
	static CommandPer cPlayersCurrentAge = new CommandPer("players-current-age", "Fact", "AoC");
	static CommandPer cPlayersCurrentAgeTime = new CommandPer("players-current-age-time", "Fact", "AoC");
	static CommandPer cPlayersMilitaryPopulation = new CommandPer("players-military-population", "Fact", "AoC");
	static CommandPer cPlayersPopulation = new CommandPer("players-population", "Fact", "AoC");
	static CommandPer cPlayersScore = new CommandPer("players-score", "Fact", "AoC");
	static CommandPer cPlayersStance = new CommandPer("players-stance", "Fact", "AoC");
	static CommandPer cPlayersTribute = new CommandPer("players-tribute", "Fact", "AoC");
	static CommandPer cPlayersTributeMemory = new CommandPer("players-tribute-memory", "Fact", "AoC");
	static CommandPer cPlayersUnitCount = new CommandPer("players-unit-count", "Fact", "AoC");
	static CommandPer cPlayersUnitTypeCount = new CommandPer("players-unit-type-count", "Fact", "AoC");
	static CommandPer cPopulation = new CommandPer("population", "Fact", "AoC");
	static CommandPer cPopulationCap = new CommandPer("population-cap", "Fact", "AoC");
	static CommandPer cPopulationHeadroom = new CommandPer("population-headroom", "Fact", "AoC");
	static CommandPer cRandomNumber = new CommandPer("random-number", "Fact", "AoC");
	static CommandPer cRegicideGame = new CommandPer("regicide-game", "Fact", "AoC");
	static CommandPer cReleaseEscrow = new CommandPer("release-escrow", "Action", "AoC");
	static CommandPer cResearch = new CommandPer("research", "Action", "AoC");
	static CommandPer cResearchAvailable = new CommandPer("research-available", "Fact", "AoC");
	static CommandPer cResearchCompleted = new CommandPer("research-completed", "Fact", "AoC");
	static CommandPer cResign = new CommandPer("resign", "Action", "AoC");
	static CommandPer cResourceFound = new CommandPer("resource-found", "Fact", "AoC");
	static CommandPer cSellCommodity = new CommandPer("sell-commodity", "Action", "AoC");
	static CommandPer cSetAuthorEmail = new CommandPer("set-author-email", "Action", "AoC");
	static CommandPer cSetAuthorName = new CommandPer("set-author-name", "Action", "AoC");
	static CommandPer cSetAuthorVersion = new CommandPer("set-author-version", "Action", "AoC");
	static CommandPer cSetDifficultyParameter = new CommandPer("set-difficulty-parameter", "Action", "AoC");
	static CommandPer cSetDoctrine = new CommandPer("set-doctrine", "Action", "AoC");
	static CommandPer cSetEscrowPercentage = new CommandPer("set-escrow-percentage", "Action", "AoC");
	static CommandPer cSetGoal = new CommandPer("set-goal", "Action", "AoC");
	static CommandPer cSetSharedGoal = new CommandPer("set-shared-goal", "Action", "AoC");
	static CommandPer cSetSignal = new CommandPer("set-signal", "Action", "AoC");
	static CommandPer cSetStance = new CommandPer("set-stance", "Action", "AoC");
	static CommandPer cSetStrategicNumber = new CommandPer("set-strategic-number", "Action", "AoC");
	static CommandPer cSharedGoal = new CommandPer("shared-goal", "Fact", "AoC");
	static CommandPer cSheepAndForageTooFar = new CommandPer("sheep-and-forage-too-far", "Fact", "AoC");
	static CommandPer cSoldierCount = new CommandPer("soldier-count", "Fact", "AoC");
	static CommandPer cSpy = new CommandPer("spy", "Action", "AoC");
	static CommandPer cStanceToward = new CommandPer("stance-toward", "Fact", "AoC");
	static CommandPer cStartingAge = new CommandPer("starting-age", "Fact", "AoC");
	static CommandPer cStartingResources = new CommandPer("starting-resources", "Fact", "AoC");
	static CommandPer cStoneAmount = new CommandPer("stone-amount", "Fact", "AoC");
	static CommandPer cStrategicNumber = new CommandPer("strategic-number", "Fact", "AoC");
	static CommandPer cTaunt = new CommandPer("taunt", "Action", "AoC");
	static CommandPer cTauntDetected = new CommandPer("taunt-detected", "Fact", "AoC");
	static CommandPer cTauntUsingRange = new CommandPer("taunt-using-range", "Action", "AoC");
	static CommandPer cTimerTriggered = new CommandPer("timer-triggered", "Fact", "AoC");
	static CommandPer cTownUnderAttack = new CommandPer("town-under-attack", "Fact", "AoC");
	static CommandPer cTraceFact = new CommandPer("trace-fact", "Action", "AoC");
	static CommandPer cTrain = new CommandPer("train", "Action", "AoC");
	static CommandPer cTributeToPlayer = new CommandPer("tribute-to-player", "Action", "AoC");
	static CommandPer cTrue = new CommandPer("true", "Fact", "AoC");
	static CommandPer cUnitAvailable = new CommandPer("unit-available", "Fact", "AoC");
	static CommandPer cUnitCount = new CommandPer("unit-count", "Fact", "AoC");
	static CommandPer cUnitCountTotal = new CommandPer("unit-count-total", "Fact", "AoC");
	static CommandPer cUnitTypeCount = new CommandPer("unit-type-count", "Fact", "AoC");
	static CommandPer cUnitTypeCountTotal = new CommandPer("unit-type-count-total", "Fact", "AoC");
	static CommandPer cVictoryCondition = new CommandPer("victory-condition", "Fact", "AoC");
	static CommandPer cWallCompletedPercentage = new CommandPer("wall-completed-percentage", "Fact", "AoC");
	static CommandPer cWallInvisiblePercentage = new CommandPer("wall-invisible-percentage", "Fact", "AoC");
	static CommandPer cWarboatCount = new CommandPer("warboat-count", "Fact", "AoC");
	static CommandPer cWoodAmount = new CommandPer("wood-amount", "Fact", "AoC");
	static CommandPer cUpAddCostData = new CommandPer("up-add-cost-data", "Action", "UP");
	static CommandPer cUpAddObjectById = new CommandPer("up-add-object-by-id", "Both", "UP");
	static CommandPer cUpAddObjectCost = new CommandPer("up-add-object-cost", "Action", "UP");
	static CommandPer cUpAddPoint = new CommandPer("up-add-point", "Action", "UP");
	static CommandPer cUpAddResearchCost = new CommandPer("up-add-research-cost", "Action", "UP");
	static CommandPer cUpAlliedGoal = new CommandPer("up-allied-goal", "Fact", "UP");
	static CommandPer cUpAlliedResourceAmount = new CommandPer("up-allied-resource-amount", "Fact", "UP");
	static CommandPer cUpAlliedResourcePercent = new CommandPer("up-allied-resource-percent", "Fact", "UP");
	static CommandPer cUpAlliedSn = new CommandPer("up-allied-sn", "Fact", "UP");
	static CommandPer cUpAssignBuilders = new CommandPer("up-assign-builders", "Action", "UP");
	static CommandPer cUpAttackerClass = new CommandPer("up-attacker-class", "Fact", "UP");
	static CommandPer cUpBoundPoint = new CommandPer("up-bound-point", "Action", "UP");
	static CommandPer cUpBoundPrecisePoint = new CommandPer("up-bound-precise-point", "Action", "UP");
	static CommandPer cUpBuild = new CommandPer("up-build", "Action", "UP");
	static CommandPer cUpBuildLine = new CommandPer("up-build-line", "Action", "UP");
	static CommandPer cUpBuildingTypeInTown = new CommandPer("up-building-type-in-town", "Fact", "UP");
	static CommandPer cUpBuyCommodity = new CommandPer("up-buy-commodity", "Action", "UP");
	static CommandPer cUpCanBuild = new CommandPer("up-can-build", "Fact", "UP");
	static CommandPer cUpCanBuildLine = new CommandPer("up-can-build-line", "Fact", "UP");
	static CommandPer cUpCanResearch = new CommandPer("up-can-research", "Fact", "UP");
	static CommandPer cUpCanSearch = new CommandPer("up-can-search", "Fact", "UP");
	static CommandPer cUpCanTrain = new CommandPer("up-can-train", "Fact", "UP");
	static CommandPer cUpCcAddResource = new CommandPer("up-cc-add-resource", "Action", "UP");
	static CommandPer cUpCcSendCheat = new CommandPer("up-cc-send-cheat", "Action", "UP");
	static CommandPer cUpChangeName = new CommandPer("up-change-name", "Action", "UP");
	static CommandPer cUpChatDataToAll = new CommandPer("up-chat-data-to-all", "Action", "UP");
	static CommandPer cUpChatDataToPlayer = new CommandPer("up-chat-data-to-player", "Action", "UP");
	static CommandPer cUpChatDataToSelf = new CommandPer("up-chat-data-to-self", "Action", "UP");
	static CommandPer cUpCleanSearch = new CommandPer("up-clean-search", "Action", "UP");
	static CommandPer cUpCompareConst = new CommandPer("up-compare-const", "Fact", "UP");
	static CommandPer cUpCompareFlag = new CommandPer("up-compare-flag", "Fact", "UP");
	static CommandPer cUpCompareGoal = new CommandPer("up-compare-goal", "Fact", "UP");
	static CommandPer cUpCompareSn = new CommandPer("up-compare-sn", "Fact", "UP");
	static CommandPer cUpCompareText = new CommandPer("up-compare-text", "Fact", "UP");
	static CommandPer cUpCopyPoint = new CommandPer("up-copy-point", "Action", "UP");
	static CommandPer cUpCreateGroup = new CommandPer("up-create-group", "Action", "UP");
	static CommandPer cUpCrossTiles = new CommandPer("up-cross-tiles", "Action", "UP");
	static CommandPer cUpDefenderCount = new CommandPer("up-defender-count", "Fact", "UP");
	static CommandPer cUpDeleteDistantFarms = new CommandPer("up-delete-distant-farms", "Action", "UP");
	static CommandPer cUpDeleteIdleUnits = new CommandPer("up-delete-idle-units", "Action", "UP");
	static CommandPer cUpDeleteObjects = new CommandPer("up-delete-objects", "Action", "UP");
	static CommandPer cUpDisbandGroupType = new CommandPer("up-disband-group-type", "Action", "UP");
	static CommandPer cUpDropResources = new CommandPer("up-drop-resources", "Action", "UP");
	static CommandPer cUpEnemyBuildingsInTown = new CommandPer("up-enemy-buildings-in-town", "Fact", "UP");
	static CommandPer cUpEnemyUnitsInTown = new CommandPer("up-enemy-units-in-town", "Fact", "UP");
	static CommandPer cUpEnemyVillagersInTown = new CommandPer("up-enemy-villagers-in-town", "Fact", "UP");
	static CommandPer cUpFilterDistance = new CommandPer("up-filter-distance", "Action", "UP");
	static CommandPer cUpFilterExclude = new CommandPer("up-filter-exclude", "Action", "UP");
	static CommandPer cUpFilterGarrison = new CommandPer("up-filter-garrison", "Action", "UP");
	static CommandPer cUpFilterInclude = new CommandPer("up-filter-include", "Action", "UP");
	static CommandPer cUpFilterRange = new CommandPer("up-filter-range", "Action", "UP");
	static CommandPer cUpFilterStatus = new CommandPer("up-filter-status", "Action", "UP");
	static CommandPer cUpFindFlare = new CommandPer("up-find-flare", "Action", "UP");
	static CommandPer cUpFindLocal = new CommandPer("up-find-local", "Both", "UP");
	static CommandPer cUpFindNextPlayer = new CommandPer("up-find-next-player", "Action", "UP");
	static CommandPer cUpFindPlayer = new CommandPer("up-find-player", "Action", "UP");
	static CommandPer cUpFindPlayerFlare = new CommandPer("up-find-player-flare", "Action", "UP");
	static CommandPer cUpFindRemote = new CommandPer("up-find-remote", "Both", "UP");
	static CommandPer cUpFindResource = new CommandPer("up-find-resource", "Both", "UP");
	static CommandPer cUpFindStatusLocal = new CommandPer("up-find-status-local", "Both", "UP");
	static CommandPer cUpFindStatusRemote = new CommandPer("up-find-status-remote", "Both", "UP");
	static CommandPer cUpFullResetSearch = new CommandPer("up-full-reset-search", "Action", "UP");
	static CommandPer cUpGaiaTypeCount = new CommandPer("up-gaia-type-count", "Fact", "UP");
	static CommandPer cUpGaiaTypeCountTotal = new CommandPer("up-gaia-type-count-total", "Fact", "UP");
	static CommandPer cUpGarrison = new CommandPer("up-garrison", "Action", "UP");
	static CommandPer cUpGatherInside = new CommandPer("up-gather-inside", "Action", "UP");
	static CommandPer cUpGetAttackerClass = new CommandPer("up-get-attacker-class", "Action", "UP");
	static CommandPer cUpGetCostDelta = new CommandPer("up-get-cost-delta", "Action", "UP");
	static CommandPer cUpGetEvent = new CommandPer("up-get-event", "Action", "UP");
	static CommandPer cUpGetFact = new CommandPer("up-get-fact", "Both", "UP");
	static CommandPer cUpGetFactMax = new CommandPer("up-get-fact-max", "Both", "UP");
	static CommandPer cUpGetFactMin = new CommandPer("up-get-fact-min", "Both", "UP");
	static CommandPer cUpGetFactSum = new CommandPer("up-get-fact-sum", "Both", "UP");
	static CommandPer cUpGetFocusFact = new CommandPer("up-get-focus-fact", "Both", "UP");
	static CommandPer cUpGetGroupSize = new CommandPer("up-get-group-size", "Action", "UP");
	static CommandPer cUpGetGuardState = new CommandPer("up-get-guard-state", "Action", "UP");
	static CommandPer cUpGetIndirectGoal = new CommandPer("up-get-indirect-goal", "Action", "UP");
	static CommandPer cUpGetObjectData = new CommandPer("up-get-object-data", "Both", "UP");
	static CommandPer cUpGetObjectTargetData = new CommandPer("up-get-object-target-data", "Both", "UP");
	static CommandPer cUpGetObjectTypeData = new CommandPer("up-get-object-type-data", "Action", "UP");
	static CommandPer cUpGetPathDistance = new CommandPer("up-get-path-distance", "Action", "UP");
	static CommandPer cUpGetPlayerColor = new CommandPer("up-get-player-color", "Action", "UP");
	static CommandPer cUpGetPlayerFact = new CommandPer("up-get-player-fact", "Both", "UP");
	static CommandPer cUpGetPoint = new CommandPer("up-get-point", "Action", "UP");
	static CommandPer cUpGetPointContains = new CommandPer("up-get-point-contains", "Both", "UP");
	static CommandPer cUpGetPointDistance = new CommandPer("up-get-point-distance", "Action", "UP");
	static CommandPer cUpGetPointElevation = new CommandPer("up-get-point-elevation", "Action", "UP");
	static CommandPer cUpGetPointTerrain = new CommandPer("up-get-point-terrain", "Action", "UP");
	static CommandPer cUpGetPointZone = new CommandPer("up-get-point-zone", "Action", "UP");
	static CommandPer cUpGetPreciseTime = new CommandPer("up-get-precise-time", "Action", "UP");
	static CommandPer cUpGetProjectilePlayer = new CommandPer("up-get-projectile-player", "Action", "UP");
	static CommandPer cUpGetRuleId = new CommandPer("up-get-rule-id", "Action", "UP");
	static CommandPer cUpGetSearchState = new CommandPer("up-get-search-state", "Action", "UP");
	static CommandPer cUpGetSharedGoal = new CommandPer("up-get-shared-goal", "Action", "UP");
	static CommandPer cUpGetSignal = new CommandPer("up-get-signal", "Action", "UP");
	static CommandPer cUpGetTargetFact = new CommandPer("up-get-target-fact", "Both", "UP");
	static CommandPer cUpGetThreatData = new CommandPer("up-get-threat-data", "Action", "UP");
	static CommandPer cUpGetTimer = new CommandPer("up-get-timer", "Action", "UP");
	static CommandPer cUpGetTreatyData = new CommandPer("up-get-treaty-data", "Action", "DE");
	static CommandPer cUpGetUpgradeId = new CommandPer("up-get-upgrade-id", "Action", "UP");
	static CommandPer cUpGetVictoryData = new CommandPer("up-get-victory-data", "Action", "UP");
	static CommandPer cUpGetVictoryLimit = new CommandPer("up-get-victory-limit", "Action", "UP");
	static CommandPer cUpGroupSize = new CommandPer("up-group-size", "Fact", "UP");
	static CommandPer cUpGuardUnit = new CommandPer("up-guard-unit", "Action", "UP");
	static CommandPer cUpIdleUnitCount = new CommandPer("up-idle-unit-count", "Fact", "UP");
	static CommandPer cUpJumpDirect = new CommandPer("up-jump-direct", "Action", "UP");
	static CommandPer cUpJumpDynamic = new CommandPer("up-jump-dynamic", "Action", "UP");
	static CommandPer cUpJumpRule = new CommandPer("up-jump-rule", "Action", "UP");
	static CommandPer cUpLerpPercent = new CommandPer("up-lerp-percent", "Action", "UP");
	static CommandPer cUpLerpTiles = new CommandPer("up-lerp-tiles", "Action", "UP");
	static CommandPer cUpLogData = new CommandPer("up-log-data", "Action", "UP");
	static CommandPer cUpModifyEscrow = new CommandPer("up-modify-escrow", "Action", "UP");
	static CommandPer cUpModifyFlag = new CommandPer("up-modify-flag", "Action", "UP");
	static CommandPer cUpModifyGoal = new CommandPer("up-modify-goal", "Both", "UP");
	static CommandPer cUpModifyGroupFlag = new CommandPer("up-modify-group-flag", "Action", "UP");
	static CommandPer cUpModifySn = new CommandPer("up-modify-sn", "Both", "UP");
	static CommandPer cUpObjectData = new CommandPer("up-object-data", "Fact", "UP");
	static CommandPer cUpObjectTargetData = new CommandPer("up-object-target-data", "Fact", "UP");
	static CommandPer cUpObjectTypeCount = new CommandPer("up-object-type-count", "Fact", "UP");
	static CommandPer cUpObjectTypeCountTotal = new CommandPer("up-object-type-count-total", "Fact", "UP");
	static CommandPer cUpPathDistance = new CommandPer("up-path-distance", "Fact", "UP");
	static CommandPer cUpPendingObjects = new CommandPer("up-pending-objects", "Fact", "UP");
	static CommandPer cUpPendingPlacement = new CommandPer("up-pending-placement", "Fact", "UP");
	static CommandPer cUpPlayerDistance = new CommandPer("up-player-distance", "Fact", "UP");
	static CommandPer cUpPlayersInGame = new CommandPer("up-players-in-game", "Fact", "UP");
	static CommandPer cUpPointContains = new CommandPer("up-point-contains", "Fact", "UP");
	static CommandPer cUpPointDistance = new CommandPer("up-point-distance", "Fact", "UP");
	static CommandPer cUpPointElevation = new CommandPer("up-point-elevation", "Fact", "UP");
	static CommandPer cUpPointExplored = new CommandPer("up-point-explored", "Fact", "UP");
	static CommandPer cUpPointTerrain = new CommandPer("up-point-terrain", "Fact", "UP");
	static CommandPer cUpPointZone = new CommandPer("up-point-zone", "Fact", "UP");
	static CommandPer cUpProjectileDetected = new CommandPer("up-projectile-detected", "Fact", "UP");
	static CommandPer cUpProjectileTarget = new CommandPer("up-projectile-target", "Fact", "UP");
	static CommandPer cUpReleaseEscrow = new CommandPer("up-release-escrow", "Action", "UP");
	static CommandPer cUpRemainingBoarAmount = new CommandPer("up-remaining-boar-amount", "Fact", "UP");
	static CommandPer cUpRemoveObjects = new CommandPer("up-remove-objects", "Action", "UP");
	static CommandPer cUpRequestHunters = new CommandPer("up-request-hunters", "Action", "UP");
	static CommandPer cUpResearch = new CommandPer("up-research", "Action", "UP");
	static CommandPer cUpResearchStatus = new CommandPer("up-research-status", "Fact", "UP");
	static CommandPer cUpResetAttackNow = new CommandPer("up-reset-attack-now", "Action", "UP");
	static CommandPer cUpResetBuilding = new CommandPer("up-reset-building", "Action", "UP");
	static CommandPer cUpResetCostData = new CommandPer("up-reset-cost-data", "Action", "UP");
	static CommandPer cUpResetFilters = new CommandPer("up-reset-filters", "Action", "UP");
	static CommandPer cUpResetGroup = new CommandPer("up-reset-group", "Action", "UP");
	static CommandPer cUpResetPlacement = new CommandPer("up-reset-placement", "Action", "UP");
	static CommandPer cUpResetScouts = new CommandPer("up-reset-scouts", "Action", "UP");
	static CommandPer cUpResetSearch = new CommandPer("up-reset-search", "Action", "UP");
	static CommandPer cUpResetTargetPriorities = new CommandPer("up-reset-target-priorities", "Action", "UP");
	static CommandPer cUpResetUnit = new CommandPer("up-reset-unit", "Action", "UP");
	static CommandPer cUpResourceAmount = new CommandPer("up-resource-amount", "Fact", "UP");
	static CommandPer cUpResourcePercent = new CommandPer("up-resource-percent", "Fact", "UP");
	static CommandPer cUpRetaskGatherers = new CommandPer("up-retask-gatherers", "Action", "UP");
	static CommandPer cUpRetreatNow = new CommandPer("up-retreat-now", "Action", "UP");
	static CommandPer cUpRetreatTo = new CommandPer("up-retreat-to", "Action", "UP");
	static CommandPer cUpSellCommodity = new CommandPer("up-sell-commodity", "Action", "UP");
	static CommandPer cUpSendFlare = new CommandPer("up-send-flare", "Action", "UP");
	static CommandPer cUpSendScout = new CommandPer("up-send-scout", "Action", "UP");
	static CommandPer cUpSetAttackStance = new CommandPer("up-set-attack-stance", "Action", "UP");
	static CommandPer cUpSetDefensePriority = new CommandPer("up-set-defense-priority", "Action", "UP");
	static CommandPer cUpSetEvent = new CommandPer("up-set-event", "Action", "UP");
	static CommandPer cUpSetGroup = new CommandPer("up-set-group", "Action", "UP");
	static CommandPer cUpSetIndirectGoal = new CommandPer("up-set-indirect-goal", "Action", "UP");
	static CommandPer cUpSetOffensePriority = new CommandPer("up-set-offense-priority", "Action", "UP");
	static CommandPer cUpSetPlacementData = new CommandPer("up-set-placement-data", "Action", "UP");
	static CommandPer cUpSetPreciseTargetPoint = new CommandPer("up-set-precise-target-point", "Action", "UP");
	static CommandPer cUpSetSharedGoal = new CommandPer("up-set-shared-goal", "Action", "UP");
	static CommandPer cUpSetSignal = new CommandPer("up-set-signal", "Action", "UP");
	static CommandPer cUpSetTargetById = new CommandPer("up-set-target-by-id", "Both", "UP");
	static CommandPer cUpSetTargetObject = new CommandPer("up-set-target-object", "Both", "UP");
	static CommandPer cUpSetTargetPoint = new CommandPer("up-set-target-point", "Action", "UP");
	static CommandPer cUpSetTimer = new CommandPer("up-set-timer", "Action", "UP");
	static CommandPer cUpSetupCostData = new CommandPer("up-setup-cost-data", "Action", "UP");
	static CommandPer cUpStoreMapName = new CommandPer("up-store-map-name", "Action", "UP");
	static CommandPer cUpStoreObjectName = new CommandPer("up-store-object-name", "Action", "UP");
	static CommandPer cUpStorePlayerChat = new CommandPer("up-store-player-chat", "Action", "UP");
	static CommandPer cUpStorePlayerName = new CommandPer("up-store-player-name", "Action", "UP");
	static CommandPer cUpStoreTechName = new CommandPer("up-store-tech-name", "Action", "UP");
	static CommandPer cUpStoreText = new CommandPer("up-store-text", "Action", "UP");
	static CommandPer cUpStoreTypeName = new CommandPer("up-store-type-name", "Action", "UP");
	static CommandPer cUpTargetObjects = new CommandPer("up-target-objects", "Action", "UP");
	static CommandPer cUpTargetPoint = new CommandPer("up-target-point", "Action", "UP");
	static CommandPer cUpTimerStatus = new CommandPer("up-timer-status", "Fact", "UP");
	static CommandPer cUpTrain = new CommandPer("up-train", "Action", "UP");
	static CommandPer cUpTrainSiteReady = new CommandPer("up-train-site-ready", "Fact", "UP");
	static CommandPer cUpTributeToPlayer = new CommandPer("up-tribute-to-player", "Action", "UP");
	static CommandPer cUpUngarrison = new CommandPer("up-ungarrison", "Action", "UP");
	static CommandPer cUpUnitTypeInTown = new CommandPer("up-unit-type-in-town", "Fact", "UP");
	static CommandPer cUpUpdateTargets = new CommandPer("up-update-targets", "Action", "UP");
	static CommandPer cUpVillagerTypeInTown = new CommandPer("up-villager-type-in-town", "Fact", "UP");
	static CommandPer cFeBreakPoint = new CommandPer("fe-break-point", "Action", "DE");
	static CommandPer cFeCcEffectAmount = new CommandPer("fe-cc-effect-amount", "Action", "DE");
	static CommandPer cFeCcEffectPercent = new CommandPer("fe-cc-effect-percent", "Action", "DE");
	static CommandPer cFeFilterGarrisoned = new CommandPer("fe-filter-garrisoned", "Action", "DE");
	static CommandPer cFeSubGameType = new CommandPer("fe-sub-game-type", "Fact", "DE");
	static CommandPer cXsScriptCall = new CommandPer("xs-script-call", "Both", "DE");

	static CommandPer cUpdateSearchState = new CommandPer("update-search-state", "Action", "Barracks");

	public static final List<CommandPer> commandsArray = new ArrayList<CommandPer>(Arrays.asList(cAcknowledgeEvent,
			cAcknowledgeTaunt, cAttackNow, cAttackSoldierCount, cAttackWarboatCount, cBuild, cBuildForward, cBuildGate,
			cBuildWall, cBuildingAvailable, cBuildingCount, cBuildingCountTotal, cBuildingTypeCount,
			cBuildingTypeCountTotal, cBuyCommodity, cCanAffordBuilding, cCanAffordCompleteWall, cCanAffordResearch,
			cCanAffordUnit, cCanBuild, cCanBuildWithEscrow, cCanBuildGate, cCanBuildGateWithEscrow, cCanBuildWall,
			cCanBuildWallWithEscrow, cCanBuyCommodity, cCanResearch, cCanResearchWithEscrow, cCanSellCommodity, cCanSpy,
			cCanSpyWithEscrow, cCanTrain, cCanTrainWithEscrow, cCcAddResource, cCcPlayersBuildingCount,
			cCcPlayersBuildingTypeCount, cCcPlayersUnitCount, cCcPlayersUnitTypeCount, cChatLocal, cChatLocalToSelf,
			cChatLocalUsingId, cChatLocalUsingRange, cChatToAll, cChatToAllUsingId, cChatToAllUsingRange, cChatToAllies,
			cChatToAlliesUsingId, cChatToAlliesUsingRange, cChatToEnemies, cChatToEnemiesUsingId,
			cChatToEnemiesUsingRange, cChatToPlayer, cChatToPlayerUsingId, cChatToPlayerUsingRange, cChatTrace,
			cCheatsEnabled, cCivilianPopulation, cCivSelected, cClearTributeMemory, cCommodityBuyingPrice,
			cCommoditySellingPrice, cCurrentAge, cCurrentAgeTime, cCurrentScore, cDeathMatchGame, cDefendSoldierCount,
			cDefendWarboatCount, cDeleteBuilding, cDeleteUnit, cDifficulty, cDisableRule, cDisableSelf, cDisableTimer,
			cDoctrine, cDoNothing, cDropsiteMinDistance, cEnableRule, cEnableTimer, cEnableWallPlacement,
			cEnemyBuildingsInTown, cEnemyCapturedRelics, cEscrowAmount, cEventDetected, cFalse, cFoodAmount, cGameTime,
			cGameType, cGateCount, cGenerateRandomNumber, cGoal, cGoldAmount, cHoldKohRuin, cHoldRelics,
			cHousingHeadroom, cIdleFarmCount, cLog, cLogTrace, cMapSize, cMapType, cMilitaryPopulation, cPlayerComputer,
			cPlayerHuman, cPlayerInGame, cPlayerNumber, cPlayerResigned, cPlayerValid, cPlayersBuildingCount,
			cPlayersBuildingTypeCount, cPlayersCiv, cPlayersCivilianPopulation, cPlayersCurrentAge,
			cPlayersCurrentAgeTime, cPlayersMilitaryPopulation, cPlayersPopulation, cPlayersScore, cPlayersStance,
			cPlayersTribute, cPlayersTributeMemory, cPlayersUnitCount, cPlayersUnitTypeCount, cPopulation,
			cPopulationCap, cPopulationHeadroom, cRandomNumber, cRegicideGame, cReleaseEscrow, cResearch,
			cResearchAvailable, cResearchCompleted, cResign, cResourceFound, cSellCommodity, cSetAuthorEmail,
			cSetAuthorName, cSetAuthorVersion, cSetDifficultyParameter, cSetDoctrine, cSetEscrowPercentage, cSetGoal,
			cSetSharedGoal, cSetSignal, cSetStance, cSetStrategicNumber, cSharedGoal, cSheepAndForageTooFar,
			cSoldierCount, cSpy, cStanceToward, cStartingAge, cStartingResources, cStoneAmount, cStrategicNumber,
			cTaunt, cTauntDetected, cTauntUsingRange, cTimerTriggered, cTownUnderAttack, cTraceFact, cTrain,
			cTributeToPlayer, cTrue, cUnitAvailable, cUnitCount, cUnitCountTotal, cUnitTypeCount, cUnitTypeCountTotal,
			cVictoryCondition, cWallCompletedPercentage, cWallInvisiblePercentage, cWarboatCount, cWoodAmount,
			cUpAddCostData, cUpAddObjectById, cUpAddObjectCost, cUpAddPoint, cUpAddResearchCost, cUpAlliedGoal,
			cUpAlliedResourceAmount, cUpAlliedResourcePercent, cUpAlliedSn, cUpAssignBuilders, cUpAttackerClass,
			cUpBoundPoint, cUpBoundPrecisePoint, cUpBuild, cUpBuildLine, cUpBuildingTypeInTown, cUpBuyCommodity,
			cUpCanBuild, cUpCanBuildLine, cUpCanResearch, cUpCanSearch, cUpCanTrain, cUpCcAddResource, cUpCcSendCheat,
			cUpChangeName, cUpChatDataToAll, cUpChatDataToPlayer, cUpChatDataToSelf, cUpCleanSearch, cUpCompareConst,
			cUpCompareFlag, cUpCompareGoal, cUpCompareSn, cUpCompareText, cUpCopyPoint, cUpCreateGroup, cUpCrossTiles,
			cUpDefenderCount, cUpDeleteDistantFarms, cUpDeleteIdleUnits, cUpDeleteObjects, cUpDisbandGroupType,
			cUpDropResources, cUpEnemyBuildingsInTown, cUpEnemyUnitsInTown, cUpEnemyVillagersInTown, cUpFilterDistance,
			cUpFilterExclude, cUpFilterGarrison, cUpFilterInclude, cUpFilterRange, cUpFilterStatus, cUpFindFlare,
			cUpFindLocal, cUpFindNextPlayer, cUpFindPlayer, cUpFindPlayerFlare, cUpFindRemote, cUpFindResource,
			cUpFindStatusLocal, cUpFindStatusRemote, cUpFullResetSearch, cUpGaiaTypeCount, cUpGaiaTypeCountTotal,
			cUpGarrison, cUpGatherInside, cUpGetAttackerClass, cUpGetCostDelta, cUpGetEvent, cUpGetFact, cUpGetFactMax,
			cUpGetFactMin, cUpGetFactSum, cUpGetFocusFact, cUpGetGroupSize, cUpGetGuardState, cUpGetIndirectGoal,
			cUpGetObjectData, cUpGetObjectTargetData, cUpGetObjectTypeData, cUpGetPathDistance, cUpGetPlayerColor,
			cUpGetPlayerFact, cUpGetPoint, cUpGetPointContains, cUpGetPointDistance, cUpGetPointElevation,
			cUpGetPointTerrain, cUpGetPointZone, cUpGetPreciseTime, cUpGetProjectilePlayer, cUpGetRuleId,
			cUpGetSearchState, cUpGetSharedGoal, cUpGetSignal, cUpGetTargetFact, cUpGetThreatData, cUpGetTimer,
			cUpGetTreatyData, cUpGetUpgradeId, cUpGetVictoryData, cUpGetVictoryLimit, cUpGroupSize, cUpGuardUnit,
			cUpIdleUnitCount, cUpJumpDirect, cUpJumpDynamic, cUpJumpRule, cUpLerpPercent, cUpLerpTiles, cUpLogData,
			cUpModifyEscrow, cUpModifyFlag, cUpModifyGoal, cUpModifyGroupFlag, cUpModifySn, cUpObjectData,
			cUpObjectTargetData, cUpObjectTypeCount, cUpObjectTypeCountTotal, cUpPathDistance, cUpPendingObjects,
			cUpPendingPlacement, cUpPlayerDistance, cUpPlayersInGame, cUpPointContains, cUpPointDistance,
			cUpPointElevation, cUpPointExplored, cUpPointTerrain, cUpPointZone, cUpProjectileDetected,
			cUpProjectileTarget, cUpReleaseEscrow, cUpRemainingBoarAmount, cUpRemoveObjects, cUpRequestHunters,
			cUpResearch, cUpResearchStatus, cUpResetAttackNow, cUpResetBuilding, cUpResetCostData, cUpResetFilters,
			cUpResetGroup, cUpResetPlacement, cUpResetScouts, cUpResetSearch, cUpResetTargetPriorities, cUpResetUnit,
			cUpResourceAmount, cUpResourcePercent, cUpRetaskGatherers, cUpRetreatNow, cUpRetreatTo, cUpSellCommodity,
			cUpSendFlare, cUpSendScout, cUpSetAttackStance, cUpSetDefensePriority, cUpSetEvent, cUpSetGroup,
			cUpSetIndirectGoal, cUpSetOffensePriority, cUpSetPlacementData, cUpSetPreciseTargetPoint, cUpSetSharedGoal,
			cUpSetSignal, cUpSetTargetById, cUpSetTargetObject, cUpSetTargetPoint, cUpSetTimer, cUpSetupCostData,
			cUpStoreMapName, cUpStoreObjectName, cUpStorePlayerChat, cUpStorePlayerName, cUpStoreTechName, cUpStoreText,
			cUpStoreTypeName, cUpTargetObjects, cUpTargetPoint, cUpTimerStatus, cUpTrain, cUpTrainSiteReady,
			cUpTributeToPlayer, cUpUngarrison, cUpUnitTypeInTown, cUpUpdateTargets, cUpVillagerTypeInTown,
			cFeBreakPoint, cFeCcEffectAmount, cFeCcEffectPercent, cFeFilterGarrisoned, cFeSubGameType, cXsScriptCall,
			cUpdateSearchState));
	private static boolean alreadyFilled = false;

	public CommandsContainer() {
		if (!alreadyFilled) {
			cAcknowledgeEvent.commandParameters.add("EventType");
			cAcknowledgeEvent.commandParameters.add("EventId");
			cAcknowledgeTaunt.commandParameters.add("PlayerNumber");
			cAcknowledgeTaunt.commandParameters.add("TauntId");
			cAttackSoldierCount.commandParameters.add("compareOp");
			cAttackSoldierCount.commandParameters.add("Value");
			cAttackWarboatCount.commandParameters.add("compareOp");
			cAttackWarboatCount.commandParameters.add("Value");
			cBuild.commandParameters.add("BuildingId");
			cBuildForward.commandParameters.add("BuildingId");
			cBuildGate.commandParameters.add("Perimeter");
			cBuildWall.commandParameters.add("Perimeter");
			cBuildWall.commandParameters.add("WallId");
			cBuildingAvailable.commandParameters.add("BuildingId");
			cBuildingCount.commandParameters.add("compareOp");
			cBuildingCount.commandParameters.add("Value");
			cBuildingCountTotal.commandParameters.add("compareOp");
			cBuildingCountTotal.commandParameters.add("Value");
			cBuildingTypeCount.commandParameters.add("BuildingId");
			cBuildingTypeCount.commandParameters.add("compareOp");
			cBuildingTypeCount.commandParameters.add("Value");
			cBuildingTypeCountTotal.commandParameters.add("BuildingId");
			cBuildingTypeCountTotal.commandParameters.add("compareOp");
			cBuildingTypeCountTotal.commandParameters.add("Value");
			cBuyCommodity.commandParameters.add("Commodity");
			cCanAffordBuilding.commandParameters.add("BuildingId");
			cCanAffordCompleteWall.commandParameters.add("Perimeter");
			cCanAffordCompleteWall.commandParameters.add("WallId");
			cCanAffordResearch.commandParameters.add("TechId");
			cCanAffordUnit.commandParameters.add("UnitId");
			cCanBuild.commandParameters.add("BuildingId");
			cCanBuildWithEscrow.commandParameters.add("BuildingId");
			cCanBuildGate.commandParameters.add("Perimeter");
			cCanBuildGateWithEscrow.commandParameters.add("Perimeter");
			cCanBuildWall.commandParameters.add("Perimeter");
			cCanBuildWall.commandParameters.add("WallId");
			cCanBuildWallWithEscrow.commandParameters.add("Perimeter");
			cCanBuildWallWithEscrow.commandParameters.add("WallId");
			cCanBuyCommodity.commandParameters.add("Commodity");
			cCanResearch.commandParameters.add("TechId");
			cCanResearchWithEscrow.commandParameters.add("TechId");
			cCanSellCommodity.commandParameters.add("Commodity");
			cCanTrain.commandParameters.add("UnitId");
			cCanTrainWithEscrow.commandParameters.add("UnitId");
			cCcAddResource.commandParameters.add("Resource");
			cCcAddResource.commandParameters.add("Value");
			cCcPlayersBuildingCount.commandParameters.add("PlayerNumber");
			cCcPlayersBuildingCount.commandParameters.add("compareOp");
			cCcPlayersBuildingCount.commandParameters.add("Value");
			cCcPlayersBuildingTypeCount.commandParameters.add("PlayerNumber");
			cCcPlayersBuildingTypeCount.commandParameters.add("BuildingId");
			cCcPlayersBuildingTypeCount.commandParameters.add("compareOp");
			cCcPlayersBuildingTypeCount.commandParameters.add("Value");
			cCcPlayersUnitCount.commandParameters.add("PlayerNumber");
			cCcPlayersUnitCount.commandParameters.add("compareOp");
			cCcPlayersUnitCount.commandParameters.add("Value");
			cCcPlayersUnitTypeCount.commandParameters.add("PlayerNumber");
			cCcPlayersUnitTypeCount.commandParameters.add("UnitId");
			cCcPlayersUnitTypeCount.commandParameters.add("compareOp");
			cCcPlayersUnitTypeCount.commandParameters.add("Value");
			cChatLocal.commandParameters.add("String");
			cChatLocalToSelf.commandParameters.add("String");
			cChatLocalUsingId.commandParameters.add("LanguageId");
			cChatLocalUsingRange.commandParameters.add("LanguageId");
			cChatLocalUsingRange.commandParameters.add("Value");
			cChatToAll.commandParameters.add("String");
			cChatToAllUsingId.commandParameters.add("LanguageId");
			cChatToAllUsingRange.commandParameters.add("LanguageId");
			cChatToAllUsingRange.commandParameters.add("Value");
			cChatToAllies.commandParameters.add("String");
			cChatToAlliesUsingId.commandParameters.add("LanguageId");
			cChatToAlliesUsingRange.commandParameters.add("LanguageId");
			cChatToAlliesUsingRange.commandParameters.add("Value");
			cChatToEnemies.commandParameters.add("String");
			cChatToEnemiesUsingId.commandParameters.add("LanguageId");
			cChatToEnemiesUsingRange.commandParameters.add("LanguageId");
			cChatToEnemiesUsingRange.commandParameters.add("Value");
			cChatToPlayer.commandParameters.add("PlayerNumber");
			cChatToPlayer.commandParameters.add("String");
			cChatToPlayerUsingId.commandParameters.add("PlayerNumber");
			cChatToPlayerUsingId.commandParameters.add("LanguageId");
			cChatToPlayerUsingRange.commandParameters.add("PlayerNumber");
			cChatToPlayerUsingRange.commandParameters.add("LanguageId");
			cChatToPlayerUsingRange.commandParameters.add("Value");
			cChatTrace.commandParameters.add("Value");
			cCivilianPopulation.commandParameters.add("compareOp");
			cCivilianPopulation.commandParameters.add("Value");
			cCivSelected.commandParameters.add("Civ");
			cClearTributeMemory.commandParameters.add("PlayerNumber");
			cClearTributeMemory.commandParameters.add("Resource");
			cCommodityBuyingPrice.commandParameters.add("Commodity");
			cCommodityBuyingPrice.commandParameters.add("compareOp");
			cCommodityBuyingPrice.commandParameters.add("Value");
			cCommoditySellingPrice.commandParameters.add("Commodity");
			cCommoditySellingPrice.commandParameters.add("compareOp");
			cCommoditySellingPrice.commandParameters.add("Value");
			cCurrentAge.commandParameters.add("compareOp");
			cCurrentAge.commandParameters.add("Age");
			cCurrentAgeTime.commandParameters.add("compareOp");
			cCurrentAgeTime.commandParameters.add("Value");
			cCurrentScore.commandParameters.add("compareOp");
			cCurrentScore.commandParameters.add("Value");
			cDefendSoldierCount.commandParameters.add("compareOp");
			cDefendSoldierCount.commandParameters.add("Value");
			cDefendWarboatCount.commandParameters.add("compareOp");
			cDefendWarboatCount.commandParameters.add("Value");
			cDeleteBuilding.commandParameters.add("BuildingId");
			cDeleteUnit.commandParameters.add("UnitId");
			cDifficulty.commandParameters.add("compareOp");
			cDifficulty.commandParameters.add("Difficulty");
			cDisableRule.commandParameters.add("Value");
			cDisableTimer.commandParameters.add("TimerId");
			cDoctrine.commandParameters.add("Value");
			cDropsiteMinDistance.commandParameters.add("Resource");
			cDropsiteMinDistance.commandParameters.add("compareOp");
			cDropsiteMinDistance.commandParameters.add("Value");
			cEnableRule.commandParameters.add("Value");
			cEnableTimer.commandParameters.add("TimerId");
			cEnableTimer.commandParameters.add("Value");
			cEnableWallPlacement.commandParameters.add("Perimeter");
			cEscrowAmount.commandParameters.add("Resource");
			cEscrowAmount.commandParameters.add("compareOp");
			cEscrowAmount.commandParameters.add("Value");
			cEventDetected.commandParameters.add("EventType");
			cEventDetected.commandParameters.add("EventId");
			cFoodAmount.commandParameters.add("compareOp");
			cFoodAmount.commandParameters.add("Value");
			cGameTime.commandParameters.add("compareOp");
			cGameTime.commandParameters.add("Value");
			cGameType.commandParameters.add("compareOp");
			cGameType.commandParameters.add("GameType");
			cGateCount.commandParameters.add("Perimeter");
			cGateCount.commandParameters.add("compareOp");
			cGateCount.commandParameters.add("Value");
			cGenerateRandomNumber.commandParameters.add("Value");
			cGoal.commandParameters.add("GoalId");
			cGoal.commandParameters.add("Value");
			cGoldAmount.commandParameters.add("compareOp");
			cGoldAmount.commandParameters.add("Value");
			cHousingHeadroom.commandParameters.add("compareOp");
			cHousingHeadroom.commandParameters.add("Value");
			cIdleFarmCount.commandParameters.add("compareOp");
			cIdleFarmCount.commandParameters.add("Value");
			cLog.commandParameters.add("String");
			cLogTrace.commandParameters.add("Value");
			cMapSize.commandParameters.add("MapSize");
			cMapType.commandParameters.add("MapType");
			cMilitaryPopulation.commandParameters.add("compareOp");
			cMilitaryPopulation.commandParameters.add("Value");
			cPlayerComputer.commandParameters.add("PlayerNumber");
			cPlayerHuman.commandParameters.add("PlayerNumber");
			cPlayerInGame.commandParameters.add("PlayerNumber");
			cPlayerNumber.commandParameters.add("PlayerNumber");
			cPlayerResigned.commandParameters.add("PlayerNumber");
			cPlayerValid.commandParameters.add("PlayerNumber");
			cPlayersBuildingCount.commandParameters.add("PlayerNumber");
			cPlayersBuildingCount.commandParameters.add("compareOp");
			cPlayersBuildingCount.commandParameters.add("Value");
			cPlayersBuildingTypeCount.commandParameters.add("PlayerNumber");
			cPlayersBuildingTypeCount.commandParameters.add("BuildingId");
			cPlayersBuildingTypeCount.commandParameters.add("compareOp");
			cPlayersBuildingTypeCount.commandParameters.add("Value");
			cPlayersCiv.commandParameters.add("PlayerNumber");
			cPlayersCiv.commandParameters.add("Civ");
			cPlayersCivilianPopulation.commandParameters.add("PlayerNumber");
			cPlayersCivilianPopulation.commandParameters.add("compareOp");
			cPlayersCivilianPopulation.commandParameters.add("Value");
			cPlayersCurrentAge.commandParameters.add("PlayerNumber");
			cPlayersCurrentAge.commandParameters.add("compareOp");
			cPlayersCurrentAge.commandParameters.add("Age");
			cPlayersCurrentAgeTime.commandParameters.add("PlayerNumber");
			cPlayersCurrentAgeTime.commandParameters.add("compareOp");
			cPlayersCurrentAgeTime.commandParameters.add("Value");
			cPlayersMilitaryPopulation.commandParameters.add("PlayerNumber");
			cPlayersMilitaryPopulation.commandParameters.add("compareOp");
			cPlayersMilitaryPopulation.commandParameters.add("Value");
			cPlayersPopulation.commandParameters.add("PlayerNumber");
			cPlayersPopulation.commandParameters.add("compareOp");
			cPlayersPopulation.commandParameters.add("Value");
			cPlayersScore.commandParameters.add("PlayerNumber");
			cPlayersScore.commandParameters.add("compareOp");
			cPlayersScore.commandParameters.add("Value");
			cPlayersStance.commandParameters.add("PlayerNumber");
			cPlayersStance.commandParameters.add("PlayerStance");
			cPlayersTribute.commandParameters.add("PlayerNumber");
			cPlayersTribute.commandParameters.add("Resource");
			cPlayersTribute.commandParameters.add("compareOp");
			cPlayersTribute.commandParameters.add("Value");
			cPlayersTributeMemory.commandParameters.add("PlayerNumber");
			cPlayersTributeMemory.commandParameters.add("Resource");
			cPlayersTributeMemory.commandParameters.add("compareOp");
			cPlayersTributeMemory.commandParameters.add("Value");
			cPlayersUnitCount.commandParameters.add("PlayerNumber");
			cPlayersUnitCount.commandParameters.add("compareOp");
			cPlayersUnitCount.commandParameters.add("Value");
			cPlayersUnitTypeCount.commandParameters.add("PlayerNumber");
			cPlayersUnitTypeCount.commandParameters.add("UnitId");
			cPlayersUnitTypeCount.commandParameters.add("compareOp");
			cPlayersUnitTypeCount.commandParameters.add("Value");
			cPopulation.commandParameters.add("compareOp");
			cPopulation.commandParameters.add("Value");
			cPopulationCap.commandParameters.add("compareOp");
			cPopulationCap.commandParameters.add("Value");
			cPopulationHeadroom.commandParameters.add("compareOp");
			cPopulationHeadroom.commandParameters.add("Value");
			cRandomNumber.commandParameters.add("compareOp");
			cRandomNumber.commandParameters.add("Value");
			cReleaseEscrow.commandParameters.add("Resource");
			cResearch.commandParameters.add("TechId");
			cResearchAvailable.commandParameters.add("TechId");
			cResearchCompleted.commandParameters.add("TechId");
			cResourceFound.commandParameters.add("Resource");
			cSellCommodity.commandParameters.add("Commodity");
			cSetDifficultyParameter.commandParameters.add("DiffParameterId");
			cSetDifficultyParameter.commandParameters.add("Value");
			cSetDoctrine.commandParameters.add("Value");
			cSetEscrowPercentage.commandParameters.add("Resource");
			cSetEscrowPercentage.commandParameters.add("Value");
			cSetGoal.commandParameters.add("GoalId");
			cSetGoal.commandParameters.add("Value");
			cSetSharedGoal.commandParameters.add("SharedGoalId");
			cSetSharedGoal.commandParameters.add("Value");
			cSetSignal.commandParameters.add("SignalId");
			cSetStance.commandParameters.add("PlayerNumber");
			cSetStance.commandParameters.add("PlayerStance");
			cSetStrategicNumber.commandParameters.add("SnId");
			cSetStrategicNumber.commandParameters.add("Value");
			cSharedGoal.commandParameters.add("SharedGoalId");
			cSharedGoal.commandParameters.add("Value");
			cSoldierCount.commandParameters.add("compareOp");
			cSoldierCount.commandParameters.add("Value");
			cStanceToward.commandParameters.add("PlayerNumber");
			cStanceToward.commandParameters.add("PlayerStance");
			cStartingAge.commandParameters.add("compareOp");
			cStartingAge.commandParameters.add("Age");
			cStartingResources.commandParameters.add("compareOp");
			cStartingResources.commandParameters.add("StartingResources");
			cStoneAmount.commandParameters.add("compareOp");
			cStoneAmount.commandParameters.add("Value");
			cStrategicNumber.commandParameters.add("SnId");
			cStrategicNumber.commandParameters.add("compareOp");
			cStrategicNumber.commandParameters.add("Value");
			cTaunt.commandParameters.add("TauntId");
			cTauntDetected.commandParameters.add("PlayerNumber");
			cTauntDetected.commandParameters.add("TauntId");
			cTauntUsingRange.commandParameters.add("TauntId");
			cTauntUsingRange.commandParameters.add("Value");
			cTimerTriggered.commandParameters.add("TimerId");
			cTrain.commandParameters.add("UnitId");
			cTributeToPlayer.commandParameters.add("PlayerNumber");
			cTributeToPlayer.commandParameters.add("Resource");
			cTributeToPlayer.commandParameters.add("Value");
			cUnitAvailable.commandParameters.add("UnitId");
			cUnitCount.commandParameters.add("compareOp");
			cUnitCount.commandParameters.add("Value");
			cUnitCountTotal.commandParameters.add("compareOp");
			cUnitCountTotal.commandParameters.add("Value");
			cUnitTypeCount.commandParameters.add("UnitId");
			cUnitTypeCount.commandParameters.add("compareOp");
			cUnitTypeCount.commandParameters.add("Value");
			cUnitTypeCountTotal.commandParameters.add("UnitId");
			cUnitTypeCountTotal.commandParameters.add("compareOp");
			cUnitTypeCountTotal.commandParameters.add("Value");
			cVictoryCondition.commandParameters.add("VictoryCondition");
			cWallCompletedPercentage.commandParameters.add("Perimeter");
			cWallCompletedPercentage.commandParameters.add("compareOp");
			cWallCompletedPercentage.commandParameters.add("Value");
			cWallInvisiblePercentage.commandParameters.add("Perimeter");
			cWallInvisiblePercentage.commandParameters.add("compareOp");
			cWallInvisiblePercentage.commandParameters.add("Value");
			cWarboatCount.commandParameters.add("compareOp");
			cWarboatCount.commandParameters.add("Value");
			cWoodAmount.commandParameters.add("compareOp");
			cWoodAmount.commandParameters.add("Value");
			cUpAddCostData.commandParameters.add("GoalId");
			cUpAddCostData.commandParameters.add("typeOp");
			cUpAddCostData.commandParameters.add("Value");
			cUpAddObjectById.commandParameters.add("SearchSource");
			cUpAddObjectById.commandParameters.add("typeOp");
			cUpAddObjectById.commandParameters.add("Id");
			cUpAddObjectCost.commandParameters.add("typeOp");
			cUpAddObjectCost.commandParameters.add("ObjectId");
			cUpAddObjectCost.commandParameters.add("typeOp");
			cUpAddObjectCost.commandParameters.add("Value");
			cUpAddPoint.commandParameters.add("Point");
			cUpAddPoint.commandParameters.add("Point");
			cUpAddPoint.commandParameters.add("typeOp");
			cUpAddPoint.commandParameters.add("Value");
			cUpAddResearchCost.commandParameters.add("typeOp");
			cUpAddResearchCost.commandParameters.add("TechId");
			cUpAddResearchCost.commandParameters.add("typeOp");
			cUpAddResearchCost.commandParameters.add("Value");
			cUpAlliedGoal.commandParameters.add("PlayerNumber");
			cUpAlliedGoal.commandParameters.add("GoalId");
			cUpAlliedGoal.commandParameters.add("compareOp");
			cUpAlliedGoal.commandParameters.add("Value");
			cUpAlliedResourceAmount.commandParameters.add("PlayerNumber");
			cUpAlliedResourceAmount.commandParameters.add("ResourceType");
			cUpAlliedResourceAmount.commandParameters.add("compareOp");
			cUpAlliedResourceAmount.commandParameters.add("Value");
			cUpAlliedResourcePercent.commandParameters.add("PlayerNumber");
			cUpAlliedResourcePercent.commandParameters.add("ResourceType");
			cUpAlliedResourcePercent.commandParameters.add("compareOp");
			cUpAlliedResourcePercent.commandParameters.add("Value");
			cUpAlliedSn.commandParameters.add("PlayerNumber");
			cUpAlliedSn.commandParameters.add("SnId");
			cUpAlliedSn.commandParameters.add("compareOp");
			cUpAlliedSn.commandParameters.add("Value");
			cUpAssignBuilders.commandParameters.add("typeOp");
			cUpAssignBuilders.commandParameters.add("BuildingId");
			cUpAssignBuilders.commandParameters.add("typeOp");
			cUpAssignBuilders.commandParameters.add("Value");
			cUpAttackerClass.commandParameters.add("compareOp");
			cUpAttackerClass.commandParameters.add("ClassId");
			cUpBoundPoint.commandParameters.add("Point");
			cUpBoundPoint.commandParameters.add("Point");
			cUpBoundPrecisePoint.commandParameters.add("Point");
			cUpBoundPrecisePoint.commandParameters.add("Option");
			cUpBoundPrecisePoint.commandParameters.add("typeOp");
			cUpBoundPrecisePoint.commandParameters.add("Value");
			cUpBuild.commandParameters.add("PlacementType");
			cUpBuild.commandParameters.add("EscrowGoalId");
			cUpBuild.commandParameters.add("typeOp");
			cUpBuild.commandParameters.add("BuildingId");
			cUpBuildLine.commandParameters.add("Point");
			cUpBuildLine.commandParameters.add("Point");
			cUpBuildLine.commandParameters.add("typeOp");
			cUpBuildLine.commandParameters.add("BuildingId");
			cUpBuildingTypeInTown.commandParameters.add("typeOp");
			cUpBuildingTypeInTown.commandParameters.add("BuildingId");
			cUpBuildingTypeInTown.commandParameters.add("compareOp");
			cUpBuildingTypeInTown.commandParameters.add("Value");
			cUpBuyCommodity.commandParameters.add("typeOp");
			cUpBuyCommodity.commandParameters.add("ResourceType");
			cUpBuyCommodity.commandParameters.add("typeOp");
			cUpBuyCommodity.commandParameters.add("Value");
			cUpCanBuild.commandParameters.add("EscrowGoalId");
			cUpCanBuild.commandParameters.add("typeOp");
			cUpCanBuild.commandParameters.add("BuildingId");
			cUpCanBuildLine.commandParameters.add("EscrowGoalId");
			cUpCanBuildLine.commandParameters.add("Point");
			cUpCanBuildLine.commandParameters.add("typeOp");
			cUpCanBuildLine.commandParameters.add("BuildingId");
			cUpCanResearch.commandParameters.add("EscrowGoalId");
			cUpCanResearch.commandParameters.add("typeOp");
			cUpCanResearch.commandParameters.add("TechId");
			cUpCanSearch.commandParameters.add("SearchSource");
			cUpCanTrain.commandParameters.add("EscrowGoalId");
			cUpCanTrain.commandParameters.add("typeOp");
			cUpCanTrain.commandParameters.add("UnitId");
			cUpCcAddResource.commandParameters.add("typeOp");
			cUpCcAddResource.commandParameters.add("ResourceType");
			cUpCcAddResource.commandParameters.add("typeOp");
			cUpCcAddResource.commandParameters.add("Value");
			cUpCcSendCheat.commandParameters.add("String");
			cUpChangeName.commandParameters.add("String");
			cUpChatDataToAll.commandParameters.add("String");
			cUpChatDataToAll.commandParameters.add("typeOp");
			cUpChatDataToAll.commandParameters.add("Value");
			cUpChatDataToPlayer.commandParameters.add("PlayerNumber");
			cUpChatDataToPlayer.commandParameters.add("String");
			cUpChatDataToPlayer.commandParameters.add("typeOp");
			cUpChatDataToPlayer.commandParameters.add("Value");
			cUpChatDataToSelf.commandParameters.add("String");
			cUpChatDataToSelf.commandParameters.add("typeOp");
			cUpChatDataToSelf.commandParameters.add("Value");
			cUpCleanSearch.commandParameters.add("SearchSource");
			cUpCleanSearch.commandParameters.add("ObjectData");
			cUpCleanSearch.commandParameters.add("SearchOrder");
			cUpCompareConst.commandParameters.add("Defconst");
			cUpCompareConst.commandParameters.add("compareOp");
			cUpCompareConst.commandParameters.add("Value");
			cUpCompareFlag.commandParameters.add("GoalId");
			cUpCompareFlag.commandParameters.add("compareOp");
			cUpCompareFlag.commandParameters.add("Flag");
			cUpCompareGoal.commandParameters.add("GoalId");
			cUpCompareGoal.commandParameters.add("compareOp");
			cUpCompareGoal.commandParameters.add("Value");
			cUpCompareSn.commandParameters.add("GoalId");
			cUpCompareSn.commandParameters.add("compareOp");
			cUpCompareSn.commandParameters.add("Value");
			cUpCompareText.commandParameters.add("typeOp");
			cUpCompareText.commandParameters.add("Defconst");
			cUpCompareText.commandParameters.add("compareOp");
			cUpCompareText.commandParameters.add("Value");
			cUpCopyPoint.commandParameters.add("Point");
			cUpCopyPoint.commandParameters.add("Point");
			cUpCreateGroup.commandParameters.add("GoalId");
			cUpCreateGroup.commandParameters.add("GoalId");
			cUpCreateGroup.commandParameters.add("typeOp");
			cUpCreateGroup.commandParameters.add("GroupId");
			cUpCrossTiles.commandParameters.add("Point");
			cUpCrossTiles.commandParameters.add("Point");
			cUpCrossTiles.commandParameters.add("typeOp");
			cUpCrossTiles.commandParameters.add("Value");
			cUpDefenderCount.commandParameters.add("compareOp");
			cUpDefenderCount.commandParameters.add("Value");
			cUpDeleteDistantFarms.commandParameters.add("typeOp");
			cUpDeleteDistantFarms.commandParameters.add("Value");
			cUpDeleteIdleUnits.commandParameters.add("IdleType");
			cUpDeleteObjects.commandParameters.add("typeOp");
			cUpDeleteObjects.commandParameters.add("UnitId");
			cUpDeleteObjects.commandParameters.add("typeOp");
			cUpDeleteObjects.commandParameters.add("Value");
			cUpDisbandGroupType.commandParameters.add("GroupType");
			cUpDropResources.commandParameters.add("Resource");
			cUpDropResources.commandParameters.add("typeOp");
			cUpDropResources.commandParameters.add("Value");
			cUpEnemyBuildingsInTown.commandParameters.add("compareOp");
			cUpEnemyBuildingsInTown.commandParameters.add("Value");
			cUpEnemyUnitsInTown.commandParameters.add("compareOp");
			cUpEnemyUnitsInTown.commandParameters.add("Value");
			cUpEnemyVillagersInTown.commandParameters.add("compareOp");
			cUpEnemyVillagersInTown.commandParameters.add("Value");
			cUpFilterDistance.commandParameters.add("typeOp");
			cUpFilterDistance.commandParameters.add("MinDistance");
			cUpFilterDistance.commandParameters.add("typeOp");
			cUpFilterDistance.commandParameters.add("MaxDistance");
			cUpFilterExclude.commandParameters.add("CmdId");
			cUpFilterExclude.commandParameters.add("ActionId");
			cUpFilterExclude.commandParameters.add("OrderId");
			cUpFilterExclude.commandParameters.add("ClassId");
			cUpFilterGarrison.commandParameters.add("typeOp");
			cUpFilterGarrison.commandParameters.add("MinGarrison");
			cUpFilterGarrison.commandParameters.add("typeOp");
			cUpFilterGarrison.commandParameters.add("MaxGarrison");
			cUpFilterInclude.commandParameters.add("CmdId");
			cUpFilterInclude.commandParameters.add("ActionId");
			cUpFilterInclude.commandParameters.add("OrderId");
			cUpFilterInclude.commandParameters.add("OnMainland");
			cUpFilterRange.commandParameters.add("MinGarrison");
			cUpFilterRange.commandParameters.add("MaxGarrison");
			cUpFilterRange.commandParameters.add("MinDistance");
			cUpFilterRange.commandParameters.add("MaxDistance");
			cUpFilterStatus.commandParameters.add("typeOp");
			cUpFilterStatus.commandParameters.add("ObjectStatus");
			cUpFilterStatus.commandParameters.add("typeOp");
			cUpFilterStatus.commandParameters.add("ObjectList");
			cUpFindFlare.commandParameters.add("Point");
			cUpFindLocal.commandParameters.add("typeOp");
			cUpFindLocal.commandParameters.add("UnitId");
			cUpFindLocal.commandParameters.add("typeOp");
			cUpFindLocal.commandParameters.add("Value");
			cUpFindNextPlayer.commandParameters.add("PlayerStance");
			cUpFindNextPlayer.commandParameters.add("FindPlayerMethod");
			cUpFindNextPlayer.commandParameters.add("OutputGoalId");
			cUpFindPlayer.commandParameters.add("PlayerStance");
			cUpFindPlayer.commandParameters.add("FindPlayerMethod");
			cUpFindPlayer.commandParameters.add("OutputGoalId");
			cUpFindPlayerFlare.commandParameters.add("PlayerNumber");
			cUpFindPlayerFlare.commandParameters.add("Point");
			cUpFindRemote.commandParameters.add("typeOp");
			cUpFindRemote.commandParameters.add("UnitId");
			cUpFindRemote.commandParameters.add("typeOp");
			cUpFindRemote.commandParameters.add("Value");
			cUpFindResource.commandParameters.add("typeOp");
			cUpFindResource.commandParameters.add("Resource");
			cUpFindResource.commandParameters.add("typeOp");
			cUpFindResource.commandParameters.add("Value");
			cUpFindStatusLocal.commandParameters.add("typeOp");
			cUpFindStatusLocal.commandParameters.add("UnitId");
			cUpFindStatusLocal.commandParameters.add("typeOp");
			cUpFindStatusLocal.commandParameters.add("Value");
			cUpFindStatusRemote.commandParameters.add("typeOp");
			cUpFindStatusRemote.commandParameters.add("UnitId");
			cUpFindStatusRemote.commandParameters.add("typeOp");
			cUpFindStatusRemote.commandParameters.add("Value");
			cUpGaiaTypeCount.commandParameters.add("typeOp");
			cUpGaiaTypeCount.commandParameters.add("Resource");
			cUpGaiaTypeCount.commandParameters.add("compareOp");
			cUpGaiaTypeCount.commandParameters.add("Value");
			cUpGaiaTypeCountTotal.commandParameters.add("typeOp");
			cUpGaiaTypeCountTotal.commandParameters.add("Resource");
			cUpGaiaTypeCountTotal.commandParameters.add("compareOp");
			cUpGaiaTypeCountTotal.commandParameters.add("Value");
			cUpGarrison.commandParameters.add("ObjectId");
			cUpGarrison.commandParameters.add("typeOp");
			cUpGarrison.commandParameters.add("UnitId");
			cUpGatherInside.commandParameters.add("typeOp");
			cUpGatherInside.commandParameters.add("BuildingId");
			cUpGatherInside.commandParameters.add("typeOp");
			cUpGatherInside.commandParameters.add("Option");
			cUpGetAttackerClass.commandParameters.add("ThreatSource");
			cUpGetCostDelta.commandParameters.add("OutputGoalId");
			cUpGetEvent.commandParameters.add("typeOp");
			cUpGetEvent.commandParameters.add("EventId");
			cUpGetEvent.commandParameters.add("Value");
			cUpGetFact.commandParameters.add("FactId");
			cUpGetFact.commandParameters.add("FactParameter");
			cUpGetFact.commandParameters.add("OutputGoalId");
			cUpGetFactMax.commandParameters.add("PlayerNumber");
			cUpGetFactMax.commandParameters.add("FactId");
			cUpGetFactMax.commandParameters.add("FactParameter");
			cUpGetFactMax.commandParameters.add("OutputGoalId");
			cUpGetFactMin.commandParameters.add("PlayerNumber");
			cUpGetFactMin.commandParameters.add("FactId");
			cUpGetFactMin.commandParameters.add("FactParameter");
			cUpGetFactMin.commandParameters.add("OutputGoalId");
			cUpGetFactSum.commandParameters.add("PlayerNumber");
			cUpGetFactSum.commandParameters.add("FactId");
			cUpGetFactSum.commandParameters.add("FactParameter");
			cUpGetFactSum.commandParameters.add("OutputGoalId");
			cUpGetFocusFact.commandParameters.add("FactId");
			cUpGetFocusFact.commandParameters.add("FactParameter");
			cUpGetFocusFact.commandParameters.add("OutputGoalId");
			cUpGetGroupSize.commandParameters.add("typeOp");
			cUpGetGroupSize.commandParameters.add("GroupId");
			cUpGetGroupSize.commandParameters.add("OutputGoalId");
			cUpGetGuardState.commandParameters.add("OutputGoalId");
			cUpGetIndirectGoal.commandParameters.add("typeOp");
			cUpGetIndirectGoal.commandParameters.add("GoalId");
			cUpGetIndirectGoal.commandParameters.add("OutputGoalId");
			cUpGetObjectData.commandParameters.add("ObjectData");
			cUpGetObjectData.commandParameters.add("OutputGoalId");
			cUpGetObjectTargetData.commandParameters.add("ObjectData");
			cUpGetObjectTargetData.commandParameters.add("OutputGoalId");
			cUpGetObjectTypeData.commandParameters.add("typeOp");
			cUpGetObjectTypeData.commandParameters.add("TypeId");
			cUpGetObjectTypeData.commandParameters.add("ObjectData");
			cUpGetObjectTypeData.commandParameters.add("OutputGoalId");
			cUpGetPathDistance.commandParameters.add("Point");
			cUpGetPathDistance.commandParameters.add("Option");
			cUpGetPathDistance.commandParameters.add("OutputGoalId");
			cUpGetPlayerColor.commandParameters.add("PlayerNumber");
			cUpGetPlayerColor.commandParameters.add("ColorId");
			cUpGetPlayerFact.commandParameters.add("PlayerNumber");
			cUpGetPlayerFact.commandParameters.add("FactId");
			cUpGetPlayerFact.commandParameters.add("FactParameter");
			cUpGetPlayerFact.commandParameters.add("OutputGoalId");
			cUpGetPoint.commandParameters.add("PositionType");
			cUpGetPoint.commandParameters.add("Point");
			cUpGetPointContains.commandParameters.add("Point");
			cUpGetPointContains.commandParameters.add("OutputGoalId");
			cUpGetPointContains.commandParameters.add("typeOp");
			cUpGetPointContains.commandParameters.add("ObjectId");
			cUpGetPointDistance.commandParameters.add("Point");
			cUpGetPointDistance.commandParameters.add("Point");
			cUpGetPointDistance.commandParameters.add("OutputGoalId");
			cUpGetPointElevation.commandParameters.add("Point");
			cUpGetPointElevation.commandParameters.add("OutputGoalId");
			cUpGetPointTerrain.commandParameters.add("Point");
			cUpGetPointTerrain.commandParameters.add("Terrain");
			cUpGetPointZone.commandParameters.add("Point");
			cUpGetPointZone.commandParameters.add("OutputGoalId");
			cUpGetPreciseTime.commandParameters.add("OptionGoalId");
			cUpGetPreciseTime.commandParameters.add("OutputGoalId");
			cUpGetProjectilePlayer.commandParameters.add("ProjectileType");
			cUpGetProjectilePlayer.commandParameters.add("OutputGoalId");
			cUpGetRuleId.commandParameters.add("GoalId");
			cUpGetSearchState.commandParameters.add("OutputGoalId");
			cUpGetSharedGoal.commandParameters.add("typeOp");
			cUpGetSharedGoal.commandParameters.add("SharedGoalId");
			cUpGetSharedGoal.commandParameters.add("Value");
			cUpGetSignal.commandParameters.add("typeOp");
			cUpGetSignal.commandParameters.add("SignalId");
			cUpGetSignal.commandParameters.add("Value");
			cUpGetTargetFact.commandParameters.add("FactId");
			cUpGetTargetFact.commandParameters.add("FactParameter");
			cUpGetTargetFact.commandParameters.add("OutputGoalId");
			cUpGetThreatData.commandParameters.add("ThreatTime");
			cUpGetThreatData.commandParameters.add("ThreatPlayer");
			cUpGetThreatData.commandParameters.add("ThreatSource");
			cUpGetThreatData.commandParameters.add("ThreatTarget");
			cUpGetTimer.commandParameters.add("typeOp");
			cUpGetTimer.commandParameters.add("TimerId");
			cUpGetTimer.commandParameters.add("OutputGoalId");
			cUpGetTreatyData.commandParameters.add("OutputGoalId");
			cUpGetUpgradeId.commandParameters.add("PlayerNumber");
			cUpGetUpgradeId.commandParameters.add("Option");
			cUpGetUpgradeId.commandParameters.add("GoalId");
			cUpGetUpgradeId.commandParameters.add("OutputGoalId");
			cUpGetVictoryData.commandParameters.add("VictoryPlayer");
			cUpGetVictoryData.commandParameters.add("VictoryType");
			cUpGetVictoryData.commandParameters.add("VictoryTime");
			cUpGetVictoryLimit.commandParameters.add("OutputGoalId");
			cUpGroupSize.commandParameters.add("typeOp");
			cUpGroupSize.commandParameters.add("GroupId");
			cUpGroupSize.commandParameters.add("compareOp");
			cUpGroupSize.commandParameters.add("Value");
			cUpGuardUnit.commandParameters.add("ObjectId");
			cUpGuardUnit.commandParameters.add("typeOp");
			cUpGuardUnit.commandParameters.add("UnitId");
			cUpIdleUnitCount.commandParameters.add("IdleType");
			cUpIdleUnitCount.commandParameters.add("compareOp");
			cUpIdleUnitCount.commandParameters.add("Value");
			cUpJumpDirect.commandParameters.add("typeOp");
			cUpJumpDirect.commandParameters.add("RuleId");
			cUpJumpDynamic.commandParameters.add("typeOp");
			cUpJumpDynamic.commandParameters.add("RuleDelta");
			cUpJumpRule.commandParameters.add("RuleDelta");
			cUpLerpPercent.commandParameters.add("Point");
			cUpLerpPercent.commandParameters.add("Point");
			cUpLerpPercent.commandParameters.add("typeOp");
			cUpLerpPercent.commandParameters.add("Percent");
			cUpLerpTiles.commandParameters.add("Point");
			cUpLerpTiles.commandParameters.add("Point");
			cUpLerpTiles.commandParameters.add("typeOp");
			cUpLerpTiles.commandParameters.add("Value");
			cUpLogData.commandParameters.add("Option");
			cUpLogData.commandParameters.add("String");
			cUpLogData.commandParameters.add("typeOp");
			cUpLogData.commandParameters.add("Value");
			cUpModifyEscrow.commandParameters.add("Resource");
			cUpModifyEscrow.commandParameters.add("mathOp");
			cUpModifyEscrow.commandParameters.add("Value");
			cUpModifyFlag.commandParameters.add("GoalId");
			cUpModifyFlag.commandParameters.add("mathOp");
			cUpModifyFlag.commandParameters.add("Flag");
			cUpModifyGoal.commandParameters.add("GoalId");
			cUpModifyGoal.commandParameters.add("mathOp");
			cUpModifyGoal.commandParameters.add("Value");
			cUpModifyGroupFlag.commandParameters.add("Option");
			cUpModifyGroupFlag.commandParameters.add("typeOp");
			cUpModifyGroupFlag.commandParameters.add("GroupId");
			cUpModifySn.commandParameters.add("SnId");
			cUpModifySn.commandParameters.add("mathOp");
			cUpModifySn.commandParameters.add("Value");
			cUpObjectData.commandParameters.add("ObjectData");
			cUpObjectData.commandParameters.add("compareOp");
			cUpObjectData.commandParameters.add("Value");
			cUpObjectTargetData.commandParameters.add("ObjectData");
			cUpObjectTargetData.commandParameters.add("compareOp");
			cUpObjectTargetData.commandParameters.add("Value");
			cUpObjectTypeCount.commandParameters.add("typeOp");
			cUpObjectTypeCount.commandParameters.add("ObjectId");
			cUpObjectTypeCount.commandParameters.add("compareOp");
			cUpObjectTypeCount.commandParameters.add("Value");
			cUpObjectTypeCountTotal.commandParameters.add("typeOp");
			cUpObjectTypeCountTotal.commandParameters.add("ObjectId");
			cUpObjectTypeCountTotal.commandParameters.add("compareOp");
			cUpObjectTypeCountTotal.commandParameters.add("Value");
			cUpPathDistance.commandParameters.add("Point");
			cUpPathDistance.commandParameters.add("Option");
			cUpPathDistance.commandParameters.add("compareOp");
			cUpPathDistance.commandParameters.add("Value");
			cUpPendingObjects.commandParameters.add("typeOp");
			cUpPendingObjects.commandParameters.add("ObjectId");
			cUpPendingObjects.commandParameters.add("compareOp");
			cUpPendingObjects.commandParameters.add("Value");
			cUpPendingPlacement.commandParameters.add("typeOp");
			cUpPendingPlacement.commandParameters.add("BuildingId");
			cUpPlayerDistance.commandParameters.add("PlayerNumber");
			cUpPlayerDistance.commandParameters.add("compareOp");
			cUpPlayerDistance.commandParameters.add("Value");
			cUpPlayersInGame.commandParameters.add("PlayerStance");
			cUpPlayersInGame.commandParameters.add("compareOp");
			cUpPlayersInGame.commandParameters.add("Value");
			cUpPointContains.commandParameters.add("Point");
			cUpPointContains.commandParameters.add("typeOp");
			cUpPointContains.commandParameters.add("ObjectId");
			cUpPointDistance.commandParameters.add("Point");
			cUpPointDistance.commandParameters.add("Point");
			cUpPointDistance.commandParameters.add("compareOp");
			cUpPointDistance.commandParameters.add("Value");
			cUpPointElevation.commandParameters.add("Point");
			cUpPointElevation.commandParameters.add("compareOp");
			cUpPointElevation.commandParameters.add("Value");
			cUpPointExplored.commandParameters.add("Point");
			cUpPointExplored.commandParameters.add("compareOp");
			cUpPointExplored.commandParameters.add("ExploredState");
			cUpPointTerrain.commandParameters.add("Point");
			cUpPointTerrain.commandParameters.add("compareOp");
			cUpPointTerrain.commandParameters.add("Terrain");
			cUpPointZone.commandParameters.add("Point");
			cUpPointZone.commandParameters.add("compareOp");
			cUpPointZone.commandParameters.add("Value");
			cUpProjectileDetected.commandParameters.add("ProjectileType");
			cUpProjectileDetected.commandParameters.add("compareOp");
			cUpProjectileDetected.commandParameters.add("Value");
			cUpProjectileTarget.commandParameters.add("ProjectileType");
			cUpProjectileTarget.commandParameters.add("compareOp");
			cUpProjectileTarget.commandParameters.add("ClassId");
			cUpRemainingBoarAmount.commandParameters.add("compareOp");
			cUpRemainingBoarAmount.commandParameters.add("Value");
			cUpRemoveObjects.commandParameters.add("SearchSource");
			cUpRemoveObjects.commandParameters.add("ObjectData");
			cUpRemoveObjects.commandParameters.add("compareOp");
			cUpRemoveObjects.commandParameters.add("Value");
			cUpRequestHunters.commandParameters.add("typeOp");
			cUpRequestHunters.commandParameters.add("Value");
			cUpResearch.commandParameters.add("EscrowGoalId");
			cUpResearch.commandParameters.add("typeOp");
			cUpResearch.commandParameters.add("TechId");
			cUpResearchStatus.commandParameters.add("typeOp");
			cUpResearchStatus.commandParameters.add("TechId");
			cUpResearchStatus.commandParameters.add("compareOp");
			cUpResearchStatus.commandParameters.add("ResearchState");
			cUpResetBuilding.commandParameters.add("Option");
			cUpResetBuilding.commandParameters.add("typeOp");
			cUpResetBuilding.commandParameters.add("BuildingId");
			cUpResetCostData.commandParameters.add("GoalId");
			cUpResetGroup.commandParameters.add("typeOp");
			cUpResetGroup.commandParameters.add("GroupId");
			cUpResetPlacement.commandParameters.add("typeOp");
			cUpResetPlacement.commandParameters.add("BuildingId");
			cUpResetSearch.commandParameters.add("LocalIndex");
			cUpResetSearch.commandParameters.add("LocalList");
			cUpResetSearch.commandParameters.add("RemoteIndex");
			cUpResetSearch.commandParameters.add("RemoteList");
			cUpResetTargetPriorities.commandParameters.add("PriorityType");
			cUpResetTargetPriorities.commandParameters.add("Option");
			cUpResetUnit.commandParameters.add("typeOp");
			cUpResetUnit.commandParameters.add("UnitId");
			cUpResourceAmount.commandParameters.add("ResourceType");
			cUpResourceAmount.commandParameters.add("compareOp");
			cUpResourceAmount.commandParameters.add("Value");
			cUpResourcePercent.commandParameters.add("ResourceType");
			cUpResourcePercent.commandParameters.add("compareOp");
			cUpResourcePercent.commandParameters.add("Value");
			cUpRetaskGatherers.commandParameters.add("Resource");
			cUpRetaskGatherers.commandParameters.add("typeOp");
			cUpRetaskGatherers.commandParameters.add("Value");
			cUpRetreatTo.commandParameters.add("ObjectId");
			cUpRetreatTo.commandParameters.add("typeOp");
			cUpRetreatTo.commandParameters.add("UnitId");
			cUpSellCommodity.commandParameters.add("typeOp");
			cUpSellCommodity.commandParameters.add("ResourceType");
			cUpSellCommodity.commandParameters.add("typeOp");
			cUpSellCommodity.commandParameters.add("Value");
			cUpSendFlare.commandParameters.add("Point");
			cUpSendScout.commandParameters.add("GroupType");
			cUpSendScout.commandParameters.add("ScoutMethod");
			cUpSetAttackStance.commandParameters.add("UnitId");
			cUpSetAttackStance.commandParameters.add("typeOp");
			cUpSetAttackStance.commandParameters.add("AttackStance");
			cUpSetDefensePriority.commandParameters.add("typeOp");
			cUpSetDefensePriority.commandParameters.add("BuildingId");
			cUpSetDefensePriority.commandParameters.add("typeOp");
			cUpSetDefensePriority.commandParameters.add("Value");
			cUpSetEvent.commandParameters.add("typeOp");
			cUpSetEvent.commandParameters.add("EventId");
			cUpSetEvent.commandParameters.add("typeOp");
			cUpSetEvent.commandParameters.add("Value");
			cUpSetGroup.commandParameters.add("SearchSource");
			cUpSetGroup.commandParameters.add("typeOp");
			cUpSetGroup.commandParameters.add("GroupId");
			cUpSetIndirectGoal.commandParameters.add("typeOp");
			cUpSetIndirectGoal.commandParameters.add("GoalId");
			cUpSetIndirectGoal.commandParameters.add("typeOp");
			cUpSetIndirectGoal.commandParameters.add("Value");
			cUpSetOffensePriority.commandParameters.add("typeOp");
			cUpSetOffensePriority.commandParameters.add("ObjectId");
			cUpSetOffensePriority.commandParameters.add("typeOp");
			cUpSetOffensePriority.commandParameters.add("Value");
			cUpSetPlacementData.commandParameters.add("PlayerNumber");
			cUpSetPlacementData.commandParameters.add("ObjectId");
			cUpSetPlacementData.commandParameters.add("typeOp");
			cUpSetPlacementData.commandParameters.add("Value");
			cUpSetPreciseTargetPoint.commandParameters.add("Point");
			cUpSetSharedGoal.commandParameters.add("typeOp");
			cUpSetSharedGoal.commandParameters.add("SharedGoalId");
			cUpSetSharedGoal.commandParameters.add("typeOp");
			cUpSetSharedGoal.commandParameters.add("Value");
			cUpSetSignal.commandParameters.add("typeOp");
			cUpSetSignal.commandParameters.add("SignalId");
			cUpSetSignal.commandParameters.add("typeOp");
			cUpSetSignal.commandParameters.add("Value");
			cUpSetTargetById.commandParameters.add("typeOp");
			cUpSetTargetById.commandParameters.add("Id");
			cUpSetTargetObject.commandParameters.add("SearchSource");
			cUpSetTargetObject.commandParameters.add("typeOp");
			cUpSetTargetObject.commandParameters.add("Index");
			cUpSetTargetPoint.commandParameters.add("Point");
			cUpSetTimer.commandParameters.add("typeOp");
			cUpSetTimer.commandParameters.add("TimerId");
			cUpSetTimer.commandParameters.add("typeOp");
			cUpSetTimer.commandParameters.add("Value");
			cUpSetupCostData.commandParameters.add("Option");
			cUpSetupCostData.commandParameters.add("GoalId");
			cUpStoreMapName.commandParameters.add("Option");
			cUpStorePlayerChat.commandParameters.add("PlayerNumber");
			cUpStorePlayerName.commandParameters.add("PlayerNumber");
			cUpStoreTechName.commandParameters.add("typeOp");
			cUpStoreTechName.commandParameters.add("TechId");
			cUpStoreText.commandParameters.add("typeOp");
			cUpStoreText.commandParameters.add("LanguageId");
			cUpStoreTypeName.commandParameters.add("typeOp");
			cUpStoreTypeName.commandParameters.add("TypeId");
			cUpTargetObjects.commandParameters.add("Option");
			cUpTargetObjects.commandParameters.add("DUCAction");
			cUpTargetObjects.commandParameters.add("Formation");
			cUpTargetObjects.commandParameters.add("AttackStance");
			cUpTargetPoint.commandParameters.add("Point");
			cUpTargetPoint.commandParameters.add("DUCAction");
			cUpTargetPoint.commandParameters.add("Formation");
			cUpTargetPoint.commandParameters.add("AttackStance");
			cUpTimerStatus.commandParameters.add("TimerId");
			cUpTimerStatus.commandParameters.add("compareOp");
			cUpTimerStatus.commandParameters.add("TimerState");
			cUpTrain.commandParameters.add("EscrowGoalId");
			cUpTrain.commandParameters.add("typeOp");
			cUpTrain.commandParameters.add("UnitId");
			cUpTrainSiteReady.commandParameters.add("typeOp");
			cUpTrainSiteReady.commandParameters.add("UnitId");
			cUpTributeToPlayer.commandParameters.add("PlayerNumber");
			cUpTributeToPlayer.commandParameters.add("ResourceType");
			cUpTributeToPlayer.commandParameters.add("typeOp");
			cUpTributeToPlayer.commandParameters.add("Value");
			cUpUngarrison.commandParameters.add("typeOp");
			cUpUngarrison.commandParameters.add("ObjectId");
			cUpUnitTypeInTown.commandParameters.add("typeOp");
			cUpUnitTypeInTown.commandParameters.add("UnitId");
			cUpUnitTypeInTown.commandParameters.add("compareOp");
			cUpUnitTypeInTown.commandParameters.add("Value");
			cUpVillagerTypeInTown.commandParameters.add("typeOp");
			cUpVillagerTypeInTown.commandParameters.add("UnitId");
			cUpVillagerTypeInTown.commandParameters.add("compareOp");
			cUpVillagerTypeInTown.commandParameters.add("Value");
			cFeBreakPoint.commandParameters.add("Value");
			cFeBreakPoint.commandParameters.add("compareOp");
			cFeBreakPoint.commandParameters.add("Value");
			cFeBreakPoint.commandParameters.add("OptionGoalId");
			cFeCcEffectAmount.commandParameters.add("EffectId");
			cFeCcEffectAmount.commandParameters.add("ItemId");
			cFeCcEffectAmount.commandParameters.add("AttrId");
			cFeCcEffectAmount.commandParameters.add("Value");
			cFeCcEffectPercent.commandParameters.add("EffectId");
			cFeCcEffectPercent.commandParameters.add("ItemId");
			cFeCcEffectPercent.commandParameters.add("AttrId");
			cFeCcEffectPercent.commandParameters.add("Percent");
			cFeFilterGarrisoned.commandParameters.add("typeOp");
			cFeFilterGarrisoned.commandParameters.add("Option");
			cFeSubGameType.commandParameters.add("compareOp");
			cFeSubGameType.commandParameters.add("SubGameType");
			cXsScriptCall.commandParameters.add("String");

			cUpFindNextPlayer.returnType = TokenType.NUMBER_INTEGER;
			cUpFindPlayer.returnType = TokenType.NUMBER_INTEGER;
			cUpGetCostDelta.returnType = TokenType.NUMBER_INTEGER;
			cUpGetFact.returnType = TokenType.NUMBER_INTEGER;
			cUpGetFactMax.returnType = TokenType.NUMBER_INTEGER;
			cUpGetFactMin.returnType = TokenType.NUMBER_INTEGER;
			cUpGetFactSum.returnType = TokenType.NUMBER_INTEGER;
			cUpGetFocusFact.returnType = TokenType.NUMBER_INTEGER;
			cUpGetGroupSize.returnType = TokenType.NUMBER_INTEGER;
			cUpGetGuardState.returnType = TokenType.NUMBER_INTEGER;
			cUpGetIndirectGoal.returnType = TokenType.NUMBER_INTEGER;
			cUpGetObjectData.returnType = TokenType.NUMBER_INTEGER;
			cUpGetObjectTargetData.returnType = TokenType.NUMBER_INTEGER;
			cUpGetObjectTypeData.returnType = TokenType.NUMBER_INTEGER;
			cUpGetPathDistance.returnType = TokenType.NUMBER_INTEGER;
			cUpGetPlayerFact.returnType = TokenType.NUMBER_INTEGER;
			cUpGetPointContains.returnType = TokenType.NUMBER_INTEGER;
			cUpGetPointDistance.returnType = TokenType.NUMBER_INTEGER;
			cUpGetPointElevation.returnType = TokenType.NUMBER_INTEGER;
			cUpGetPointZone.returnType = TokenType.NUMBER_INTEGER;
			cUpGetPreciseTime.returnType = TokenType.NUMBER_INTEGER;
			cUpGetProjectilePlayer.returnType = TokenType.NUMBER_INTEGER;
			cUpGetSearchState.returnType = TokenType.NUMBER_INTEGER;
			cUpGetTargetFact.returnType = TokenType.NUMBER_INTEGER;
			cUpGetTimer.returnType = TokenType.NUMBER_INTEGER;
			cUpGetTreatyData.returnType = TokenType.NUMBER_INTEGER;
			cUpGetUpgradeId.returnType = TokenType.NUMBER_INTEGER;
			cUpGetVictoryLimit.returnType = TokenType.NUMBER_INTEGER;
			cUpGetPlayerColor.returnType = TokenType.NUMBER_INTEGER;

			cUpBoundPoint.returnType = TokenType.POINT_OBJECT;
			cUpBoundPrecisePoint.returnType = TokenType.POINT_OBJECT;
			cUpCrossTiles.returnType = TokenType.POINT_OBJECT;
			cUpFindFlare.returnType = TokenType.POINT_OBJECT;
			cUpFindPlayerFlare.returnType = TokenType.POINT_OBJECT;
			cUpGetPoint.returnType = TokenType.POINT_OBJECT;
			cUpLerpPercent.returnType = TokenType.POINT_OBJECT;
			cUpLerpTiles.returnType = TokenType.POINT_OBJECT;

			cUpBoundPoint.commandParameters.clear();
			cUpFindFlare.commandParameters.clear();
			cUpFindPlayerFlare.commandParameters.clear();
			cUpGetPoint.commandParameters.clear();
			cUpBoundPoint.commandParameters.add("Point");
			cUpFindPlayerFlare.commandParameters.add("PlayerNumber");
			cUpGetPoint.commandParameters.add("PositionType");

			cUpGetAttackerClass.returnType = TokenType.NUMBER_INTEGER;
			alreadyFilled = true;
		}

	}

	public CommandPer getCommandOfNanem(String name) {
		for (CommandPer command : commandsArray) {
			if (command.commandName.equals(name)) {
				return command;
			}
		}
		return null;
	}
	
	public boolean isACommandName(String s) {
		for (CommandPer command : commandsArray) {
			if (s.equals(command.commandName)) {
				return true;
			}
		}
		return false;
	}

}
