package com.fategrinder.barracks;

public class DefaultConstants {

	// Default string constant
    private static final String DEFAULT_CONSTANT = ";--------------------------------------\n"
    		+ "; Define FactId Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst game-time 0)\n"
    		+ "(defconst population-cap 1)\n"
    		+ "(defconst population-headroom 2)\n"
    		+ "(defconst housing-headroom 3)\n"
    		+ "(defconst idle-farm-count 4)\n"
    		+ "(defconst food-amount 5)\n"
    		+ "(defconst wood-amount 6)\n"
    		+ "(defconst stone-amount 7)\n"
    		+ "(defconst gold-amount 8)\n"
    		+ "(defconst escrow-amount 9)\n"
    		+ "(defconst commodity-buying-price 10)\n"
    		+ "(defconst commodity-selling-price 11)\n"
    		+ "(defconst dropsite-min-distance 12)\n"
    		+ "(defconst soldier-count 13)\n"
    		+ "(defconst attack-soldier-count 14)\n"
    		+ "(defconst defend-soldier-count 15)\n"
    		+ "(defconst warboat-count 16)\n"
    		+ "(defconst attack-warboat-count 17)\n"
    		+ "(defconst defend-warboat-count 18)\n"
    		+ "(defconst current-age 19)					;any\n"
    		+ "(defconst current-score 20)					;any\n"
    		+ "(defconst civilization 21)					;any\n"
    		+ "(defconst player-number 22)					;any\n"
    		+ "(defconst player-in-game 23)				;any\n"
    		+ "(defconst unit-count 24)					;any\n"
    		+ "(defconst unit-type-count 25)				;any\n"
    		+ "(defconst unit-type-count-total 26)\n"
    		+ "(defconst building-count 27)				;any\n"
    		+ "(defconst building-type-count 28)			;any\n"
    		+ "(defconst building-type-count-total 29)\n"
    		+ "(defconst population 30)					;any\n"
    		+ "(defconst military-population 31)			;any\n"
    		+ "(defconst civilian-population 32)			;any\n"
    		+ "(defconst random-number 33)\n"
    		+ "(defconst resource-amount 34)				;any\n"
    		+ "(defconst player-distance 35)				;any\n"
    		+ "(defconst allied-goal 36)					;any\n"
    		+ "(defconst allied-sn 37)						;any\n"
    		+ "(defconst resource-percent 38)				;any\n"
    		+ "(defconst enemy-buildings-in-town 39)\n"
    		+ "(defconst enemy-units-in-town 40)\n"
    		+ "(defconst enemy-villagers-in-town 41)\n"
    		+ "(defconst players-in-game 42)\n"
    		+ "(defconst defender-count 43)\n"
    		+ "(defconst building-type-in-town 44)\n"
    		+ "(defconst unit-type-in-town 45)\n"
    		+ "(defconst villager-type-in-town 46)\n"
    		+ "(defconst gaia-type-count 47)\n"
    		+ "(defconst gaia-type-count-total 48)\n"
    		+ "(defconst cc-gaia-type-count 49)\n"
    		+ "(defconst current-age-time 50)				;any\n"
    		+ "(defconst timer-status 51)\n"
    		+ "(defconst players-tribute 52)				;any\n"
    		+ "(defconst players-tribute-memory 53)			;any\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ObjectId Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst flare 274)\n"
    		+ "(defconst villager-class 904)\n"
    		+ "(defconst building-class 903)\n"
    		+ "(defconst ocean-fish-class 905)\n"
    		+ "(defconst shore-fish-class 933)\n"
    		+ "(defconst farm-class 949)\n"
    		+ "(defconst tower-class 952)\n"
    		+ "(defconst wall-class 927)\n"
    		+ "(defconst gate-class 939)\n"
    		+ "(defconst king-class 959)\n"
    		+ "(defconst livestock-class 958)\n"
    		+ "(defconst infantry-class 906)\n"
    		+ "(defconst archery-class 900)\n"
    		+ "(defconst archery-cannon-class 944)\n"
    		+ "(defconst cavalry-class 912)\n"
    		+ "(defconst cavalry-archer-class 936)\n"
    		+ "(defconst cavalry-cannon-class 923)\n"
    		+ "(defconst monastery-class 918)\n"
    		+ "(defconst siege-weapon-class 913)\n"
    		+ "(defconst scorpion-class 955)\n"
    		+ "(defconst packed-trebuchet-class 951)\n"
    		+ "(defconst unpacked-trebuchet-class 954)\n"
    		+ "(defconst petard-class 935)\n"
    		+ "(defconst warship-class 922)\n"
    		+ "(defconst all-units-class -1)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define FoundationId Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst town-center-foundation 621)\n"
    		+ "(defconst gate-ascending 487)\n"
    		+ "(defconst gate-ascending-closed 64)\n"
    		+ "(defconst gate-ascending-open 78)\n"
    		+ "(defconst gate-descending 490)\n"
    		+ "(defconst gate-descending-closed 88)\n"
    		+ "(defconst gate-descending-open 99)\n"
    		+ "(defconst gate-horizontal 665)\n"
    		+ "(defconst gate-horizontal-closed 659)\n"
    		+ "(defconst gate-horizontal-open 661)\n"
    		+ "(defconst gate-vertical 673)\n"
    		+ "(defconst gate-vertical-closed 667)\n"
    		+ "(defconst gate-vertical-open 669)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ResearchState Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst research-unavailable 0)\n"
    		+ "(defconst research-available 1)\n"
    		+ "(defconst research-pending 2)\n"
    		+ "(defconst research-complete 3)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define TimerState Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst timer-disabled 0)\n"
    		+ "(defconst timer-triggered 1)\n"
    		+ "(defconst timer-running 2)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define GroupType Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst group-type-land-attack 100)\n"
    		+ "(defconst group-type-land-explore 101)\n"
    		+ "(defconst group-type-land-trade 109)\n"
    		+ "(defconst group-type-water-attack 102)\n"
    		+ "(defconst group-type-water-explore 103)\n"
    		+ "(defconst group-type-water-trade 106)\n"
    		+ "(defconst group-type-transport-ship 104)\n"
    		+ "(defconst group-type-fishing-ship 105)\n"
    		+ "(defconst group-type-forward-builder 107)\n"
    		+ "(defconst group-type-monk 108)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define IdleType Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst idle-type-villager 0)\n"
    		+ "(defconst idle-type-trade-cart 1)\n"
    		+ "(defconst idle-type-fishing-ship 2)\n"
    		+ "(defconst idle-type-trade-cog 3)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define AttackStance Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst stance-aggressive 0)\n"
    		+ "(defconst stance-defensive 1)\n"
    		+ "(defconst stance-stand-ground 2)\n"
    		+ "(defconst stance-no-attack 3)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ResourceAmount Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst amount-food 0)\n"
    		+ "(defconst amount-wood 1)\n"
    		+ "(defconst amount-stone 2)\n"
    		+ "(defconst amount-gold 3)\n"
    		+ "(defconst amount-population-cap 4)\n"
    		+ "(defconst amount-religion 5)\n"
    		+ "(defconst amount-current-age 6)\n"
    		+ "(defconst amount-relics 7)\n"
    		+ "(defconst amount-trade-bonus 8)\n"
    		+ "(defconst amount-trade-goods 9)\n"
    		+ "(defconst amount-trade-production 10)\n"
    		+ "(defconst amount-population 11)\n"
    		+ "(defconst amount-decay 12)\n"
    		+ "(defconst amount-discovery 13)\n"
    		+ "(defconst amount-ruins 14)\n"
    		+ "(defconst amount-meat 15)\n"
    		+ "(defconst amount-berries 16)\n"
    		+ "(defconst amount-fish 17)\n"
    		+ "(defconst amount-kills 20)\n"
    		+ "(defconst amount-research-count 21)\n"
    		+ "(defconst amount-exploration 22)\n"
    		+ "(defconst amount-convert-priest 27)\n"
    		+ "(defconst amount-convert-building 28)\n"
    		+ "(defconst amount-building-limit 30)\n"
    		+ "(defconst amount-food-limit 31)\n"
    		+ "(defconst amount-unit-limit 32)\n"
    		+ "(defconst amount-maintenance 33)\n"
    		+ "(defconst amount-faith 34)\n"
    		+ "(defconst amount-faith-recharge-rate 35)\n"
    		+ "(defconst amount-farm-food 36)\n"
    		+ "(defconst amount-civilian-population 37)\n"
    		+ "(defconst amount-all-techs-achieved 39)\n"
    		+ "(defconst amount-military-population 40)\n"
    		+ "(defconst amount-conversions 41)\n"
    		+ "(defconst amount-wonder 42)\n"
    		+ "(defconst amount-razings 43)\n"
    		+ "(defconst amount-kill-ratio 44)\n"
    		+ "(defconst amount-player-killed 45)\n"
    		+ "(defconst amount-tribute-inefficiency 46)\n"
    		+ "(defconst amount-gold-bonus 47)\n"
    		+ "(defconst amount-town-center-unavailable 48)\n"
    		+ "(defconst amount-gold-counter 49)\n"
    		+ "(defconst amount-writing 50)\n"
    		+ "(defconst amount-monasteries 52)\n"
    		+ "(defconst amount-tribute 53)\n"
    		+ "(defconst amount-hold-ruins 54)\n"
    		+ "(defconst amount-hold-relics 55)\n"
    		+ "(defconst amount-ore 56)\n"
    		+ "(defconst amount-captured-unit 57)\n"
    		+ "(defconst amount-trade-good-quality 59)\n"
    		+ "(defconst amount-trade-market-level 60)\n"
    		+ "(defconst amount-formations 61)\n"
    		+ "(defconst amount-building-housing-rate 62)\n"
    		+ "(defconst amount-gather-tax-rate 63)\n"
    		+ "(defconst amount-gather-accumulator 64)\n"
    		+ "(defconst amount-salvage-decay-rate 65)\n"
    		+ "(defconst amount-allow-formations 66)\n"
    		+ "(defconst amount-can-convert 67)\n"
    		+ "(defconst amount-player1-kills 69)\n"
    		+ "(defconst amount-player2-kills 70)\n"
    		+ "(defconst amount-player3-kills 71)\n"
    		+ "(defconst amount-player4-kills 72)\n"
    		+ "(defconst amount-player5-kills 73)\n"
    		+ "(defconst amount-player6-kills 74)\n"
    		+ "(defconst amount-player7-kills 75)\n"
    		+ "(defconst amount-player8-kills 76)\n"
    		+ "(defconst amount-convert-resistance 77)\n"
    		+ "(defconst amount-trade-vig-rate 78)\n"
    		+ "(defconst amount-stone-bonus 79)\n"
    		+ "(defconst amount-queued-count 80)\n"
    		+ "(defconst amount-training-count 81)\n"
    		+ "(defconst amount-raider 82)\n"
    		+ "(defconst amount-boarding-recharge-rate 83)\n"
    		+ "(defconst amount-starting-villagers 84)\n"
    		+ "(defconst amount-research-cost-mod 85)\n"
    		+ "(defconst amount-research-time-mod 86)\n"
    		+ "(defconst amount-convert-boats 87)\n"
    		+ "(defconst amount-fish-trap-food 88)\n"
    		+ "(defconst amount-heal-rate-modifier 89)\n"
    		+ "(defconst amount-heal-range 90)\n"
    		+ "(defconst amount-starting-food 91)\n"
    		+ "(defconst amount-starting-wood 92)\n"
    		+ "(defconst amount-starting-stone 93)\n"
    		+ "(defconst amount-starting-gold 94)\n"
    		+ "(defconst amount-raider-ability 95)\n"
    		+ "(defconst amount-berserker-heal-timer 96)\n"
    		+ "(defconst amount-dominant-sheep-control 97)\n"
    		+ "(defconst amount-object-cost-summation 98)\n"
    		+ "(defconst amount-research-cost-summation 99)\n"
    		+ "(defconst amount-relic-income-summation 100)\n"
    		+ "(defconst amount-trade-income-summation 101)\n"
    		+ "(defconst amount-player1-tribute 102)\n"
    		+ "(defconst amount-player2-tribute 103)\n"
    		+ "(defconst amount-player3-tribute 104)\n"
    		+ "(defconst amount-player4-tribute 105)\n"
    		+ "(defconst amount-player5-tribute 106)\n"
    		+ "(defconst amount-player6-tribute 107)\n"
    		+ "(defconst amount-player7-tribute 108)\n"
    		+ "(defconst amount-player8-tribute 109)\n"
    		+ "(defconst amount-player1-kill-value 110)\n"
    		+ "(defconst amount-player2-kill-value 111)\n"
    		+ "(defconst amount-player3-kill-value 112)\n"
    		+ "(defconst amount-player4-kill-value 113)\n"
    		+ "(defconst amount-player5-kill-value 114)\n"
    		+ "(defconst amount-player6-kill-value 115)\n"
    		+ "(defconst amount-player7-kill-value 116)\n"
    		+ "(defconst amount-player8-kill-value 117)\n"
    		+ "(defconst amount-player1-razings 118)\n"
    		+ "(defconst amount-player2-razings 119)\n"
    		+ "(defconst amount-player3-razings 120)\n"
    		+ "(defconst amount-player4-razings 121)\n"
    		+ "(defconst amount-player5-razings 122)\n"
    		+ "(defconst amount-player6-razings 123)\n"
    		+ "(defconst amount-player7-razings 124)\n"
    		+ "(defconst amount-player8-razings 125)\n"
    		+ "(defconst amount-player1-razing-value 126)\n"
    		+ "(defconst amount-player2-razing-value 127)\n"
    		+ "(defconst amount-player3-razing-value 128)\n"
    		+ "(defconst amount-player4-razing-value 129)\n"
    		+ "(defconst amount-player5-razing-value 130)\n"
    		+ "(defconst amount-player6-razing-value 131)\n"
    		+ "(defconst amount-player7-razing-value 132)\n"
    		+ "(defconst amount-player8-razing-value 133)\n"
    		+ "(defconst amount-castle 134)\n"
    		+ "(defconst amount-kills-by-player1 136)\n"
    		+ "(defconst amount-kills-by-player2 137)\n"
    		+ "(defconst amount-kills-by-player3 138)\n"
    		+ "(defconst amount-kills-by-player4 139)\n"
    		+ "(defconst amount-kills-by-player5 140)\n"
    		+ "(defconst amount-kills-by-player6 141)\n"
    		+ "(defconst amount-kills-by-player7 142)\n"
    		+ "(defconst amount-kills-by-player8 143)\n"
    		+ "(defconst amount-razings-by-player1 144)\n"
    		+ "(defconst amount-razings-by-player2 145)\n"
    		+ "(defconst amount-razings-by-player3 146)\n"
    		+ "(defconst amount-razings-by-player4 147)\n"
    		+ "(defconst amount-razings-by-player5 148)\n"
    		+ "(defconst amount-razings-by-player6 149)\n"
    		+ "(defconst amount-razings-by-player7 150)\n"
    		+ "(defconst amount-razings-by-player8 151)\n"
    		+ "(defconst amount-value-killed-by-others 152)\n"
    		+ "(defconst amount-value-razed-by-others 153)\n"
    		+ "(defconst amount-killed-by-others 154)\n"
    		+ "(defconst amount-razed-by-others 155)\n"
    		+ "(defconst amount-tribute-from-player1 156)\n"
    		+ "(defconst amount-tribute-from-player2 157)\n"
    		+ "(defconst amount-tribute-from-player3 158)\n"
    		+ "(defconst amount-tribute-from-player4 159)\n"
    		+ "(defconst amount-tribute-from-player5 160)\n"
    		+ "(defconst amount-tribute-from-player6 161)\n"
    		+ "(defconst amount-tribute-from-player7 162)\n"
    		+ "(defconst amount-tribute-from-player8 163)\n"
    		+ "(defconst amount-value-current-units 164)\n"
    		+ "(defconst amount-value-current-buildings 165)\n"
    		+ "(defconst amount-food-total 166)\n"
    		+ "(defconst amount-wood-total 167)\n"
    		+ "(defconst amount-stone-total 168)\n"
    		+ "(defconst amount-gold-total 169)\n"
    		+ "(defconst amount-total-value-of-kills 170)\n"
    		+ "(defconst amount-total-tribute-received 171)\n"
    		+ "(defconst amount-total-value-of-razings 172)\n"
    		+ "(defconst amount-total-castles-built 173)\n"
    		+ "(defconst amount-total-wonders-built 174)\n"
    		+ "(defconst amount-tribute-score 175)\n"
    		+ "(defconst amount-convert-min-adj 176)\n"
    		+ "(defconst amount-convert-max-adj 177)\n"
    		+ "(defconst amount-convert-resist-min-adj 178)\n"
    		+ "(defconst amount-convert-resist-max-adj 179)\n"
    		+ "(defconst amount-convert-building-min 180)\n"
    		+ "(defconst amount-convert-building-max 181)\n"
    		+ "(defconst amount-convert-building-chance 182)\n"
    		+ "(defconst amount-spies 183)\n"
    		+ "(defconst amount-value-wonders-castles 184)\n"
    		+ "(defconst amount-food-score 185)\n"
    		+ "(defconst amount-wood-score 186)\n"
    		+ "(defconst amount-stone-score 187)\n"
    		+ "(defconst amount-gold-score 188)\n"
    		+ "(defconst amount-wood-bonus 189)\n"
    		+ "(defconst amount-food-bonus 190)\n"
    		+ "(defconst amount-relic-rate 191)\n"
    		+ "(defconst amount-heresy 192)\n"
    		+ "(defconst amount-theocracy 193)\n"
    		+ "(defconst amount-crenellations 194)\n"
    		+ "(defconst amount-construction-rate-mod 195)\n"
    		+ "(defconst amount-hun-wonder-bonus 196)\n"
    		+ "(defconst amount-spies-discount 197)\n"
    		+ "(defconst amount-unused-0 220)\n"
    		+ "(defconst amount-unused-1 221)\n"
    		+ "(defconst amount-unused-2 222)\n"
    		+ "(defconst amount-unused-3 223)\n"
    		+ "(defconst amount-unused-4 224)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Unused ResourceAmount Constants\n"
    		+ ";--------------------------------------\n"
    		+ ";(defconst amount-houses 51)\n"
    		+ ";(defconst amount-hit-points-killed 68)\n"
    		+ ";(defconst amount-hit-points-razings 135)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ProjectileType Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst projectile-town-center 0)\n"
    		+ "(defconst projectile-castle 1)\n"
    		+ "(defconst projectile-watch-tower 2)\n"
    		+ "(defconst projectile-bombard-tower 3)\n"
    		+ "(defconst projectile-ship 4)\n"
    		+ "(defconst projectile-siege 5)\n"
    		+ "(defconst projectile-fortification 6)\n"
    		+ "(defconst projectile-any 7)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define EscrowState Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst with-escrow 0)\n"
    		+ "(defconst without-escrow 1)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ExploredState Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst explored-no 0)\n"
    		+ "(defconst explored-yes 128)					;point has been seen in the past\n"
    		+ "(defconst explored-active 15)				;point is currently visible by an object\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define PlacementType Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst place-normal 0)\n"
    		+ "(defconst place-forward 1)\n"
    		+ "(defconst place-control 2)\n"
    		+ "(defconst place-point 3)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define PriorityType Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst priority-offense 0)\n"
    		+ "(defconst priority-defense 1)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define PositionType Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst position-center 0)\n"
    		+ "(defconst position-opposite 1)\n"
    		+ "(defconst position-corner 2)\n"
    		+ "(defconst position-enemy 3)\n"
    		+ "(defconst position-border 4)\n"
    		+ "(defconst position-mirror 5)\n"
    		+ "(defconst position-flank 6)\n"
    		+ "(defconst position-zero 7)\n"
    		+ "(defconst position-map-size 8)\n"
    		+ "(defconst position-self 9)\n"
    		+ "(defconst position-target 10)\n"
    		+ "(defconst position-focus 11)\n"
    		+ "(defconst position-object 12)\n"
    		+ "(defconst position-point 13)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define SearchSource Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst search-local 1)\n"
    		+ "(defconst search-remote 2)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ObjectList Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst list-active 0)\n"
    		+ "(defconst list-inactive 1)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ObjectStatus Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst status-pending 0)\n"
    		+ "(defconst status-ready 2)\n"
    		+ "(defconst status-resource 3)\n"
    		+ "(defconst status-down 4)\n"
    		+ "(defconst status-gather 5)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define SearchOrder Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst search-order-none 0)\n"
    		+ "(defconst search-order-asc 1)\n"
    		+ "(defconst search-order-desc 2)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define GuardFlag Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst guard-flag-victory 1)\n"
    		+ "(defconst guard-flag-resource 2)\n"
    		+ "(defconst guard-flag-inverse 4)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ProgressType Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst progress-type-train 102)\n"
    		+ "(defconst progress-type-research 103)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define TargetAction Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst action-default 0)	;target-point -> action-move\n"
    		+ "(defconst action-move 1)	;target-point + target-objects\n"
    		+ "(defconst action-patrol 2)	;target-point + target-objects\n"
    		+ "(defconst action-guard 3)	;target-point -> action-move\n"
    		+ "(defconst action-follow 4)	;target-point -> action-move\n"
    		+ "(defconst action-stop 5)	;target-point + target-objects\n"
    		+ "(defconst action-ground 6)	;target-point + target-objects\n"
    		+ "(defconst action-garrison 7)	;target-point -> action-move\n"
    		+ "(defconst action-delete 8)	;target-point + target-objects\n"
    		+ "(defconst action-unload 9)	;target-objects -> action-none\n"
    		+ "(defconst action-train 10)	;target-objects -> action-none\n"
    		+ "(defconst action-gather 11)	;target-point + target-objects\n"
    		+ "(defconst action-lock 12)	;target-objects -> action-none\n"
    		+ "(defconst action-work 13)	;target-objects -> action-none\n"
    		+ "(defconst action-ungarrison 14)	;target-objects -> action-none\n"
    		+ "(defconst action-drop-relic 15)	;target-objects -> action-none\n"
    		+ "(defconst action-pack 16)	;target-objects -> action-none\n"
    		+ "(defconst action-unpack 17)	;target-objects -> action-none\n"
    		+ "(defconst action-none 18)	;target-point + target-objects\n"
    		+ "\n"
    		+ "; action-unload: buildings ungarrison to gather point, siege (913) eject in-place, transports to target-point\n"
    		+ "; action-ungarrison: selected units from inside an object are ungarrisoned\n"
    		+ "; action-gather: set gather point (for buildings only)\n"
    		+ "; action-work: send villagers back to work\n"
    		+ "\n"
    		+ "; action-train: (up-target-point inGoalEscrowState action-train typeOp inOpTypeId)\n"
    		+ "; inGoalEscrowState must be either 0 for without-escrow or an extended goal from 41-510\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define Formation Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst formation-line 2)\n"
    		+ "(defconst formation-box 4)\n"
    		+ "(defconst formation-stagger 7)\n"
    		+ "(defconst formation-flank 8)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define CmdId Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst cmdid-flag 0)\n"
    		+ "(defconst cmdid-livestock-gaia 1)\n"
    		+ "(defconst cmdid-civilian-building 2)\n"
    		+ "(defconst cmdid-villager 3)\n"
    		+ "(defconst cmdid-military 4)\n"
    		+ "(defconst cmdid-trade 5)\n"
    		+ "(defconst cmdid-monk 6)\n"
    		+ "(defconst cmdid-transport 7)\n"
    		+ "(defconst cmdid-relic 8)					;includes monk-with-relic\n"
    		+ "(defconst cmdid-fishing-ship 9)\n"
    		+ "(defconst cmdid-military-building 10)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ActionId Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst actionid-attack 600)\n"
    		+ "(defconst actionid-defend 601)\n"
    		+ "(defconst actionid-build 602)\n"
    		+ "(defconst actionid-heal 603)\n"
    		+ "(defconst actionid-convert 604)\n"
    		+ "(defconst actionid-explore 605)\n"
    		+ "(defconst actionid-stop 606)\n"
    		+ "(defconst actionid-runaway 607)\n"
    		+ "(defconst actionid-retreat 608)\n"
    		+ "(defconst actionid-gather 609)\n"
    		+ "(defconst actionid-move 610)\n"
    		+ "(defconst actionid-patrol 611)\n"
    		+ "(defconst actionid-follow 612)\n"
    		+ "(defconst actionid-hunt 613)\n"
    		+ "(defconst actionid-transport 614)\n"
    		+ "(defconst actionid-trade 615)\n"
    		+ "(defconst actionid-evade 616)\n"
    		+ "(defconst actionid-enter 617)\n"
    		+ "(defconst actionid-repair 618)\n"
    		+ "(defconst actionid-train 619)\n"
    		+ "(defconst actionid-research 620)\n"
    		+ "(defconst actionid-unload 621)\n"
    		+ "(defconst actionid-relic 631)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define OrderId Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst orderid-attack 700)\n"
    		+ "(defconst orderid-defend 701)\n"
    		+ "(defconst orderid-build 702)\n"
    		+ "(defconst orderid-heal 703)\n"
    		+ "(defconst orderid-convert 704)\n"
    		+ "(defconst orderid-explore 705)\n"
    		+ "(defconst orderid-stop 706)\n"
    		+ "(defconst orderid-runaway 707)\n"
    		+ "(defconst orderid-retreat 708)\n"
    		+ "(defconst orderid-gather 709)\n"
    		+ "(defconst orderid-move 710)\n"
    		+ "(defconst orderid-patrol 711)\n"
    		+ "(defconst orderid-follow 712)\n"
    		+ "(defconst orderid-hunt 713)\n"
    		+ "(defconst orderid-transport 714)\n"
    		+ "(defconst orderid-trade 715)\n"
    		+ "(defconst orderid-evade 716)\n"
    		+ "(defconst orderid-enter 717)\n"
    		+ "(defconst orderid-repair 718)\n"
    		+ "(defconst orderid-train 719)\n"
    		+ "(defconst orderid-research 720)\n"
    		+ "(defconst orderid-unload 721)\n"
    		+ "(defconst orderid-relic 731)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define Mainland Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst off-mainland 0)\n"
    		+ "(defconst on-mainland 1)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ObjectData Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst object-data-index -1)				;only use with up-remove-objects\n"
    		+ "(defconst object-data-id 0)\n"
    		+ "(defconst object-data-type 1)\n"
    		+ "(defconst object-data-class 2)\n"
    		+ "(defconst object-data-category 3)\n"
    		+ "(defconst object-data-cmdid 4)\n"
    		+ "(defconst object-data-action 5)\n"
    		+ "(defconst object-data-order 6)\n"
    		+ "(defconst object-data-target 7)\n"
    		+ "(defconst object-data-point-x 8)\n"
    		+ "(defconst object-data-point-y 9)\n"
    		+ "(defconst object-data-hitpoints 10)\n"
    		+ "(defconst object-data-maxhp 11)\n"
    		+ "(defconst object-data-range 12)\n"
    		+ "(defconst object-data-speed 13)\n"
    		+ "(defconst object-data-dropsite 14)\n"
    		+ "(defconst object-data-resource 15)\n"
    		+ "(defconst object-data-carry 16)\n"
    		+ "(defconst object-data-garrisoned 17)\n"
    		+ "(defconst object-data-garrison-count 18)\n"
    		+ "(defconst object-data-status 19)			;0:incomplete, 2:active, 3:resource, >=4:inactive\n"
    		+ "(defconst object-data-player 20)\n"
    		+ "(defconst object-data-attack-stance 21)\n"
    		+ "(defconst object-data-action-time 22)\n"
    		+ "(defconst object-data-target-id 23)\n"
    		+ "(defconst object-data-formation-id 24)\n"
    		+ "(defconst object-data-patrolling 25)\n"
    		+ "(defconst object-data-strike-armor 26)\n"
    		+ "(defconst object-data-pierce-armor 27)\n"
    		+ "(defconst object-data-base-attack 28)\n"
    		+ "(defconst object-data-locked 29)\n"
    		+ "(defconst object-data-garrison-id 30)\n"
    		+ "(defconst object-data-train-count 31)\n"
    		+ "(defconst object-data-tasks-count 32)		;increased for internal tasks performed on the object (may be more than 1 per event)\n"
    		+ "(defconst object-data-attacker-count 33)	;not increased for certain situations like hunting\n"
    		+ "(defconst object-data-attacker-id 34)		;not set for certain situations like hunting\n"
    		+ "(defconst object-data-under-attack 35)		;not set for certain situations like hunting\n"
    		+ "(defconst object-data-attack-timer 36)		;resets to 60s for each attack (buildings only)\n"
    		+ "(defconst object-data-point-z 37)\n"
    		+ "(defconst object-data-precise-x 38)		;point x100.0\n"
    		+ "(defconst object-data-precise-y 39)\n"
    		+ "(defconst object-data-precise-z 40)\n"
    		+ "(defconst object-data-researching 41)\n"
    		+ "(defconst object-data-tile-position 42)		;match with sn-target-point-adjustment\n"
    		+ "(defconst object-data-tile-inverse 43)\n"
    		+ "(defconst object-data-distance 44)		;based on target-point\n"
    		+ "(defconst object-data-precise-distance 45)	;distance x100\n"
    		+ "(defconst object-data-full-distance 46)\n"
    		+ "(defconst object-data-map-zone-id 47)\n"
    		+ "(defconst object-data-on-mainland 48)		;compares map-zone-id to home TC map-zone-id\n"
    		+ "(defconst object-data-idling 49)\n"
    		+ "(defconst object-data-move-x 50)\n"
    		+ "(defconst object-data-move-y 51)\n"
    		+ "(defconst object-data-precise-move-x 52)\n"
    		+ "(defconst object-data-precise-move-y 53)\n"
    		+ "(defconst object-data-reload-time 54)		;in milliseconds\n"
    		+ "(defconst object-data-next-attack 55)		;in milliseconds\n"
    		+ "(defconst object-data-train-site 56)\n"
    		+ "(defconst object-data-train-time 57)		;in seconds\n"
    		+ "(defconst object-data-blast-radius 58)		;radius x100.0\n"
    		+ "(defconst object-data-blast-level 59)\n"
    		+ "(defconst object-data-progress-type 60)\n"
    		+ "(defconst object-data-progress-value 61)\n"
    		+ "(defconst object-data-min-range 62)\n"
    		+ "(defconst object-data-target-time 63)		;in milliseconds (not for villagers)\n"
    		+ "(defconst object-data-heresy 64)		;checks amount-heresy\n"
    		+ "(defconst object-data-faith 65)			;checks amount-convert-resistance\n"
    		+ "(defconst object-data-redemption 66)		;checks amount-convert-building\n"
    		+ "(defconst object-data-atonement 67)		;checks amount-convert-priest\n"
    		+ "(defconst object-data-theocracy 68)		;checks amount-theocracy\n"
    		+ "(defconst object-data-spies 69)			;checks amount-spies\n"
    		+ "(defconst object-data-ballistics 70)\n"
    		+ "(defconst object-data-gather-type 71)		;food, wood, gold, stone, or -1 for none\n"
    		+ "(defconst object-data-language-id 72)		;can use to check villager types\n"
    		+ "(defconst object-data-group-flag 73)		;group id from 0 to 9 or -2 for none\n"
    		+ "(defconst object-data-hero-flags 74)		;combined hero status flags\n"
    		+ "(defconst object-data-hero 75)			;has actual hero flag set\n"
    		+ "(defconst object-data-auto-heal 76)		;will hero heal (non-berserk)\n"
    		+ "(defconst object-data-no-convert 77)		;cannot be converted\n"
    		+ "(defconst object-data-frame-delay 78)		;number of frames for projectile delay\n"
    		+ "(defconst object-data-attack-count 79)		;consecutive attack count\n"
    		+ "(defconst object-data-to-precise 80)		;precise distance to a precise target-point\n"
    		+ "(defconst object-data-base-type 81)		;object base type id\n"
    		+ "(defconst object-data-upgrade-type 82)		;object upgrade type id\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define LangId Constants (aoc)\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst lid-villager-idle 5121)\n"
    		+ "(defconst lid-villager-shepherd 5496)\n"
    		+ "(defconst lid-villager-farmer 5123)\n"
    		+ "(defconst lid-villager-forager 5402)\n"
    		+ "(defconst lid-villager-hunter 5124)\n"
    		+ "(defconst lid-villager-fisherman 5499)\n"
    		+ "(defconst lid-villager-lumberjack 5125)\n"
    		+ "(defconst lid-villager-gold-miner 5482)\n"
    		+ "(defconst lid-villager-stone-miner 5126)\n"
    		+ "(defconst lid-villager-builder 5122)\n"
    		+ "(defconst lid-villager-repairer 5127)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define Terrain Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst terrain-grass 0)\n"
    		+ "(defconst terrain-grass2 12)\n"
    		+ "(defconst terrain-grass3 9)\n"
    		+ "(defconst terrain-grass-snow 34)\n"
    		+ "(defconst terrain-grass-old 16)\n"
    		+ "(defconst terrain-water 1)\n"
    		+ "(defconst terrain-water-deep 22)\n"
    		+ "(defconst terrain-water-medium 23)\n"
    		+ "(defconst terrain-water-bridge 28)\n"
    		+ "(defconst terrain-water-old 15)\n"
    		+ "(defconst terrain-water-beach 2)\n"
    		+ "(defconst terrain-shallows 4)\n"
    		+ "(defconst terrain-ice 26)\n"
    		+ "(defconst terrain-ice2 35)\n"
    		+ "(defconst terrain-ice-beach 37)\n"
    		+ "(defconst terrain-desert 14)\n"
    		+ "(defconst terrain-dirt 6)\n"
    		+ "(defconst terrain-dirt2 11)\n"
    		+ "(defconst terrain-dirt3 3)\n"
    		+ "(defconst terrain-dirt-snow 33)\n"
    		+ "(defconst terrain-farm 7)\n"
    		+ "(defconst terrain-farm1 29)\n"
    		+ "(defconst terrain-farm2 30)\n"
    		+ "(defconst terrain-farm3 31)\n"
    		+ "(defconst terrain-farm-dead 8)\n"
    		+ "(defconst terrain-forest 10)\n"
    		+ "(defconst terrain-forest-bamboo 18)\n"
    		+ "(defconst terrain-forest-jungle 17)\n"
    		+ "(defconst terrain-forest-oak 20)\n"
    		+ "(defconst terrain-forest-palm 13)\n"
    		+ "(defconst terrain-forest-pine 19)\n"
    		+ "(defconst terrain-forest-snow 21)\n"
    		+ "(defconst terrain-foundation 27)\n"
    		+ "(defconst terrain-foundation-snow 36)\n"
    		+ "(defconst terrain-koh 40)\n"
    		+ "(defconst terrain-leaves 5)\n"
    		+ "(defconst terrain-road 24)\n"
    		+ "(defconst terrain-road-broken 25)\n"
    		+ "(defconst terrain-road-snow 38)\n"
    		+ "(defconst terrain-road-fungus 39)\n"
    		+ "(defconst terrain-snow 32)\n"
    		+ "(defconst terrain-unknown 41)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define SortTargetMethod Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst sort-targets 0)\n"
    		+ "(defconst sort-random 1)\n"
    		+ "(defconst sort-distance 2)\n"
    		+ "(defconst sort-hitpoints 3)\n"
    		+ "(defconst sort-range 4)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define FindPlayerMethod Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst find-attacker 0)\n"
    		+ "(defconst find-random 1)\n"
    		+ "(defconst find-closest 2)\n"
    		+ "(defconst find-ordered 3)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define ScoutMethod Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst scout-center 0)\n"
    		+ "(defconst scout-opposite 1)\n"
    		+ "(defconst scout-corner 2)\n"
    		+ "(defconst scout-enemy 3)\n"
    		+ "(defconst scout-border 4)\n"
    		+ "(defconst scout-mirror 5)\n"
    		+ "(defconst scout-flank 6)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define AdjustPoint Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst adjust-default 0)\n"
    		+ "(defconst adjust-left 1)\n"
    		+ "(defconst adjust-top 2)\n"
    		+ "(defconst adjust-right 3)\n"
    		+ "(defconst adjust-bottom 4)\n"
    		+ "(defconst adjust-middle 5)\n"
    		+ "(defconst adjust-precise 6)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define PlayerStance Constants\n"
    		+ ";--------------------------------------\n"
    		+ ";(defconst ally 0)\n"
    		+ ";(defconst neutral 1)\n"
    		+ ";(defconst enemy 3)\n"
    		+ ";(defconst any 2)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define DropsiteMinDistance Constants\n"
    		+ ";--------------------------------------\n"
    		+ ";(defconst hunting 4)\n"
    		+ ";(defconst boar-hunting 5)\n"
    		+ ";(defconst deer-hunting 6)\n"
    		+ ";(defconst live-boar 7)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define Counting Constants\n"
    		+ ";--------------------------------------\n"
    		+ ";(defconst monk-set 970)\n"
    		+ ";(defconst trebuchet-set 971)\n"
    		+ ";(defconst huskarl-set 972)\n"
    		+ ";(defconst villager-shepherd 973)\n"
    		+ ";(defconst villager-forager 974)\n"
    		+ ";(defconst villager-farmer 975)\n"
    		+ ";(defconst villager-hunter 976)\n"
    		+ ";(defconst villager-fisherman 977)\n"
    		+ ";(defconst villager-food 978)\n"
    		+ ";(defconst villager-wood 979)\n"
    		+ ";(defconst villager-stone 980)\n"
    		+ ";(defconst villager-gold 981)\n"
    		+ ";(defconst villager-builder 982)\n"
    		+ ";(defconst villager-repairer 983)\n"
    		+ ";(defconst villager-base 984)\n"
    		+ "\n"
    		+ ";--------------------------------------\n"
    		+ "; Define Extended Strategic Numbers\n"
    		+ ";--------------------------------------\n"
    		+ ";(defconst sn-enable-new-building-system 242)\n"
    		+ ";(defconst sn-percent-building-cancellation 243)\n"
    		+ ";(defconst sn-enable-boar-hunting 244)\n"
    		+ ";(defconst sn-minimum-number-hunters 245)\n"
    		+ ";(defconst sn-object-repair-level 246)\n"
    		+ ";(defconst sn-enable-patrol-attack 247)\n"
    		+ ";(defconst sn-dropsite-separation-distance 248)\n"
    		+ ";(defconst sn-target-player-number 249)\n"
    		+ ";(defconst sn-safe-town-size 250)\n"
    		+ ";(defconst sn-focus-player-number 251)\n"
    		+ ";(defconst sn-minimum-boar-lure-group-size 252)\n"
    		+ ";(defconst sn-preferred-mill-placement 253)\n"
    		+ ";(defconst sn-enable-offensive-priority 254)\n"
    		+ ";(defconst sn-building-targeting-mode 255)\n"
    		+ ";(defconst sn-home-exploration-time 256)\n"
    		+ ";(defconst sn-number-civilian-militia 257)\n"
    		+ ";(defconst sn-allow-civilian-offense 258)\n"
    		+ ";(defconst sn-preferred-trade-distance 259)\n"
    		+ ";(defconst sn-lumber-camp-max-distance 260)\n"
    		+ ";(defconst sn-mining-camp-max-distance 261)\n"
    		+ ";(defconst sn-wall-targeting-mode 262)\n"
    		+ ";(defconst sn-livestock-to-town-center 263)\n"
    		+ ";(defconst sn-enable-training-queue 264)\n"
    		+ ";(defconst sn-ignore-tower-elevation 265)\n"
    		+ ";(defconst sn-town-center-placement 266)\n"
    		+ ";(defconst sn-disable-tower-priority 267)\n"
    		+ ";(defconst sn-placement-zone-size 268)\n"
    		+ ";(defconst sn-placement-fail-delta 269)\n"
    		+ ";(defconst sn-placement-to-center 270)\n"
    		+ ";(defconst sn-disable-attack-groups 271)\n"
    		+ ";(defconst sn-allow-adjacent-dropsites 272)\n"
    		+ ";(defconst sn-defer-dropsite-update 273)\n"
    		+ ";(defconst sn-maximum-garrison-fill 274)\n"
    		+ ";(defconst sn-number-garrison-units 275)\n"
    		+ ";(defconst sn-filter-under-attack 276)\n"
    		+ ";(defconst sn-disable-defend-groups 277)\n"
    		+ ";(defconst sn-dock-placement-mode 278)\n"
    		+ ";(defconst sn-dock-proximity-factor 279)\n"
    		+ ";(defconst sn-dock-avoidance-factor 280)\n"
    		+ ";(defconst sn-dock-training-filter 281)\n"
    		+ ";(defconst sn-free-siege-targeting 282)\n"
    		+ ";(defconst sn-warship-targeting-mode 283)\n"
    		+ ";(defconst sn-disable-sighted-response-cap 284)\n"
    		+ ";(defconst sn-disable-builder-assistance 285)\n"
    		+ ";(defconst sn-local-targeting-mode 286)\n"
    		+ ";(defconst sn-livestock-defend-priority 287)\n"
    		+ ";(defconst sn-number-tasked-units 288)\n"
    		+ ";(defconst sn-minimum-tasked-units 289)\n"
    		+ ";(defconst sn-maximum-tasked-units 290)\n"
    		+ ";(defconst sn-disable-villager-garrison 291)\n"
    		+ ";(defconst sn-target-point-adjustment 292)\n"
    		+ ";(defconst sn-unexplored-construction 293)\n"
    		+ ";(defconst sn-disable-trade-evasion 294)\n"
    		+ ";(defconst sn-boar-lure-destination 295)\n"
    		+ "";
    
    private static final String BARRACKS_DEFAULT_CONSTANT = ";--------------------------------------\n"
    		+ "; Define Barracks Constants\n"
    		+ ";--------------------------------------\n"
    		+ "(defconst actionid-any -1)\n"
		    + "(defconst orderid-any -1)\n"
		    + "(defconst stance-unchanged -1)\n"
		    + "(defconst formation-unchanged -1)\n"
		    + "(defconst monk-with-relic-class 943)\n";
    
    // Method to print the default constant
    public static String PrintDefaultPerConstants() {
        return (DEFAULT_CONSTANT + "\n" + BARRACKS_DEFAULT_CONSTANT);
    }
}
