package com.fategrinder.barracks;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.fategrinder.barracks.Environment.VariableInfo;

public class ParameterClassesContainer {
	static ParameterClass pCompareOp = new ParameterClass("compareOp", "AoC", "&#60;rel-op&#62;");
	static ParameterClass pMathOp = new ParameterClass("mathOp", "UP", "undefined");
	static ParameterClass pTypeOp = new ParameterClass("typeOp", "UP", "undefined");
	static ParameterClass pActionId = new ParameterClass("ActionId", "UP", "undefined");
	static ParameterClass pAge = new ParameterClass("Age", "AoC", "&#60;age&#62;");
	static ParameterClass pAttackStance = new ParameterClass("AttackStance", "UP", "undefined");
	static ParameterClass pAttrId = new ParameterClass("AttrId", "DE", "undefined");
	static ParameterClass pBuildingId = new ParameterClass("BuildingId", "AoC", "&#60;building&#62;");
	static ParameterClass pCiv = new ParameterClass("Civ", "AoC", "&#60;civ&#62;");
	static ParameterClass pClassId = new ParameterClass("ClassId", "UP", "undefined");
	static ParameterClass pCmdId = new ParameterClass("CmdId", "UP", "undefined");
	static ParameterClass pColorId = new ParameterClass("ColorId", "UP", "undefined");
	static ParameterClass pCommodity = new ParameterClass("Commodity", "AoC", "&#60;commodity&#62;");
	static ParameterClass pDefconst = new ParameterClass("Defconst", "UP", "undefined");
	static ParameterClass pDifficulty = new ParameterClass("Difficulty", "AoC", "&#60;difficulty&#62;");
	static ParameterClass pDiffParameterId = new ParameterClass("DiffParameterId", "AoC",
			"&#60;difficulty-parameter&#62;");
	static ParameterClass pDUCAction = new ParameterClass("DUCAction", "UP", "undefined");
	static ParameterClass pEffectId = new ParameterClass("EffectId", "DE", "undefined");
	static ParameterClass pEscrowGoalId = new ParameterClass("EscrowGoalId", "UP", "undefined");
	static ParameterClass pEventId = new ParameterClass("EventId", "AoC", "&#60;event-id&#62;");
	static ParameterClass pEventType = new ParameterClass("EventType", "AoC", "&#60;event-type&#62;");
	static ParameterClass pExploredState = new ParameterClass("ExploredState", "UP", "undefined");
	static ParameterClass pFactId = new ParameterClass("FactId", "UP", "undefined");
	static ParameterClass pFactParameter = new ParameterClass("FactParameter", "UP", "undefined");
	static ParameterClass pFindPlayerMethod = new ParameterClass("FindPlayerMethod", "UP", "undefined");
	static ParameterClass pFlag = new ParameterClass("Flag", "UP", "undefined");
	static ParameterClass pFormation = new ParameterClass("Formation", "UP", "undefined");
	static ParameterClass pGameType = new ParameterClass("GameType", "AoC", "undefined");
	static ParameterClass pGoalId = new ParameterClass("GoalId", "AoC", "&#60;goal-id&#62;");
	static ParameterClass pGroupId = new ParameterClass("GroupId", "UP", "undefined");
	static ParameterClass pGroupType = new ParameterClass("GroupType", "UP", "undefined");
	static ParameterClass pGuardFlag = new ParameterClass("GuardFlag", "UP", "undefined");
	static ParameterClass pId = new ParameterClass("Id", "UP", "undefined");
	static ParameterClass pIdleType = new ParameterClass("IdleType", "UP", "undefined");
	static ParameterClass pIndex = new ParameterClass("Index", "UP", "undefined");
	static ParameterClass pItemId = new ParameterClass("ItemId", "DE", "undefined");
	static ParameterClass pLanguageId = new ParameterClass("LanguageId", "AoC", "&#60;string-id&#62;");
	static ParameterClass pLineId = new ParameterClass("LineId", "AoC", "undefined");
	static ParameterClass pLocalIndex = new ParameterClass("LocalIndex", "UP", "undefined");
	static ParameterClass pLocalList = new ParameterClass("LocalList", "UP", "undefined");
	static ParameterClass pMapSize = new ParameterClass("MapSize", "AoC", "&#60;map-size&#62;");
	static ParameterClass pMapType = new ParameterClass("MapType", "AoC", "&#60;map-type&#62;");
	static ParameterClass pMaxDistance = new ParameterClass("MaxDistance", "UP", "undefined");
	static ParameterClass pMaxGarrison = new ParameterClass("MaxGarrison", "UP", "undefined");
	static ParameterClass pMinDistance = new ParameterClass("MinDistance", "UP", "undefined");
	static ParameterClass pMinGarrison = new ParameterClass("MinGarrison", "UP", "undefined");
	static ParameterClass pObjectData = new ParameterClass("ObjectData", "UP", "undefined");
	static ParameterClass pObjectId = new ParameterClass("ObjectId", "UP", "undefined");
	static ParameterClass pObjectList = new ParameterClass("ObjectList", "UP", "undefined");
	static ParameterClass pObjectStatus = new ParameterClass("ObjectStatus", "UP", "undefined");
	static ParameterClass pOnMainland = new ParameterClass("OnMainland", "UP", "undefined");
	static ParameterClass pOption = new ParameterClass("Option", "UP", "undefined");
	static ParameterClass pOptionGoalId = new ParameterClass("OptionGoalId", "UP", "undefined");
	static ParameterClass pOrderId = new ParameterClass("OrderId", "UP", "undefined");
	static ParameterClass pOutputGoalId = new ParameterClass("OutputGoalId", "UP", "undefined");
	static ParameterClass pPercent = new ParameterClass("Percent", "UP", "undefined");
	static ParameterClass pPerimeter = new ParameterClass("Perimeter", "AoC", "&#60;perimeter&#62;");
	static ParameterClass pPlacementType = new ParameterClass("PlacementType", "UP", "undefined");
	static ParameterClass pPlayerNumber = new ParameterClass("PlayerNumber", "AoC", "&#60;player-number&#62;");
	static ParameterClass pPlayerStance = new ParameterClass("PlayerStance", "AoC", "undefined");
	static ParameterClass pPoint = new ParameterClass("Point", "UP", "undefined");
	static ParameterClass pPositionType = new ParameterClass("PositionType", "UP", "undefined");
	static ParameterClass pProgressType = new ParameterClass("ProgressType", "UP", "undefined");
	static ParameterClass pProjectileType = new ParameterClass("ProjectileType", "UP", "undefined");
	static ParameterClass pPriorityType = new ParameterClass("PriorityType", "UP", "undefined");
	static ParameterClass pRemoteIndex = new ParameterClass("RemoteIndex", "UP", "undefined");
	static ParameterClass pRemoteList = new ParameterClass("RemoteList", "UP", "undefined");
	static ParameterClass pResearchState = new ParameterClass("ResearchState", "UP", "undefined");
	static ParameterClass pResource = new ParameterClass("Resource", "AoC", "&#60;resource-type&#62;");
	static ParameterClass pResourceType = new ParameterClass("ResourceType", "UP", "undefined");
	static ParameterClass pRuleDelta = new ParameterClass("RuleDelta", "UP", "undefined");
	static ParameterClass pRuleId = new ParameterClass("RuleId", "UP", "undefined");
	static ParameterClass pScoutMethod = new ParameterClass("ScoutMethod", "UP", "undefined");
	static ParameterClass pSearchOrder = new ParameterClass("SearchOrder", "UP", "undefined");
	static ParameterClass pSearchSource = new ParameterClass("SearchSource", "UP", "undefined");
	static ParameterClass pSetId = new ParameterClass("SetId", "UP", "undefined");
	static ParameterClass pSharedGoalId = new ParameterClass("SharedGoalId", "AoC", "&#60;shared-goal-id&#62;");
	static ParameterClass pSignalId = new ParameterClass("SignalId", "AoC", "&#60;signal-id&#62;");
	static ParameterClass pSnId = new ParameterClass("SnId", "AoC", "&#60;strategic-number&#62;");
	static ParameterClass pStartingResources = new ParameterClass("StartingResources", "AoC",
			"&#60;starting-resources&#62;");
	static ParameterClass pString = new ParameterClass("String", "AoC", "&#60;string&#62;");
	static ParameterClass pSubGameType = new ParameterClass("SubGameType", "DE", "undefined");
	static ParameterClass pTauntId = new ParameterClass("TauntId", "AoC", "&#60;taunt-id&#62;");
	static ParameterClass pTechId = new ParameterClass("TechId", "AoC", "&#60;research-item&#62;");
	static ParameterClass pTerrain = new ParameterClass("Terrain", "UP", "undefined");
	static ParameterClass pThreatPlayer = new ParameterClass("ThreatPlayer", "UP", "undefined");
	static ParameterClass pThreatSource = new ParameterClass("ThreatSource", "UP", "undefined");
	static ParameterClass pThreatTarget = new ParameterClass("ThreatTarget", "UP", "undefined");
	static ParameterClass pThreatTime = new ParameterClass("ThreatTime", "UP", "undefined");
	static ParameterClass pTimerId = new ParameterClass("TimerId", "AoC", "&#60;timer-id&#62;");
	static ParameterClass pTimerState = new ParameterClass("TimerState", "UP", "undefined");
	static ParameterClass pTypeId = new ParameterClass("TypeId", "UP", "undefined");
	static ParameterClass pUnitId = new ParameterClass("UnitId", "AoC", "&#60;unit&#62;");
	static ParameterClass pValue = new ParameterClass("Value", "AoC", "&#60;value&#62;");
	static ParameterClass pVictoryCondition = new ParameterClass("VictoryCondition", "AoC",
			"&#60;victory-condition&#62;");
	static ParameterClass pVictoryPlayer = new ParameterClass("VictoryPlayer", "UP", "undefined");
	static ParameterClass pVictoryTime = new ParameterClass("VictoryTime", "UP", "undefined");
	static ParameterClass pVictoryType = new ParameterClass("VictoryType", "UP", "undefined");
	static ParameterClass pWallId = new ParameterClass("WallId", "AoC", "&#60;wall-id&#62;");

	static ParameterClass pObjectName = new ParameterClass("", "", ""); // somewhere to store all the units names
	static final public List<ParameterClass> parametersArray = new ArrayList<ParameterClass>(Arrays.asList(pCompareOp,
			pMathOp, pTypeOp, pActionId, pAge, pAttackStance, pAttrId, pBuildingId, pCiv, pClassId, pCmdId, pColorId,
			pCommodity, pDefconst, pDifficulty, pDiffParameterId, pDUCAction, pEffectId, pEscrowGoalId, pEventId,
			pEventType, pExploredState, pFactId, pFactParameter, pFindPlayerMethod, pFlag, pFormation, pGameType,
			pGoalId, pGroupId, pGroupType, pGuardFlag, pId, pIdleType, pIndex, pItemId, pLanguageId, pLineId,
			pLocalIndex, pLocalList, pMapSize, pMapType, pMaxDistance, pMaxGarrison, pMinDistance, pMinGarrison,
			pObjectData, pObjectId, pObjectList, pObjectStatus, pOnMainland, pOption, pOptionGoalId, pOrderId,
			pOutputGoalId, pPercent, pPerimeter, pPlacementType, pPlayerNumber, pPlayerStance, pPoint, pPositionType,
			pProgressType, pProjectileType, pPriorityType, pRemoteIndex, pRemoteList, pResearchState, pResource,
			pResourceType, pRuleDelta, pRuleId, pScoutMethod, pSearchOrder, pSearchSource, pSetId, pSharedGoalId,
			pSignalId, pSnId, pStartingResources, pString, pSubGameType, pTauntId, pTechId, pTerrain, pThreatPlayer,
			pThreatSource, pThreatTarget, pThreatTime, pTimerId, pTimerState, pTypeId, pUnitId, pValue,
			pVictoryCondition, pVictoryPlayer, pVictoryTime, pVictoryType, pWallId, pObjectName));

	public static final Map<String, ParameterClass> FactParameterAssociatedToFactId = new HashMap<>();

	private static boolean alreadyFilled = false;

	public ParameterClassesContainer() {
		if (!alreadyFilled) {
			pActionId.valueList.add("actionid-any");
			pActionId.valueList.add("actionid-attack");
			pActionId.valueList.add("actionid-defend");
			pActionId.valueList.add("actionid-build");
			pActionId.valueList.add("actionid-heal");
			pActionId.valueList.add("actionid-convert");
			pActionId.valueList.add("actionid-explore");
			pActionId.valueList.add("actionid-stop");
			pActionId.valueList.add("actionid-runaway");
			pActionId.valueList.add("actionid-retreat");
			pActionId.valueList.add("actionid-gather");
			pActionId.valueList.add("actionid-move");
			pActionId.valueList.add("actionid-patrol");
			pActionId.valueList.add("actionid-follow");
			pActionId.valueList.add("actionid-hunt");
			pActionId.valueList.add("actionid-transport");
			pActionId.valueList.add("actionid-trade");
			pActionId.valueList.add("actionid-evade");
			pActionId.valueList.add("actionid-enter");
			pActionId.valueList.add("actionid-repair");
			pActionId.valueList.add("actionid-train");
			pActionId.valueList.add("actionid-research");
			pActionId.valueList.add("actionid-unload");
			pActionId.valueList.add("actionid-relic");
			pAge.valueList.add("dark-age");
			pAge.valueList.add("feudal-age");
			pAge.valueList.add("castle-age");
			pAge.valueList.add("imperial-age");
			pAge.valueList.add("post-imperial-age");
			pAttackStance.valueList.add("stance-unchanged");
			pAttackStance.valueList.add("stance-aggressive");
			pAttackStance.valueList.add("stance-defensive");
			pAttackStance.valueList.add("stance-stand-ground");
			pAttackStance.valueList.add("stance-no-attack");
			pAttrId.valueList.add("attribute-hp");
			pAttrId.valueList.add("attribute-los");
			pAttrId.valueList.add("attribute-obj-max");
			pAttrId.valueList.add("attribute-radius-x");
			pAttrId.valueList.add("attribute-radius-y");
			pAttrId.valueList.add("attribute-speed");
			pAttrId.valueList.add("attribute-turn-speed");
			pAttrId.valueList.add("attribute-armor");
			pAttrId.valueList.add("attribute-weapon");
			pAttrId.valueList.add("attribute-speed-of-attack");
			pAttrId.valueList.add("attribute-hit-chance");
			pAttrId.valueList.add("attribute-weapon-range");
			pAttrId.valueList.add("attribute-work-rate");
			pAttrId.valueList.add("attribute-carry-capacity");
			pAttrId.valueList.add("attribute-base-armor");
			pAttrId.valueList.add("attribute-missile-id");
			pAttrId.valueList.add("attribute-building-facet");
			pAttrId.valueList.add("attribute-defensive-terrain");
			pAttrId.valueList.add("attribute-targetting-type");
			pAttrId.valueList.add("attribute-minimum-weapon-range");
			pAttrId.valueList.add("attribute-attribute-amount-held");
			pAttrId.valueList.add("attribute-area-effect");
			pAttrId.valueList.add("attribute-search-radius");
			pAttrId.valueList.add("attribute-hidden-damage-resist");
			pAttrId.valueList.add("attribute-icon-id");
			pAttrId.valueList.add("attribute-fire-missile-at-frame");
			pAttrId.valueList.add("attribute-area-effect-level.");
			pAttrId.valueList.add("attribute-blast-defense-level");
			pAttrId.valueList.add("attribute-shown-attack");
			pAttrId.valueList.add("attribute-shown-range");
			pAttrId.valueList.add("attribute-shown-melee-armor");
			pAttrId.valueList.add("attribute-name-id");
			pAttrId.valueList.add("attribute-description-id");
			pAttrId.valueList.add("attribute-terrain-restriction");
			pAttrId.valueList.add("attribute-death-spawn-obj");
			pAttrId.valueList.add("attribute-hotkey-id");
			pAttrId.valueList.add("attribute-resource-cost");
			pAttrId.valueList.add("attribute-creation-time");
			pAttrId.valueList.add("attribute-garrison-arrows");
			pAttrId.valueList.add("attribute-food-cost");
			pAttrId.valueList.add("attribute-wood-cost");
			pAttrId.valueList.add("attribute-gold-cost");
			pAttrId.valueList.add("attribute-stone-cost");
			pAttrId.valueList.add("attribute-max-dup-missiles");
			pAttrId.valueList.add("attribute-garrison-heal-rate");
			pAttrId.valueList.add("attribute-regenration-rate");
			pBuildingId.valueList.add("watch-tower-line");
			pCiv.valueList.add("gaia");
			pCiv.valueList.add("briton");
			pCiv.valueList.add("frankish");
			pCiv.valueList.add("gothic");
			pCiv.valueList.add("teutonic");
			pCiv.valueList.add("japanese");
			pCiv.valueList.add("chinese");
			pCiv.valueList.add("byzantine");
			pCiv.valueList.add("persian");
			pCiv.valueList.add("saracen");
			pCiv.valueList.add("turkish");
			pCiv.valueList.add("viking");
			pCiv.valueList.add("mongol");
			pCiv.valueList.add("celtic");
			pCiv.valueList.add("spanish");
			pCiv.valueList.add("aztec");
			pCiv.valueList.add("mayan");
			pCiv.valueList.add("hun");
			pCiv.valueList.add("korean");
			pCiv.valueList.add("italian");
			pCiv.valueList.add("indian");
			pCiv.valueList.add("incan");
			pCiv.valueList.add("magyar");
			pCiv.valueList.add("slavic");
			pCiv.valueList.add("portuguese");
			pCiv.valueList.add("ethiopian");
			pCiv.valueList.add("malian");
			pCiv.valueList.add("berbers");
			pCiv.valueList.add("khmer");
			pCiv.valueList.add("malay");
			pCiv.valueList.add("burmese");
			pCiv.valueList.add("vietnamese");
			pCiv.valueList.add("bulgarians");
			pCiv.valueList.add("tatars");
			pCiv.valueList.add("cumans");
			pCiv.valueList.add("lithuanians");
			pCiv.valueList.add("burgundians");
			pCiv.valueList.add("sicilians");
			pCiv.valueList.add("poles");
			pCiv.valueList.add("bohemians");
			pCiv.valueList.add("dravidians");
			pCiv.valueList.add("bengalis");
			pCiv.valueList.add("gurjaras");
			pCiv.valueList.add("romans");
			pCiv.valueList.add("armenians");
			pCiv.valueList.add("georgians");
			pClassId.valueList.add("all-units-class");
			pClassId.valueList.add("archery-class");
			pClassId.valueList.add("monument-class");
			pClassId.valueList.add("trade-cog-class");
			pClassId.valueList.add("building-class");
			pClassId.valueList.add("villager-class");
			pClassId.valueList.add("ocean-fish-class");
			pClassId.valueList.add("infantry-class");
			pClassId.valueList.add("forage-class");
			pClassId.valueList.add("stone-mine-class");
			pClassId.valueList.add("prey-animal-class");
			pClassId.valueList.add("predator-animal-class");
			pClassId.valueList.add("miscellaneous-class");
			pClassId.valueList.add("cavalry-class");
			pClassId.valueList.add("siege-weapon-class");
			pClassId.valueList.add("terrain-class");
			pClassId.valueList.add("tree-class");
			pClassId.valueList.add("monastery-class");
			pClassId.valueList.add("trade-cart-class");
			pClassId.valueList.add("transport-ship-class");
			pClassId.valueList.add("fishing-ship-class");
			pClassId.valueList.add("warship-class");
			pClassId.valueList.add("cavalry-cannon-class");
			pClassId.valueList.add("wall-class");
			pClassId.valueList.add("flag-class");
			pClassId.valueList.add("gold-mine-class");
			pClassId.valueList.add("shore-fish-class");
			pClassId.valueList.add("petard-class");
			pClassId.valueList.add("cavalry-archer-class");
			pClassId.valueList.add("gate-class");
			pClassId.valueList.add("relic-class");
			pClassId.valueList.add("monk-with-relic-class");
			pClassId.valueList.add("archery-cannon-class");
			pClassId.valueList.add("scout-cavalry-class");
			pClassId.valueList.add("farm-class");
			pClassId.valueList.add("packed-trebuchet-class");
			pClassId.valueList.add("tower-class");
			pClassId.valueList.add("unpacked-trebuchet-class");
			pClassId.valueList.add("scorpion-class");
			pClassId.valueList.add("livestock-class");
			pClassId.valueList.add("king-class");
			pCmdId.valueList.add("cmdid-flag");
			pCmdId.valueList.add("cmdid-livestock-gaia");
			pCmdId.valueList.add("cmdid-civilian-building");
			pCmdId.valueList.add("cmdid-villager");
			pCmdId.valueList.add("cmdid-military");
			pCmdId.valueList.add("cmdid-trade");
			pCmdId.valueList.add("cmdid-monk");
			pCmdId.valueList.add("cmdid-transport");
			pCmdId.valueList.add("cmdid-relic");
			pCmdId.valueList.add("cmdid-fishing-ship");
			pCmdId.valueList.add("cmdid-military-building");
			pCommodity.valueList.add("food");
			pCommodity.valueList.add("wood");
			pCommodity.valueList.add("stone");
			pDifficulty.valueList.add("extreme");
			pDifficulty.valueList.add("hardest");
			pDifficulty.valueList.add("hard");
			pDifficulty.valueList.add("moderate");
			pDifficulty.valueList.add("easy");
			pDifficulty.valueList.add("easiest");
			pDiffParameterId.valueList.add("ability-to-maintain-distance");
			pDiffParameterId.valueList.add("ability-to-dodge-missiles");
			pDUCAction.valueList.add("action-default");
			pDUCAction.valueList.add("action-move");
			pDUCAction.valueList.add("action-patrol");
			pDUCAction.valueList.add("action-guard");
			pDUCAction.valueList.add("action-follow");
			pDUCAction.valueList.add("action-stop");
			pDUCAction.valueList.add("action-ground");
			pDUCAction.valueList.add("action-garrison");
			pDUCAction.valueList.add("action-delete");
			pDUCAction.valueList.add("action-unload");
			pDUCAction.valueList.add("action-train");
			pDUCAction.valueList.add("action-gather");
			pDUCAction.valueList.add("action-lock");
			pDUCAction.valueList.add("action-work");
			pDUCAction.valueList.add("action-ungarrison");
			pDUCAction.valueList.add("action-drop-relic");
			pDUCAction.valueList.add("action-pack");
			pDUCAction.valueList.add("action-unpack");
			pDUCAction.valueList.add("action-none");
			pDUCAction.valueList.add("action-attack-move");
			pDUCAction.valueList.add("action-transform");
			pEffectId.valueList.add("effect-set-attribute");
			pEffectId.valueList.add("effect-mod-resource");
			pEffectId.valueList.add("effect-enable-object");
			pEffectId.valueList.add("effect-upgrade-unit");
			pEffectId.valueList.add("effect-add-attribute");
			pEffectId.valueList.add("effect-mul-attribute");
			pEffectId.valueList.add("effect-mul-resource");
			pEffectId.valueList.add("effect-enable-tech");
			pEffectId.valueList.add("effect-modify-tech");
			pEffectId.valueList.add("effect-set-player-data");
			pEventType.valueList.add("trigger");
			pExploredState.valueList.add("explored-no");
			pExploredState.valueList.add("explored-active");
			pExploredState.valueList.add("explored-yes");
			pFactId.valueList.add("game-time");
			pFactId.valueList.add("population-cap");
			pFactId.valueList.add("population-headroom");
			pFactId.valueList.add("housing-headroom");
			pFactId.valueList.add("idle-farm-count");
			pFactId.valueList.add("food-amount");
			pFactId.valueList.add("wood-amount");
			pFactId.valueList.add("stone-amount");
			pFactId.valueList.add("gold-amount");
			pFactId.valueList.add("escrow-amount");
			pFactId.valueList.add("commodity-buying-price");
			pFactId.valueList.add("commodity-selling-price");
			pFactId.valueList.add("dropsite-min-distance");
			pFactId.valueList.add("soldier-count");
			pFactId.valueList.add("attack-soldier-count");
			pFactId.valueList.add("defend-soldier-count");
			pFactId.valueList.add("warboat-count");
			pFactId.valueList.add("attack-warboat-count");
			pFactId.valueList.add("defend-warboat-count");
			pFactId.valueList.add("current-age");
			pFactId.valueList.add("current-score");
			pFactId.valueList.add("civilization");
			pFactId.valueList.add("player-number");
			pFactId.valueList.add("player-in-game");
			pFactId.valueList.add("unit-count");
			pFactId.valueList.add("unit-type-count");
			pFactId.valueList.add("unit-type-count-total");
			pFactId.valueList.add("building-count");
			pFactId.valueList.add("building-type-count");
			pFactId.valueList.add("building-type-count-total");
			pFactId.valueList.add("population");
			pFactId.valueList.add("military-population");
			pFactId.valueList.add("civilian-population");
			pFactId.valueList.add("random-number");
			pFactId.valueList.add("resource-amount");
			pFactId.valueList.add("player-distance");
			pFactId.valueList.add("allied-goal");
			pFactId.valueList.add("allied-sn");
			pFactId.valueList.add("resource-percent");
			pFactId.valueList.add("enemy-buildings-in-town");
			pFactId.valueList.add("enemy-units-in-town");
			pFactId.valueList.add("enemy-villagers-in-town");
			pFactId.valueList.add("players-in-game");
			pFactId.valueList.add("defender-count");
			pFactId.valueList.add("building-type-in-town");
			pFactId.valueList.add("unit-type-in-town");
			pFactId.valueList.add("villager-type-in-town");
			pFactId.valueList.add("gaia-type-count");
			pFactId.valueList.add("gaia-type-count-total");
			pFactId.valueList.add("cc-gaia-type-count");
			pFactId.valueList.add("current-age-time");
			pFactId.valueList.add("timer-status");
			pFactId.valueList.add("players-tribute");
			pFactId.valueList.add("players-tribute-memory");
			pFactId.valueList.add("treaty-time");
			pFindPlayerMethod.valueList.add("find-attacker");
			pFindPlayerMethod.valueList.add("find-random");
			pFindPlayerMethod.valueList.add("find-closest");
			pFindPlayerMethod.valueList.add("find-ordered");
			pFormation.valueList.add("formation-unchanged");
			pFormation.valueList.add("formation-line");
			pFormation.valueList.add("formation-box");
			pFormation.valueList.add("formation-stagger");
			pFormation.valueList.add("formation-flank");
			pGameType.valueList.add("random-map");
			pGameType.valueList.add("regicide");
			pGameType.valueList.add("death-match");
			pGameType.valueList.add("scenario");
			pGameType.valueList.add("king-of-the-hill");
			pGameType.valueList.add("wonder-race");
			pGameType.valueList.add("defend-the-wonder");
			pGameType.valueList.add("turbo-random-map");
			pGameType.valueList.add("capture-the-relic");
			pGameType.valueList.add("sudden-death");
			pGameType.valueList.add("battle-royale");
			pGameType.valueList.add("empire-wars");
			pGroupType.valueList.add("group-type-land-attack");
			pGroupType.valueList.add("group-type-land-explore");
			pGroupType.valueList.add("group-type-water-attack");
			pGroupType.valueList.add("group-type-water-explore");
			pGroupType.valueList.add("group-type-transport-ship");
			pGroupType.valueList.add("group-type-fishing-ship");
			pGroupType.valueList.add("group-type-water-trade");
			pGroupType.valueList.add("group-type-forward-builder");
			pGroupType.valueList.add("group-type-monk");
			pGroupType.valueList.add("group-type-land-trade");
			pGuardFlag.valueList.add("guard-flag-victory");
			pGuardFlag.valueList.add("guard-flag-resource");
			pGuardFlag.valueList.add("guard-flag-inverse");
			pIdleType.valueList.add("idle-type-villager");
			pIdleType.valueList.add("idle-type-trade-cart");
			pIdleType.valueList.add("idle-type-fishing-ship");
			pIdleType.valueList.add("idle-type-trade-cog");
			pLineId.valueList.add("stone-wall-line");
			pLineId.valueList.add("watch-tower-line");
			pLineId.valueList.add("archer-line");
			pLineId.valueList.add("cavalry-archer-line");
			pLineId.valueList.add("skirmisher-line");
			pLineId.valueList.add("militiaman-line");
			pLineId.valueList.add("spearman-line");
			pLineId.valueList.add("demolition-ship-line");
			pLineId.valueList.add("fire-ship-line");
			pLineId.valueList.add("galley-line");
			pLineId.valueList.add("battering-ram-line");
			pLineId.valueList.add("mangonel-line");
			pLineId.valueList.add("scorpion-line");
			pLineId.valueList.add("camel-line");
			pLineId.valueList.add("knight-line");
			pLineId.valueList.add("scout-cavalry-line");
			pLineId.valueList.add("cannon-galleon-line");
			pLineId.valueList.add("longboat-line");
			pLineId.valueList.add("turtle-ship-line");
			pLineId.valueList.add("berserk-line");
			pLineId.valueList.add("cataphract-line");
			pLineId.valueList.add("chu-ko-nu-line");
			pLineId.valueList.add("huskarl-line");
			pLineId.valueList.add("janissary-line");
			pLineId.valueList.add("longbowman-line");
			pLineId.valueList.add("mameluke-line");
			pLineId.valueList.add("mangudai-line");
			pLineId.valueList.add("samurai-line");
			pLineId.valueList.add("teutonic-knight-line");
			pLineId.valueList.add("throwing-axeman-line");
			pLineId.valueList.add("war-elephant-line");
			pLineId.valueList.add("war-wagon-line");
			pLineId.valueList.add("woad-raider-line");
			pLineId.valueList.add("jaguar-man-line");
			pLineId.valueList.add("eagle-warrior-line");
			pLineId.valueList.add("plumed-archer-line");
			pLineId.valueList.add("tarkan-line");
			pLineId.valueList.add("conquistador-line");
			pLineId.valueList.add("camel-archer-line");
			pLineId.valueList.add("genoese-crossbowman-line");
			pLineId.valueList.add("elephant-archer-line");
			pLineId.valueList.add("boyar-line");
			pLineId.valueList.add("magyar-huszar-line");
			pLineId.valueList.add("kamayuk-line");
			pLineId.valueList.add("caravel-line");
			pLineId.valueList.add("organ-gun-line");
			pLineId.valueList.add("gbeto-line");
			pLineId.valueList.add("shotel-warrior-line");
			pLineId.valueList.add("genitour-line");
			pLineId.valueList.add("ballista-elephant-line");
			pLineId.valueList.add("rattan-archer-line");
			pLineId.valueList.add("arambai-line");
			pLineId.valueList.add("battle-elephant-line");
			pLineId.valueList.add("karambit-warrior-line");
			pLineId.valueList.add("konnik-line");
			pLineId.valueList.add("krepost-konnik-line");
			pLineId.valueList.add("foot-konnik-line");
			pLineId.valueList.add("leitis-line");
			pLineId.valueList.add("kipchak-line");
			pLineId.valueList.add("keshik-line");
			pLineId.valueList.add("steppe-lancer-line");
			pLineId.valueList.add("coustillier-line");
			pLineId.valueList.add("serjeant-line");
			pLineId.valueList.add("donjon-serjeant-line");
			pLineId.valueList.add("obuch-line");
			pLineId.valueList.add("hussite-wagon-line");
			pLineId.valueList.add("bombard-cannon-line");
			pLineId.valueList.add("urumi-swordsman-line");
			pLineId.valueList.add("ratha-melee-line");
			pLineId.valueList.add("chakram-thrower-line");
			pLineId.valueList.add("armored-elephant-line");
			pLineId.valueList.add("ghulam-line");
			pLineId.valueList.add("shrivamsha-rider-line");
			pLineId.valueList.add("ratha-ranged-line");
			pLineId.valueList.add("donjon-spearman-line");
			pLineId.valueList.add("centurion-line");
			pLineId.valueList.add("composite-bowman-line");
			pLineId.valueList.add("monaspa-line");
			pLineId.valueList.add("qizilbash-warrior-line");
			pMapSize.valueList.add("miniature-map");
			pMapSize.valueList.add("tiny-map, tiny");
			pMapSize.valueList.add("small-map, small");
			pMapSize.valueList.add("medium-map, medium");
			pMapSize.valueList.add("normal-map, normal");
			pMapSize.valueList.add("large-map, large");
			pMapSize.valueList.add("huge-map, giant");
			pMapSize.valueList.add("giant-map");
			pMapSize.valueList.add("massive-map");
			pMapSize.valueList.add("enormous-map");
			pMapSize.valueList.add("colossal-map");
			pMapSize.valueList.add("incredible-map");
			pMapSize.valueList.add("monstrous-map");
			pMapSize.valueList.add("ludicrous-map, ludicrous, ludikris");
			pMapType.valueList.add("scenario-map");
			pMapType.valueList.add("arabia");
			pMapType.valueList.add("archipelago");
			pMapType.valueList.add("baltic");
			pMapType.valueList.add("black-forest");
			pMapType.valueList.add("coastal");
			pMapType.valueList.add("continental");
			pMapType.valueList.add("crater-lake");
			pMapType.valueList.add("fortress");
			pMapType.valueList.add("gold-rush");
			pMapType.valueList.add("highland");
			pMapType.valueList.add("islands");
			pMapType.valueList.add("mediterranean");
			pMapType.valueList.add("migration");
			pMapType.valueList.add("rivers");
			pMapType.valueList.add("team-islands");
			pMapType.valueList.add("scandanavia");
			pMapType.valueList.add("mongolia");
			pMapType.valueList.add("yucatan");
			pMapType.valueList.add("salt-marsh");
			pMapType.valueList.add("arena");
			pMapType.valueList.add("king-of-the-hill");
			pMapType.valueList.add("oasis");
			pMapType.valueList.add("ghost-lake");
			pMapType.valueList.add("nomad");
			pMapType.valueList.add("real-world-spain");
			pMapType.valueList.add("real-world-england");
			pMapType.valueList.add("real-world-midEast");
			pMapType.valueList.add("real-world-texas");
			pMapType.valueList.add("real-world-italy");
			pMapType.valueList.add("real-world-caribbean");
			pMapType.valueList.add("real-world-france");
			pMapType.valueList.add("real-world-jutland");
			pMapType.valueList.add("real-world-nippon");
			pMapType.valueList.add("real-world-byzantium");
			pMapType.valueList.add("custom_map");
			pMapType.valueList.add("acropolis");
			pMapType.valueList.add("budapest");
			pMapType.valueList.add("cenotes");
			pMapType.valueList.add("cityoflakes");
			pMapType.valueList.add("goldenpit");
			pMapType.valueList.add("hideout");
			pMapType.valueList.add("hillfort");
			pMapType.valueList.add("lombardia");
			pMapType.valueList.add("steppe");
			pMapType.valueList.add("valley");
			pMapType.valueList.add("megarandom");
			pMapType.valueList.add("hamburger");
			pMapType.valueList.add("ctr-random");
			pMapType.valueList.add("ctr-monsoon");
			pMapType.valueList.add("ctr-pyramid-descent");
			pMapType.valueList.add("ctr-spiral");
			pMapType.valueList.add("kilimanjaro");
			pMapType.valueList.add("mountain-pass");
			pMapType.valueList.add("nile-delta");
			pMapType.valueList.add("serengeti");
			pMapType.valueList.add("socotra");
			pMapType.valueList.add("real-world-amazon");
			pMapType.valueList.add("real-world-china");
			pMapType.valueList.add("real-world-india");
			pMapType.valueList.add("real-world-madagascar");
			pMapType.valueList.add("real-world-west-africa");
			pMapType.valueList.add("real-world-bohemia");
			pMapType.valueList.add("real-world-earth");
			pMapType.valueList.add("special-map-canyons");
			pMapType.valueList.add("special-map-archipelago");
			pMapType.valueList.add("special-map-enemy-islands");
			pMapType.valueList.add("special-map-far-out");
			pMapType.valueList.add("special-map-front-line");
			pMapType.valueList.add("special-map-inner-circle");
			pMapType.valueList.add("special-map-motherland");
			pMapType.valueList.add("special-map-open-plains");
			pMapType.valueList.add("special-map-ring-of-water");
			pMapType.valueList.add("special-map-snake-pit");
			pMapType.valueList.add("special-map-the-eye");
			pMapType.valueList.add("bog-islands");
			pMapType.valueList.add("mangrove-jungle");
			pMapType.valueList.add("pacific-islands");
			pMapType.valueList.add("sandbank");
			pMapType.valueList.add("water-nomad");
			pMapType.valueList.add("special-map-jungle-islands");
			pMapType.valueList.add("special-map-holy-line");
			pMapType.valueList.add("special-map-border-stones");
			pMapType.valueList.add("special-map-yin-yang");
			pMapType.valueList.add("special-map-jungle-lanes");
			pMapType.valueList.add("golden-swamp");
			pMapType.valueList.add("four-lakes");
			pMapType.valueList.add("land-nomad");
			pMapType.valueList.add("battle-on-the-ice");
			pMapType.valueList.add("el-dorado");
			pMapType.valueList.add("fall-of-axum");
			pMapType.valueList.add("fall-of-rome");
			pMapType.valueList.add("the-majapahit-empire");
			pMapType.valueList.add("amazon-tunnel");
			pMapType.valueList.add("coastal-forest");
			pMapType.valueList.add("african-clearing");
			pMapType.valueList.add("atacama");
			pMapType.valueList.add("seize-the-mountain");
			pMapType.valueList.add("crater");
			pMapType.valueList.add("crossroads");
			pMapType.valueList.add("volcanic-island");
			pMapType.valueList.add("acclivity");
			pMapType.valueList.add("eruption");
			pMapType.valueList.add("frigid-lake");
			pMapType.valueList.add("greenland");
			pMapType.valueList.add("lowland");
			pMapType.valueList.add("marketplace");
			pMapType.valueList.add("meadow");
			pMapType.valueList.add("mountain-range");
			pMapType.valueList.add("northern-isles");
			pMapType.valueList.add("ring-fortress");
			pMapType.valueList.add("runestones");
			pMapType.valueList.add("aftermath");
			pMapType.valueList.add("enclosed");
			pMapType.valueList.add("haboob");
			pMapType.valueList.add("kawasan");
			pMapType.valueList.add("land-madness");
			pMapType.valueList.add("sacred-springs");
			pObjectData.valueList.add("object-data-index");
			pObjectData.valueList.add("object-data-id");
			pObjectData.valueList.add("object-data-type");
			pObjectData.valueList.add("object-data-class");
			pObjectData.valueList.add("object-data-category");
			pObjectData.valueList.add("object-data-cmdid");
			pObjectData.valueList.add("object-data-action");
			pObjectData.valueList.add("object-data-order");
			pObjectData.valueList.add("object-data-target");
			pObjectData.valueList.add("object-data-point-x");
			pObjectData.valueList.add("object-data-point-y");
			pObjectData.valueList.add("object-data-hitpoints");
			pObjectData.valueList.add("object-data-maxhp");
			pObjectData.valueList.add("object-data-range");
			pObjectData.valueList.add("object-data-speed");
			pObjectData.valueList.add("object-data-dropsite");
			pObjectData.valueList.add("object-data-resource");
			pObjectData.valueList.add("object-data-carry");
			pObjectData.valueList.add("object-data-garrisoned");
			pObjectData.valueList.add("object-data-garrison-count");
			pObjectData.valueList.add("object-data-status");
			pObjectData.valueList.add("object-data-player");
			pObjectData.valueList.add("object-data-attack-stance");
			pObjectData.valueList.add("object-data-action-time");
			pObjectData.valueList.add("object-data-target-id");
			pObjectData.valueList.add("object-data-formation-id");
			pObjectData.valueList.add("object-data-patrolling");
			pObjectData.valueList.add("object-data-strike-armor");
			pObjectData.valueList.add("object-data-pierce-armor");
			pObjectData.valueList.add("object-data-base-attack");
			pObjectData.valueList.add("object-data-locked");
			pObjectData.valueList.add("object-data-garrison-id");
			pObjectData.valueList.add("object-data-train-count");
			pObjectData.valueList.add("object-data-tasks-count");
			pObjectData.valueList.add("object-data-attacker-count");
			pObjectData.valueList.add("object-data-attacker-id");
			pObjectData.valueList.add("object-data-under-attack");
			pObjectData.valueList.add("object-data-attack-timer");
			pObjectData.valueList.add("object-data-point-z");
			pObjectData.valueList.add("object-data-precise-x");
			pObjectData.valueList.add("object-data-precise-y");
			pObjectData.valueList.add("object-data-precise-z");
			pObjectData.valueList.add("object-data-researching");
			pObjectData.valueList.add("object-data-tile-position");
			pObjectData.valueList.add("object-data-tile-inverse");
			pObjectData.valueList.add("object-data-distance");
			pObjectData.valueList.add("object-data-precise-distance");
			pObjectData.valueList.add("object-data-full-distance");
			pObjectData.valueList.add("object-data-map-zone-id");
			pObjectData.valueList.add("object-data-on-mainland");
			pObjectData.valueList.add("object-data-idling");
			pObjectData.valueList.add("object-data-move-x");
			pObjectData.valueList.add("object-data-move-y");
			pObjectData.valueList.add("object-data-precise-move-x");
			pObjectData.valueList.add("object-data-precise-move-y");
			pObjectData.valueList.add("object-data-reload-time");
			pObjectData.valueList.add("object-data-next-attack");
			pObjectData.valueList.add("object-data-train-site");
			pObjectData.valueList.add("object-data-train-time");
			pObjectData.valueList.add("object-data-blast-radius");
			pObjectData.valueList.add("object-data-blast-level");
			pObjectData.valueList.add("object-data-progress-type");
			pObjectData.valueList.add("object-data-progress-value");
			pObjectData.valueList.add("object-data-min-range");
			pObjectData.valueList.add("object-data-target-time");
			pObjectData.valueList.add("object-data-heresy");
			pObjectData.valueList.add("object-data-faith");
			pObjectData.valueList.add("object-data-redemption");
			pObjectData.valueList.add("object-data-atonement");
			pObjectData.valueList.add("object-data-theocracy");
			pObjectData.valueList.add("object-data-spies");
			pObjectData.valueList.add("object-data-ballistics");
			pObjectData.valueList.add("object-data-gather-type");
			pObjectData.valueList.add("object-data-language-id");
			pObjectData.valueList.add("object-data-group-flag");
			pObjectData.valueList.add("object-data-hero-flags");
			pObjectData.valueList.add("object-data-hero");
			pObjectData.valueList.add("object-data-auto-heal");
			pObjectData.valueList.add("object-data-no-convert");
			pObjectData.valueList.add("object-data-frame-delay");
			pObjectData.valueList.add("object-data-attack-count");
			pObjectData.valueList.add("object-data-to-precise");
			pObjectData.valueList.add("object-data-base-type");
			pObjectData.valueList.add("object-data-upgrade-type");
			pObjectData.valueList.add("object-data-ownership");
			pObjectData.valueList.add("object-data-capture-flag");
			pObjectData.valueList.add("object-data-charge-attack-type");
			pObjectData.valueList.add("object-data-charge-attack-max");
			pObjectData.valueList.add("object-data-charge-attack-amount");
			pObjectData.valueList.add("object-data-charge-attack-regeneration-rate");
			pObjectData.valueList.add("object-data-charge-attack-event-type");
			pObjectList.valueList.add("list-active");
			pObjectList.valueList.add("list-inactive");
			pObjectStatus.valueList.add("status-pending");
			pObjectStatus.valueList.add("status-ready");
			pObjectStatus.valueList.add("status-resource");
			pObjectStatus.valueList.add("status-down");
			pObjectStatus.valueList.add("status-gather");
			pOrderId.valueList.add("orderid-any");
			pOrderId.valueList.add("orderid-attack");
			pOrderId.valueList.add("orderid-defend");
			pOrderId.valueList.add("orderid-build");
			pOrderId.valueList.add("orderid-heal");
			pOrderId.valueList.add("orderid-convert");
			pOrderId.valueList.add("orderid-explore");
			pOrderId.valueList.add("orderid-stop");
			pOrderId.valueList.add("orderid-runaway");
			pOrderId.valueList.add("orderid-retreat");
			pOrderId.valueList.add("orderid-gather");
			pOrderId.valueList.add("orderid-move");
			pOrderId.valueList.add("orderid-patrol");
			pOrderId.valueList.add("orderid-follow");
			pOrderId.valueList.add("orderid-hunt");
			pOrderId.valueList.add("orderid-transport");
			pOrderId.valueList.add("orderid-trade");
			pOrderId.valueList.add("orderid-evade");
			pOrderId.valueList.add("orderid-enter");
			pOrderId.valueList.add("orderid-repair");
			pOrderId.valueList.add("orderid-train");
			pOrderId.valueList.add("orderid-research");
			pOrderId.valueList.add("orderid-unload");
			pOrderId.valueList.add("orderid-relic");
			pPlacementType.valueList.add("place-normal");
			pPlacementType.valueList.add("place-forward");
			pPlacementType.valueList.add("place-control");
			pPlacementType.valueList.add("place-point");
			pPlayerNumber.valueList.add("any-ally");
			pPlayerNumber.valueList.add("any-computer");
			pPlayerNumber.valueList.add("any-computer-ally");
			pPlayerNumber.valueList.add("any-computer-enemy");
			pPlayerNumber.valueList.add("any-computer-neutral");
			pPlayerNumber.valueList.add("any-enemy");
			pPlayerNumber.valueList.add("any-human");
			pPlayerNumber.valueList.add("any-human-ally");
			pPlayerNumber.valueList.add("any-human-enemy");
			pPlayerNumber.valueList.add("any-human-neutral");
			pPlayerNumber.valueList.add("any-neutral");
			pPlayerNumber.valueList.add("every-ally");
			pPlayerNumber.valueList.add("every-computer");
			pPlayerNumber.valueList.add("every-enemy");
			pPlayerNumber.valueList.add("every-human");
			pPlayerNumber.valueList.add("every-neutral");
			pPlayerNumber.valueList.add("this-any-ally");
			pPlayerNumber.valueList.add("this-any-computer");
			pPlayerNumber.valueList.add("this-any-computer-ally");
			pPlayerNumber.valueList.add("this-any-computer-enemy");
			pPlayerNumber.valueList.add("this-any-computer-neutral");
			pPlayerNumber.valueList.add("this-any-enemy");
			pPlayerNumber.valueList.add("this-any-human");
			pPlayerNumber.valueList.add("this-any-human-ally");
			pPlayerNumber.valueList.add("this-any-human-enemy");
			pPlayerNumber.valueList.add("this-any-human-neutral");
			pPlayerNumber.valueList.add("this-any-neutral");
			pPlayerStance.valueList.add("ally");
			pPlayerStance.valueList.add("neutral");
			pPlayerStance.valueList.add("any");
			pPlayerStance.valueList.add("enemy");
			pPositionType.valueList.add("position-center");
			pPositionType.valueList.add("position-opposite");
			pPositionType.valueList.add("position-corner");
			pPositionType.valueList.add("position-enemy");
			pPositionType.valueList.add("position-border");
			pPositionType.valueList.add("position-mirror");
			pPositionType.valueList.add("position-flank");
			pPositionType.valueList.add("position-zero");
			pPositionType.valueList.add("position-map-size");
			pPositionType.valueList.add("position-self");
			pPositionType.valueList.add("position-target");
			pPositionType.valueList.add("position-focus");
			pPositionType.valueList.add("position-object");
			pPositionType.valueList.add("position-point");
			pProgressType.valueList.add("progress-type-train");
			pProgressType.valueList.add("progress-type-research");
			pProjectileType.valueList.add("projectile-town-center");
			pProjectileType.valueList.add("projectile-castle");
			pProjectileType.valueList.add("projectile-watch-tower");
			pProjectileType.valueList.add("projectile-bombard-tower");
			pProjectileType.valueList.add("projectile-ship");
			pProjectileType.valueList.add("projectile-siege");
			pProjectileType.valueList.add("projectile-fortification");
			pProjectileType.valueList.add("projectile-any");
			pPriorityType.valueList.add("priority-offense");
			pPriorityType.valueList.add("priority-defense");
			pResearchState.valueList.add("research-disabled");
			pResearchState.valueList.add("research-unavailable");
			pResearchState.valueList.add("research-available");
			pResearchState.valueList.add("research-pending");
			pResearchState.valueList.add("research-complete");
			pResearchState.valueList.add("research-queued");
			pResource.valueList.add("food");
			pResource.valueList.add("wood");
			pResource.valueList.add("stone");
			pResource.valueList.add("gold");
			pResource.valueList.add("hunting");
			pResource.valueList.add("boar-hunting");
			pResource.valueList.add("deer-hunting");
			pResource.valueList.add("live-boar");
			pResourceType.valueList.add("food");
			pResourceType.valueList.add("wood");
			pResourceType.valueList.add("stone");
			pResourceType.valueList.add("gold");
			pResourceType.valueList.add("amount-food");
			pResourceType.valueList.add("amount-wood");
			pResourceType.valueList.add("amount-stone");
			pResourceType.valueList.add("amount-gold");
			pResourceType.valueList.add("amount-population-cap");
			pResourceType.valueList.add("amount-religion");
			pResourceType.valueList.add("amount-current-age");
			pResourceType.valueList.add("amount-relics");
			pResourceType.valueList.add("amount-trade-bonus");
			pResourceType.valueList.add("amount-trade-goods");
			pResourceType.valueList.add("amount-trade-production");
			pResourceType.valueList.add("amount-population");
			pResourceType.valueList.add("amount-decay");
			pResourceType.valueList.add("amount-discovery");
			pResourceType.valueList.add("amount-ruins");
			pResourceType.valueList.add("amount-meat");
			pResourceType.valueList.add("amount-berries");
			pResourceType.valueList.add("amount-fish");
			pResourceType.valueList.add("amount-kills");
			pResourceType.valueList.add("amount-research-count");
			pResourceType.valueList.add("amount-exploration");
			pResourceType.valueList.add("amount-convert-priest");
			pResourceType.valueList.add("amount-convert-building");
			pResourceType.valueList.add("amount-building-limit");
			pResourceType.valueList.add("amount-food-limit");
			pResourceType.valueList.add("amount-unit-limit");
			pResourceType.valueList.add("amount-maintenance");
			pResourceType.valueList.add("amount-faith");
			pResourceType.valueList.add("amount-faith-recharge-rate");
			pResourceType.valueList.add("amount-farm-food");
			pResourceType.valueList.add("amount-civilian-population");
			pResourceType.valueList.add("amount-all-techs-achieved");
			pResourceType.valueList.add("amount-military-population");
			pResourceType.valueList.add("amount-conversions");
			pResourceType.valueList.add("amount-wonder");
			pResourceType.valueList.add("amount-razings");
			pResourceType.valueList.add("amount-kill-ratio");
			pResourceType.valueList.add("amount-player-killed");
			pResourceType.valueList.add("amount-tribute-inefficiency");
			pResourceType.valueList.add("amount-gold-bonus");
			pResourceType.valueList.add("amount-town-center-unavailable");
			pResourceType.valueList.add("amount-gold-counter");
			pResourceType.valueList.add("amount-writing");
			pResourceType.valueList.add("amount-monasteries");
			pResourceType.valueList.add("amount-tribute");
			pResourceType.valueList.add("amount-hold-ruins");
			pResourceType.valueList.add("amount-hold-relics");
			pResourceType.valueList.add("amount-ore");
			pResourceType.valueList.add("amount-captured-unit");
			pResourceType.valueList.add("amount-trade-good-quality");
			pResourceType.valueList.add("amount-trade-market-level");
			pResourceType.valueList.add("amount-formations");
			pResourceType.valueList.add("amount-building-housing-rate");
			pResourceType.valueList.add("amount-gather-tax-rate");
			pResourceType.valueList.add("amount-gather-accumulator");
			pResourceType.valueList.add("amount-salvage-decay-rate");
			pResourceType.valueList.add("amount-allow-formations");
			pResourceType.valueList.add("amount-can-convert");
			pResourceType.valueList.add("amount-convert-resistance");
			pResourceType.valueList.add("amount-trade-vig-rate");
			pResourceType.valueList.add("amount-stone-bonus");
			pResourceType.valueList.add("amount-queued-count");
			pResourceType.valueList.add("amount-training-count");
			pResourceType.valueList.add("amount-raider");
			pResourceType.valueList.add("amount-boarding-recharge-rate");
			pResourceType.valueList.add("amount-starting-villagers");
			pResourceType.valueList.add("amount-research-cost-mod");
			pResourceType.valueList.add("amount-research-time-mod");
			pResourceType.valueList.add("amount-convert-boats");
			pResourceType.valueList.add("amount-fish-trap-food");
			pResourceType.valueList.add("amount-heal-rate-modifier");
			pResourceType.valueList.add("amount-heal-range");
			pResourceType.valueList.add("amount-starting-food");
			pResourceType.valueList.add("amount-starting-wood");
			pResourceType.valueList.add("amount-starting-stone");
			pResourceType.valueList.add("amount-starting-gold");
			pResourceType.valueList.add("amount-raider-ability");
			pResourceType.valueList.add("amount-berserker-heal-timer");
			pResourceType.valueList.add("amount-dominant-sheep-control");
			pResourceType.valueList.add("amount-object-cost-summation");
			pResourceType.valueList.add("amount-research-summation");
			pResourceType.valueList.add("amount-relic-income-summation");
			pResourceType.valueList.add("amount-trade-income-summation");
			pResourceType.valueList.add("amount-castle");
			pResourceType.valueList.add("amount-value-killed-by-others");
			pResourceType.valueList.add("amount-value-razed-by-others");
			pResourceType.valueList.add("amount-killed-by-others");
			pResourceType.valueList.add("amount-razed-by-others");
			pResourceType.valueList.add("amount-value-current-units");
			pResourceType.valueList.add("amount-value-current-buildings");
			pResourceType.valueList.add("amount-food-total");
			pResourceType.valueList.add("amount-wood-total");
			pResourceType.valueList.add("amount-stone-total");
			pResourceType.valueList.add("amount-gold-total");
			pResourceType.valueList.add("amount-total-value-of-kills");
			pResourceType.valueList.add("amount-total-tribute-received");
			pResourceType.valueList.add("amount-total-value-of-razings");
			pResourceType.valueList.add("amount-total-castles-built");
			pResourceType.valueList.add("amount-total-wonders-built");
			pResourceType.valueList.add("amount-tribute-score");
			pResourceType.valueList.add("amount-convert-min-adj");
			pResourceType.valueList.add("amount-convert-max-adj");
			pResourceType.valueList.add("amount-convert-resist-min-adj");
			pResourceType.valueList.add("amount-convert-resist-max-adj");
			pResourceType.valueList.add("amount-convert-building-min");
			pResourceType.valueList.add("amount-convert-building-max");
			pResourceType.valueList.add("amount-convert-building-chance");
			pResourceType.valueList.add("amount-spies");
			pResourceType.valueList.add("amount-value-wonders-castles");
			pResourceType.valueList.add("amount-food-score");
			pResourceType.valueList.add("amount-wood-score");
			pResourceType.valueList.add("amount-stone-score");
			pResourceType.valueList.add("amount-gold-score");
			pResourceType.valueList.add("amount-wood-bonus");
			pResourceType.valueList.add("amount-food-bonus");
			pResourceType.valueList.add("amount-relic-rate");
			pResourceType.valueList.add("amount-heresy");
			pResourceType.valueList.add("amount-theocracy");
			pResourceType.valueList.add("amount-crenellations");
			pResourceType.valueList.add("amount-construction-rate-mod");
			pResourceType.valueList.add("amount-hun-wonder-bonus");
			pResourceType.valueList.add("amount-spies-discount");
			pResourceType.valueList.add("amount-feitoria-food-productivity");
			pResourceType.valueList.add("amount-feitoria-wood-productivity");
			pResourceType.valueList.add("amount-feitoria-stone-productivity");
			pResourceType.valueList.add("amount-feitoria-gold-productivity");
			pResourceType.valueList.add("amount-temporary-map-reveal");
			pResourceType.valueList.add("amount-reveal-initial-type");
			pResourceType.valueList.add("amount-elevation-bonus-higher");
			pResourceType.valueList.add("amount-elevation-bonus-lower");
			pResourceType.valueList.add("amount-raiding-productivity");
			pResourceType.valueList.add("amount-mercenary-kipchak-count");
			pResourceType.valueList.add("amount-mercenary-kipchak-limit");
			pResourceType.valueList.add("amount-shepherd-productivity");
			pResourceType.valueList.add("amount-shared-line-of-sight");
			pResourceType.valueList.add("amount-feudal-town-center-limit");
			pResourceType.valueList.add("amount-fishing-productivity");
			pResourceType.valueList.add("amount-unused-0");
			pResourceType.valueList.add("amount-monument-food-trickle");
			pResourceType.valueList.add("amount-monument-wood-trickle");
			pResourceType.valueList.add("amount-monument-stone-trickle");
			pResourceType.valueList.add("amount-monument-gold-trickle");
			pResourceType.valueList.add("amount-relic-food-rate");
			pResourceType.valueList.add("amount-villagers-killed-by-gaia");
			pResourceType.valueList.add("amount-villagers-killed-by-animal");
			pResourceType.valueList.add("amount-villagers-killed-by-ai-player");
			pResourceType.valueList.add("amount-villagers-killed-by-human-player");
			pResourceType.valueList.add("amount-food-generation");
			pResourceType.valueList.add("amount-wood-generation");
			pResourceType.valueList.add("amount-stone-generation");
			pResourceType.valueList.add("amount-gold-generation");
			pResourceType.valueList.add("amount-spawn-cap");
			pResourceType.valueList.add("amount-flemish-militia-pop");
			pResourceType.valueList.add("amount-gold-farming-productivity");
			pResourceType.valueList.add("amount-folwark-collection-amount");
			pResourceType.valueList.add("amount-folwark-collection-type");
			pResourceType.valueList.add("amount-building-id");
			pResourceType.valueList.add("amount-units-converted");
			pResourceType.valueList.add("amount-stone-gold-mining-productivity");
			pResourceType.valueList.add("amount-workshop-food-trickle");
			pResourceType.valueList.add("amount-workshop-wood-trickle");
			pResourceType.valueList.add("amount-workshop-stone-trickle");
			pResourceType.valueList.add("amount-workshop-gold-trickle");
			pResourceType.valueList.add("amount-units-value-total");
			pResourceType.valueList.add("amount-buildings-value-total");
			pResourceType.valueList.add("amount-villagers-created-total");
			pResourceType.valueList.add("amount-villagers-idle-periods-total");
			pResourceType.valueList.add("amount-villagers-idle-seconds-total");
			pResourceType.valueList.add("amount-trade-food-percent");
			pResourceType.valueList.add("amount-trade-wood-percent");
			pResourceType.valueList.add("amount-trade-stone-percent");
			pResourceType.valueList.add("amount-livestock-food-productivity");
			pResourceType.valueList.add("amount-speed-up-building-type");
			pResourceType.valueList.add("amount-speed-up-building-range");
			pResourceType.valueList.add("amount-speed-up-percentage");
			pResourceType.valueList.add("amount-speed-up-object-type");
			pResourceType.valueList.add("amount-speed-up-effect-type");
			pResourceType.valueList.add("amount-speed-up-secondary-effect-type");
			pResourceType.valueList.add("amount-speed-up-secondary-percentage");
			pResourceType.valueList.add("amount-civ-name-override");
			pResourceType.valueList.add("amount-starting-scout-id");
			pResourceType.valueList.add("amount-relic-wood-rate");
			pResourceType.valueList.add("amount-relic-stone-rate");
			pResourceType.valueList.add("amount-chopping-gold-productivity");
			pResourceType.valueList.add("amount-foraging-wood-productivity");
			pResourceType.valueList.add("amount-hunting-productivity");
			pResourceType.valueList.add("amount-technology-reward-effect");
			pResourceType.valueList.add("amount-unit-repair-cost");
			pResourceType.valueList.add("amount-building-repair-cost");
			pResourceType.valueList.add("amount-elevation-damage-higher");
			pResourceType.valueList.add("amount-elevation-damage-lower");
			pResourceType.valueList.add("amount-infantry-kill-reward");
			pResourceType.valueList.add("amount-military-can-convert");
			pResourceType.valueList.add("amount-military-conversion-range-adj");
			pResourceType.valueList.add("amount-military-conversion-chance");
			pResourceType.valueList.add("amount-military-conversion-recharge-rate");
			pResourceType.valueList.add("amount-spawn-stay-inside");
			pResourceType.valueList.add("amount-cavalry-kill-reward");
			pResourceType.valueList.add("amount-trigger-shared-visibility");
			pResourceType.valueList.add("amount-trigger-shared-exploration");
			pResourceType.valueList.add("amount-gaia-kills");
			pResourceType.valueList.add("amount-player1-kills");
			pResourceType.valueList.add("amount-player2-kills");
			pResourceType.valueList.add("amount-player3-kills");
			pResourceType.valueList.add("amount-player4-kills");
			pResourceType.valueList.add("amount-player5-kills");
			pResourceType.valueList.add("amount-player6-kills");
			pResourceType.valueList.add("amount-player7-kills");
			pResourceType.valueList.add("amount-player8-kills");
			pResourceType.valueList.add("amount-kills-by-gaia");
			pResourceType.valueList.add("amount-kills-by-player1");
			pResourceType.valueList.add("amount-kills-by-player2");
			pResourceType.valueList.add("amount-kills-by-player3");
			pResourceType.valueList.add("amount-kills-by-player4");
			pResourceType.valueList.add("amount-kills-by-player5");
			pResourceType.valueList.add("amount-kills-by-player6");
			pResourceType.valueList.add("amount-kills-by-player7");
			pResourceType.valueList.add("amount-kills-by-player8");
			pResourceType.valueList.add("amount-gaia-razings");
			pResourceType.valueList.add("amount-player1-razings");
			pResourceType.valueList.add("amount-player2-razings");
			pResourceType.valueList.add("amount-player3-razings");
			pResourceType.valueList.add("amount-player4-razings");
			pResourceType.valueList.add("amount-player5-razings");
			pResourceType.valueList.add("amount-player6-razings");
			pResourceType.valueList.add("amount-player7-razings");
			pResourceType.valueList.add("amount-player8-razings");
			pResourceType.valueList.add("amount-razings-by-gaia");
			pResourceType.valueList.add("amount-razings-by-player1");
			pResourceType.valueList.add("amount-razings-by-player2");
			pResourceType.valueList.add("amount-razings-by-player3");
			pResourceType.valueList.add("amount-razings-by-player4");
			pResourceType.valueList.add("amount-razings-by-player5");
			pResourceType.valueList.add("amount-razings-by-player6");
			pResourceType.valueList.add("amount-razings-by-player7");
			pResourceType.valueList.add("amount-razings-by-player8");
			pResourceType.valueList.add("amount-gaia-kill-value");
			pResourceType.valueList.add("amount-player1-kill-value");
			pResourceType.valueList.add("amount-player2-kill-value");
			pResourceType.valueList.add("amount-player3-kill-value");
			pResourceType.valueList.add("amount-player4-kill-value");
			pResourceType.valueList.add("amount-player5-kill-value");
			pResourceType.valueList.add("amount-player6-kill-value");
			pResourceType.valueList.add("amount-player7-kill-value");
			pResourceType.valueList.add("amount-player8-kill-value");
			pResourceType.valueList.add("amount-gaia-razing-value");
			pResourceType.valueList.add("amount-player1-razing-value");
			pResourceType.valueList.add("amount-player2-razing-value");
			pResourceType.valueList.add("amount-player3-razing-value");
			pResourceType.valueList.add("amount-player4-razing-value");
			pResourceType.valueList.add("amount-player5-razing-value");
			pResourceType.valueList.add("amount-player6-razing-value");
			pResourceType.valueList.add("amount-player7-razing-value");
			pResourceType.valueList.add("amount-player8-razing-value");
			pResourceType.valueList.add("amount-gaia-tribute");
			pResourceType.valueList.add("amount-player1-tribute");
			pResourceType.valueList.add("amount-player2-tribute");
			pResourceType.valueList.add("amount-player3-tribute");
			pResourceType.valueList.add("amount-player4-tribute");
			pResourceType.valueList.add("amount-player5-tribute");
			pResourceType.valueList.add("amount-player6-tribute");
			pResourceType.valueList.add("amount-player7-tribute");
			pResourceType.valueList.add("amount-player8-tribute");
			pResourceType.valueList.add("amount-tribute-from-gaia");
			pResourceType.valueList.add("amount-tribute-from-player1");
			pResourceType.valueList.add("amount-tribute-from-player2");
			pResourceType.valueList.add("amount-tribute-from-player3");
			pResourceType.valueList.add("amount-tribute-from-player4");
			pResourceType.valueList.add("amount-tribute-from-player5");
			pResourceType.valueList.add("amount-tribute-from-player6");
			pResourceType.valueList.add("amount-tribute-from-player7");
			pResourceType.valueList.add("amount-tribute-from-player8");
			pScoutMethod.valueList.add("scout-center");
			pScoutMethod.valueList.add("scout-opposite");
			pScoutMethod.valueList.add("scout-corner");
			pScoutMethod.valueList.add("scout-enemy");
			pScoutMethod.valueList.add("scout-border");
			pScoutMethod.valueList.add("scout-mirror");
			pScoutMethod.valueList.add("scout-flank");
			pSearchOrder.valueList.add("search-order-none");
			pSearchOrder.valueList.add("search-order-asc");
			pSearchOrder.valueList.add("search-order-desc");
			pSearchSource.valueList.add("search-local");
			pSearchSource.valueList.add("search-remote");
			pSetId.valueList.add("monk-set");
			pSetId.valueList.add("trebuchet-set");
			pSetId.valueList.add("huskarl-set");
			pSetId.valueList.add("villager-shepherd");
			pSetId.valueList.add("villager-forager");
			pSetId.valueList.add("villager-farmer");
			pSetId.valueList.add("villager-hunter");
			pSetId.valueList.add("villager-fisherman");
			pSetId.valueList.add("villager-food");
			pSetId.valueList.add("villager-wood");
			pSetId.valueList.add("villager-stone");
			pSetId.valueList.add("villager-gold");
			pSetId.valueList.add("villager-builder");
			pSetId.valueList.add("villager-repairer");
			pSetId.valueList.add("villager-base");
			pSetId.valueList.add("tarkan-set");
			pSetId.valueList.add("konnik-set");
			pSetId.valueList.add("kipchak-set");
			pSetId.valueList.add("serjeant-set");
			pSetId.valueList.add("flemish-militia-set");
			pSetId.valueList.add("ratha-set");
			pStartingResources.valueList.add("low-resources");
			pStartingResources.valueList.add("medium-resources");
			pStartingResources.valueList.add("high-resources");
			pStartingResources.valueList.add("ultra-high-resources");
			pStartingResources.valueList.add("infinite-resources");
			pStartingResources.valueList.add("random-resources");
			pSubGameType.valueList.add("sub-game-type-empire-wars");
			pSubGameType.valueList.add("sub-game-type-sudden-death");
			pSubGameType.valueList.add("sub-game-type-regicide");
			pSubGameType.valueList.add("sub-game-type-king-of-the-hill");
			pTerrain.valueList.add("terrain-grass");
			pTerrain.valueList.add("terrain-water");
			pTerrain.valueList.add("terrain-water-beach");
			pTerrain.valueList.add("terrain-dirt3");
			pTerrain.valueList.add("terrain-shallows");
			pTerrain.valueList.add("terrain-leaves");
			pTerrain.valueList.add("terrain-dirt");
			pTerrain.valueList.add("terrain-farm");
			pTerrain.valueList.add("terrain-farm-dead");
			pTerrain.valueList.add("terrain-grass3");
			pTerrain.valueList.add("terrain-forest");
			pTerrain.valueList.add("terrain-dirt2");
			pTerrain.valueList.add("terrain-grass2");
			pTerrain.valueList.add("terrain-forest-palm");
			pTerrain.valueList.add("terrain-desert");
			pTerrain.valueList.add("terrain-water-old");
			pTerrain.valueList.add("terrain-grass-old");
			pTerrain.valueList.add("terrain-forest-jungle");
			pTerrain.valueList.add("terrain-forest-bamboo");
			pTerrain.valueList.add("terrain-forest-pine");
			pTerrain.valueList.add("terrain-forest-oak");
			pTerrain.valueList.add("terrain-forest-snow");
			pTerrain.valueList.add("terrain-water-deep");
			pTerrain.valueList.add("terrain-water-medium");
			pTerrain.valueList.add("terrain-road");
			pTerrain.valueList.add("terrain-road-broken");
			pTerrain.valueList.add("terrain-ice");
			pTerrain.valueList.add("terrain-foundation");
			pTerrain.valueList.add("terrain-water-bridge");
			pTerrain.valueList.add("terrain-farm1");
			pTerrain.valueList.add("terrain-farm2");
			pTerrain.valueList.add("terrain-farm3");
			pTerrain.valueList.add("terrain-snow");
			pTerrain.valueList.add("terrain-dirt-snow");
			pTerrain.valueList.add("terrain-grass-snow");
			pTerrain.valueList.add("terrain-ice2");
			pTerrain.valueList.add("terrain-foundation-snow");
			pTerrain.valueList.add("terrain-ice-beach");
			pTerrain.valueList.add("terrain-road-snow");
			pTerrain.valueList.add("terrain-road-fungus");
			pTerrain.valueList.add("terrain-koh");
			pTerrain.valueList.add("terrain-unknown");
			pTimerState.valueList.add("timer-disabled");
			pTimerState.valueList.add("timer-triggered");
			pTimerState.valueList.add("timer-running");
			pUnitId.valueList.add("archer-line");
			pUnitId.valueList.add("cavalry-archer-line");
			pUnitId.valueList.add("skirmisher-line");
			pUnitId.valueList.add("militiaman-line");
			pUnitId.valueList.add("spearman-line");
			pUnitId.valueList.add("demolition-ship-line");
			pUnitId.valueList.add("fire-ship-line");
			pUnitId.valueList.add("galley-line");
			pUnitId.valueList.add("battering-ram-line");
			pUnitId.valueList.add("mangonel-line");
			pUnitId.valueList.add("scorpion-line");
			pUnitId.valueList.add("camel-line");
			pUnitId.valueList.add("knight-line");
			pUnitId.valueList.add("scout-cavalry-line");
			pUnitId.valueList.add("cannon-galleon-line");
			pUnitId.valueList.add("longboat-line");
			pUnitId.valueList.add("turtle-ship-line");
			pUnitId.valueList.add("berserk-line");
			pUnitId.valueList.add("cataphract-line");
			pUnitId.valueList.add("chu-ko-nu-line");
			pUnitId.valueList.add("huskarl-line");
			pUnitId.valueList.add("janissary-line");
			pUnitId.valueList.add("longbowman-line");
			pUnitId.valueList.add("mameluke-line");
			pUnitId.valueList.add("mangudai-line");
			pUnitId.valueList.add("samurai-line");
			pUnitId.valueList.add("teutonic-knight-line");
			pUnitId.valueList.add("throwing-axeman-line");
			pUnitId.valueList.add("war-elephant-line");
			pUnitId.valueList.add("war-wagon-line");
			pUnitId.valueList.add("woad-raider-line");
			pUnitId.valueList.add("jaguar-man-line");
			pUnitId.valueList.add("eagle-warrior-line");
			pUnitId.valueList.add("plumed-archer-line");
			pUnitId.valueList.add("tarkan-line");
			pUnitId.valueList.add("conquistador-line");
			pUnitId.valueList.add("camel-archer-line");
			pUnitId.valueList.add("genoese-crossbowman-line");
			pUnitId.valueList.add("elephant-archer-line");
			pUnitId.valueList.add("boyar-line");
			pUnitId.valueList.add("magyar-huszar-line");
			pUnitId.valueList.add("kamayuk-line");
			pUnitId.valueList.add("caravel-line");
			pUnitId.valueList.add("organ-gun-line");
			pUnitId.valueList.add("gbeto-line");
			pUnitId.valueList.add("shotel-warrior-line");
			pUnitId.valueList.add("genitour-line");
			pUnitId.valueList.add("ballista-elephant-line");
			pUnitId.valueList.add("rattan-archer-line");
			pUnitId.valueList.add("arambai-line");
			pUnitId.valueList.add("battle-elephant-line");
			pUnitId.valueList.add("karambit-warrior-line");
			pUnitId.valueList.add("konnik-line");
			pUnitId.valueList.add("krepost-konnik-line");
			pUnitId.valueList.add("foot-konnik-line");
			pUnitId.valueList.add("leitis-line");
			pUnitId.valueList.add("kipchak-line");
			pUnitId.valueList.add("keshik-line");
			pUnitId.valueList.add("steppe-lancer-line");
			pUnitId.valueList.add("coustillier-line");
			pUnitId.valueList.add("serjeant-line");
			pUnitId.valueList.add("donjon-serjeant-line");
			pUnitId.valueList.add("obuch-line");
			pUnitId.valueList.add("hussite-wagon-line");
			pUnitId.valueList.add("bombard-cannon-line");
			pUnitId.valueList.add("urumi-swordsman-line");
			pUnitId.valueList.add("ratha-melee-line");
			pUnitId.valueList.add("chakram-thrower-line");
			pUnitId.valueList.add("armored-elephant-line");
			pUnitId.valueList.add("ghulam-line");
			pUnitId.valueList.add("shrivamsha-rider-line");
			pUnitId.valueList.add("ratha-ranged-line");
			pUnitId.valueList.add("donjon-spearman-line");
			pUnitId.valueList.add("centurion-line");
			pUnitId.valueList.add("composite-bowman-line");
			pUnitId.valueList.add("monaspa-line");
			pUnitId.valueList.add("qizilbash-warrior-line");
			pVictoryCondition.valueList.add("standard");
			pVictoryCondition.valueList.add("conquest");
			pVictoryCondition.valueList.add("time-limit");
			pVictoryCondition.valueList.add("score");
			pVictoryCondition.valueList.add("custom");
			pWallId.valueList.add("palisade-wall");
			pWallId.valueList.add("stone-wall");
			pWallId.valueList.add("fortified-wall");
			pWallId.valueList.add("stone-wall-line");

//																		Added from the objectsBuildingsArray array:
//																	Added from the objectsBuildingsArray array:
//																															Added from the objectsBuildingsArray array:
//																							Added from the objectsBuildingsArray array:
			pBuildingId.valueList.add("town-center");
			pBuildingId.valueList.add("town-center-foundation");
			pBuildingId.valueList.add("house");
			pBuildingId.valueList.add("mill");
			pBuildingId.valueList.add("mining-camp");
			pBuildingId.valueList.add("lumber-camp");
			pBuildingId.valueList.add("mule-cart");
			pBuildingId.valueList.add("dock");
			pBuildingId.valueList.add("fish-trap");
			pBuildingId.valueList.add("farm");
			pBuildingId.valueList.add("blacksmith");
			pBuildingId.valueList.add("market");
			pBuildingId.valueList.add("monastery");
			pBuildingId.valueList.add("university");
			pBuildingId.valueList.add("wonder");
			pBuildingId.valueList.add("fortified-church");
			pBuildingId.valueList.add("caravanserai");
			pBuildingId.valueList.add("feitoria");
			pBuildingId.valueList.add("barracks");
			pBuildingId.valueList.add("archery-range");
			pBuildingId.valueList.add("stable");
			pBuildingId.valueList.add("siege-workshop");
			pBuildingId.valueList.add("outpost");
			pBuildingId.valueList.add("palisade-wall");
			pBuildingId.valueList.add("stone-wall");
			pBuildingId.valueList.add("fortified-wall");
			pBuildingId.valueList.add("watch-tower");
			pBuildingId.valueList.add("guard-tower");
			pBuildingId.valueList.add("keep");
			pBuildingId.valueList.add("bombard-tower");
			pBuildingId.valueList.add("castle");
			pBuildingId.valueList.add("krepost");
			pBuildingId.valueList.add("donjon");
			pBuildingId.valueList.add("gate-ascending-closed");
			pBuildingId.valueList.add("gate-ascending-open");
			pBuildingId.valueList.add("gate,<br>gate-ascending");
			pBuildingId.valueList.add("gate-descending-closed");
			pBuildingId.valueList.add("gate-descending");
			pBuildingId.valueList.add("gate-horizontal-closed");
			pBuildingId.valueList.add("gate-horizontal-open");
			pBuildingId.valueList.add("gate-horizontal-open");
			pBuildingId.valueList.add("gate-horizontal");
			pBuildingId.valueList.add("gate-vertical-closed");
			pBuildingId.valueList.add("gate-vertical-open");
			pBuildingId.valueList.add("gate-vertical-open");
			pBuildingId.valueList.add("gate-vertical");

//	Added from the Tech array:
//Added from the Tech array:
//														Added from the Tech array:
//						Added from the Tech array:

			pTechId.valueList.add("ri-crossbow");
			pTechId.valueList.add("ri-elite-skirmisher");
			pTechId.valueList.add("ri-arbalest");
			pTechId.valueList.add("ri-heavy-cavalry-archer");
			pTechId.valueList.add("ri-hand-cannon");
			pTechId.valueList.add("ri-imperial-skirmisher");
			pTechId.valueList.add("ri-elite-genitour");
			pTechId.valueList.add("ri-elite-elephant-archer");
			pTechId.valueList.add("ri-thumb-ring");
			pTechId.valueList.add("ri-parthian-tactics");
			pTechId.valueList.add("ri-man-at-arms");
			pTechId.valueList.add("ri-long-swordsman");
			pTechId.valueList.add("ri-pikeman");
			pTechId.valueList.add("ri-eagle-warrior");
			pTechId.valueList.add("ri-two-handed-swordsman");
			pTechId.valueList.add("ri-champion");
			pTechId.valueList.add("ri-legionary");
			pTechId.valueList.add("ri-halberdier");
			pTechId.valueList.add("ri-elite-eagle-warrior");
			pTechId.valueList.add("ri-supplies");
			pTechId.valueList.add("ri-gambesons");
			pTechId.valueList.add("ri-tracking");
			pTechId.valueList.add("ri-squires");
			pTechId.valueList.add("ri-arson");
			pTechId.valueList.add("ri-forging");
			pTechId.valueList.add("ri-fletching");
			pTechId.valueList.add("ri-scale-mail");
			pTechId.valueList.add("ri-padded-archer-armor");
			pTechId.valueList.add("ri-scale-barding");
			pTechId.valueList.add("ri-iron-casting");
			pTechId.valueList.add("ri-bodkin-arrow");
			pTechId.valueList.add("ri-chain-mail");
			pTechId.valueList.add("ri-leather-archer-armor");
			pTechId.valueList.add("ri-chain-barding");
			pTechId.valueList.add("ri-blast-furnace");
			pTechId.valueList.add("ri-bracer");
			pTechId.valueList.add("ri-plate-mail");
			pTechId.valueList.add("ri-ring-archer-armor");
			pTechId.valueList.add("ri-plate-barding");
			pTechId.valueList.add("ri-conscription");
			pTechId.valueList.add("ri-hoardings");
			pTechId.valueList.add("ri-sappers");
			pTechId.valueList.add("ri-elite-composite-bowman");
			pTechId.valueList.add("ri-cilician-fleet");
			pTechId.valueList.add("ri-fereters");
			pTechId.valueList.add("ri-elite-jaguar-man");
			pTechId.valueList.add("ri-atlatl");
			pTechId.valueList.add("ri-elite-ratha");
			pTechId.valueList.add("ri-paiks");
			pTechId.valueList.add("ri-mahayana");
			pTechId.valueList.add("ri-elite-camel-archer");
			pTechId.valueList.add("ri-kasbah");
			pTechId.valueList.add("ri-maghrebi-camels");
			pTechId.valueList.add("ri-elite-hussite-wagon");
			pTechId.valueList.add("ri-wagenburg-tactics");
			pTechId.valueList.add("ri-hussite-reforms");
			pTechId.valueList.add("ri-elite-longbowman");
			pTechId.valueList.add("ri-warwolf");
			pTechId.valueList.add("ri-elite-konnik");
			pTechId.valueList.add("ri-stirrups");
			pTechId.valueList.add("ri-bagains");
			pTechId.valueList.add("ri-elite-coustillier");
			pTechId.valueList.add("ri-burgundian-vineyards");
			pTechId.valueList.add("ri-flemish-revolution");
			pTechId.valueList.add("ri-elite-arambai");
			pTechId.valueList.add("ri-manipur-cavalry");
			pTechId.valueList.add("ri-howdah");
			pTechId.valueList.add("ri-elite-cataphract");
			pTechId.valueList.add("ri-greek-fire");
			pTechId.valueList.add("ri-elite-woad-raider");
			pTechId.valueList.add("ri-stronghold");
			pTechId.valueList.add("ri-elite-chu-ko-nu");
			pTechId.valueList.add("ri-great-wall");
			pTechId.valueList.add("ri-elite-kipchak");
			pTechId.valueList.add("ri-steppe-husbandry");
			pTechId.valueList.add("ri-cuman-mercenaries");
			pTechId.valueList.add("ri-elite-urumi-swordsman");
			pTechId.valueList.add("ri-medical-corps");
			pTechId.valueList.add("ri-wootz-steel");
			pTechId.valueList.add("ri-elite-shotel");
			pTechId.valueList.add("ri-royal-heirs");
			pTechId.valueList.add("ri-torsion-engines");
			pTechId.valueList.add("ri-elite-throwing-axeman");
			pTechId.valueList.add("ri-chivalry");
			pTechId.valueList.add("ri-elite-monaspa");
			pTechId.valueList.add("ri-svan-towers");
			pTechId.valueList.add("ri-aznauri-cavalry");
			pTechId.valueList.add("ri-elite-huskarl");
			pTechId.valueList.add("ri-elite-chakram-thrower");
			pTechId.valueList.add("ri-kshatriyas");
			pTechId.valueList.add("ri-frontier-guards");
			pTechId.valueList.add("ri-elite-ghulam");
			pTechId.valueList.add("ri-grand-trunk-road");
			pTechId.valueList.add("ri-shatagni");
			pTechId.valueList.add("ri-elite-tarkan");
			pTechId.valueList.add("ri-marauders");
			pTechId.valueList.add("ri-elite-kamayuk");
			pTechId.valueList.add("ri-andean-sling");
			pTechId.valueList.add("ri-fabric-shields");
			pTechId.valueList.add("ri-elite-elephant-archer");
			pTechId.valueList.add("ri-sultans");
			pTechId.valueList.add("ri-shatagni");
			pTechId.valueList.add("ri-elite-genoese-crossbowman");
			pTechId.valueList.add("ri-pavise");
			pTechId.valueList.add("ri-silk-road");
			pTechId.valueList.add("ri-elite-samurai");
			pTechId.valueList.add("ri-yasama");
			pTechId.valueList.add("ri-elite-ballista-elephant");
			pTechId.valueList.add("ri-tusk-swords");
			pTechId.valueList.add("ri-double-crossbow");
			pTechId.valueList.add("ri-elite-war-wagon");
			pTechId.valueList.add("ri-eupseong");
			pTechId.valueList.add("ri-elite-leitis");
			pTechId.valueList.add("ri-hill-forts");
			pTechId.valueList.add("ri-tower-shields");
			pTechId.valueList.add("ri-elite-magyar-huszar");
			pTechId.valueList.add("ri-corvinian-army");
			pTechId.valueList.add("ri-recurve-bow");
			pTechId.valueList.add("ri-elite-karambit-warrior");
			pTechId.valueList.add("ri-thalassocracy");
			pTechId.valueList.add("ri-forced-levy");
			pTechId.valueList.add("ri-elite-gbeto");
			pTechId.valueList.add("ri-tigui");
			pTechId.valueList.add("ri-farimba");
			pTechId.valueList.add("ri-elite-plumed-archer");
			pTechId.valueList.add("ri-elite-mangudai");
			pTechId.valueList.add("ri-nomads");
			pTechId.valueList.add("ri-elite-war-elephant");
			pTechId.valueList.add("ri-kamandaran");
			pTechId.valueList.add("ri-elite-obuch");
			pTechId.valueList.add("ri-szlachta-privileges");
			pTechId.valueList.add("ri-lechitic-legacy");
			pTechId.valueList.add("ri-elite-organ-gun");
			pTechId.valueList.add("ri-carrack");
			pTechId.valueList.add("ri-arquebus");
			pTechId.valueList.add("ri-elite-centurion");
			pTechId.valueList.add("ri-ballistas");
			pTechId.valueList.add("ri-comitatenses");
			pTechId.valueList.add("ri-elite-mameluke");
			pTechId.valueList.add("ri-counterweights");
			pTechId.valueList.add("ri-elite-serjeant");
			pTechId.valueList.add("ri-first-crusade");
			pTechId.valueList.add("ri-hauberk");
			pTechId.valueList.add("ri-elite-boyar");
			pTechId.valueList.add("ri-detinets");
			pTechId.valueList.add("ri-druzhina");
			pTechId.valueList.add("ri-elite-conquistador");
			pTechId.valueList.add("ri-inquisition");
			pTechId.valueList.add("ri-elite-keshik");
			pTechId.valueList.add("ri-silk-armor");
			pTechId.valueList.add("ri-timurid-siegecraft");
			pTechId.valueList.add("ri-elite-teutonic-knight");
			pTechId.valueList.add("ri-ironclad");
			pTechId.valueList.add("ri-elite-janissary");
			pTechId.valueList.add("ri-sipahi");
			pTechId.valueList.add("ri-elite-rattan-archer");
			pTechId.valueList.add("ri-chatras");
			pTechId.valueList.add("ri-paper-money");
			pTechId.valueList.add("ri-elite-berserk");
			pTechId.valueList.add("ri-chieftains");
			pTechId.valueList.add("ri-war-galley");
			pTechId.valueList.add("ri-galleon");
			pTechId.valueList.add("ri-fast-fire-ship");
			pTechId.valueList.add("ri-heavy-demolition-ship");
			pTechId.valueList.add("ri-cannon-galleon");
			pTechId.valueList.add("ri-deck-guns");
			pTechId.valueList.add("ri-elite-caravel");
			pTechId.valueList.add("ri-elite-longboat");
			pTechId.valueList.add("ri-elite-turtle-ship");
			pTechId.valueList.add("ri-gillnets");
			pTechId.valueList.add("ri-careening");
			pTechId.valueList.add("ri-dry-dock");
			pTechId.valueList.add("ri-shipwright");
			pTechId.valueList.add("ri-double-bit-axe");
			pTechId.valueList.add("ri-bow-saw");
			pTechId.valueList.add("ri-two-man-saw");
			pTechId.valueList.add("ri-cartography");
			pTechId.valueList.add("ri-coinage");
			pTechId.valueList.add("ri-caravan");
			pTechId.valueList.add("ri-banking");
			pTechId.valueList.add("ri-guilds");
			pTechId.valueList.add("ri-horse-collar");
			pTechId.valueList.add("ri-heavy-plow");
			pTechId.valueList.add("ri-crop-rotation");
			pTechId.valueList.add("ri-gold-mining");
			pTechId.valueList.add("ri-stone-mining");
			pTechId.valueList.add("ri-gold-shaft-mining");
			pTechId.valueList.add("ri-stone-shaft-mining");
			pTechId.valueList.add("ri-atonement");
			pTechId.valueList.add("ri-fervor");
			pTechId.valueList.add("ri-heresy");
			pTechId.valueList.add("ri-redemption");
			pTechId.valueList.add("ri-sanctity");
			pTechId.valueList.add("ri-devotion");
			pTechId.valueList.add("ri-block-printing");
			pTechId.valueList.add("ri-faith");
			pTechId.valueList.add("ri-illumination");
			pTechId.valueList.add("ri-theocracy");
			pTechId.valueList.add("ri-capped-ram");
			pTechId.valueList.add("ri-siege-ram");
			pTechId.valueList.add("ri-siege-elephant");
			pTechId.valueList.add("ri-onager");
			pTechId.valueList.add("ri-siege-onager");
			pTechId.valueList.add("ri-heavy-scorpion");
			pTechId.valueList.add("ri-bombard-cannon");
			pTechId.valueList.add("ri-houfnice");
			pTechId.valueList.add("ri-light-cavalry");
			pTechId.valueList.add("ri-hussar");
			pTechId.valueList.add("ri-winged-hussar");
			pTechId.valueList.add("ri-cavalier");
			pTechId.valueList.add("ri-paladin");
			pTechId.valueList.add("ri-savar");
			pTechId.valueList.add("ri-heavy-camel");
			pTechId.valueList.add("ri-imperial-camel-rider");
			pTechId.valueList.add("ri-elite-battle-elephant");
			pTechId.valueList.add("ri-elite-steppe-lancer");
			pTechId.valueList.add("ri-elite-shrivamsha-rider");
			pTechId.valueList.add("ri-bloodlines");
			pTechId.valueList.add("ri-husbandry");
			pTechId.valueList.add("ri-loom");
			pTechId.valueList.add("feudal-age");
			pTechId.valueList.add("castle-age");
			pTechId.valueList.add("ri-town-watch");
			pTechId.valueList.add("ri-wheel-barrow");
			pTechId.valueList.add("imperial-age");
			pTechId.valueList.add("ri-town-patrol");
			pTechId.valueList.add("ri-hand-cart");
			pTechId.valueList.add("ri-fortified-wall");
			pTechId.valueList.add("ri-guard-tower");
			pTechId.valueList.add("ri-keep");
			pTechId.valueList.add("ri-bombard-tower");
			pTechId.valueList.add("ri-ballistics");
			pTechId.valueList.add("ri-heated-shot");
			pTechId.valueList.add("ri-masonry");
			pTechId.valueList.add("ri-murder-holes");
			pTechId.valueList.add("ri-stonecutting");
			pTechId.valueList.add("ri-architecture");
			pTechId.valueList.add("ri-arrowslits");
			pTechId.valueList.add("ri-chemistry");
			pTechId.valueList.add("ri-siege-engineers");

			// Added from the Objects array:
			// Added from the Objects array:
			// Added from the Objects array:
			// Added from the Objects array:

			pObjectName.valueList.add("archer");
			pObjectName.valueList.add("crossbowman");
			pObjectName.valueList.add("arbalest");
			pObjectName.valueList.add("skirmisher");
			pObjectName.valueList.add("elite-skirmisher");
			pObjectName.valueList.add("imperial-skirmisher");
			pObjectName.valueList.add("cavalry-archer");
			pObjectName.valueList.add("heavy-cavalry-archer");
			pObjectName.valueList.add("hand-cannoneer");
			pObjectName.valueList.add("slinger");
			pObjectName.valueList.add("genitour");
			pObjectName.valueList.add("elite-genitour");
			pObjectName.valueList.add("elephant-archer");
			pObjectName.valueList.add("elite-elephant-archer");
			pObjectName.valueList.add("militiaman");
			pObjectName.valueList.add("man-at-arms");
			pObjectName.valueList.add("long-swordsman");
			pObjectName.valueList.add("two-handed-swordsman");
			pObjectName.valueList.add("champion");
			pObjectName.valueList.add("legionary");
			pObjectName.valueList.add("spearman");
			pObjectName.valueList.add("pikeman");
			pObjectName.valueList.add("halberdier");
			pObjectName.valueList.add("eagle-warrior");
			pObjectName.valueList.add("heavy-eagle-warrior");
			pObjectName.valueList.add("elite-eagle-warrior");
			pObjectName.valueList.add("condottiero");
			pObjectName.valueList.add("trebuchet");
			pObjectName.valueList.add("petard");
			pObjectName.valueList.add("composite-bowman");
			pObjectName.valueList.add("elite-composite-bowman");
			pObjectName.valueList.add("jaguar-man");
			pObjectName.valueList.add("elite-jaguar-man");
			pObjectName.valueList.add("ratha-ranged");
			pObjectName.valueList.add("ratha-melee");
			pObjectName.valueList.add("elite-ratha-ranged");
			pObjectName.valueList.add("elite-ratha-melee");
			pObjectName.valueList.add("camel-archer");
			pObjectName.valueList.add("elite-camel-archer");
			pObjectName.valueList.add("longbowman");
			pObjectName.valueList.add("elite-longbowman");
			pObjectName.valueList.add("hussite-wagon");
			pObjectName.valueList.add("elite-hussite-wagon");
			pObjectName.valueList.add("konnik");
			pObjectName.valueList.add("elite-konnik");
			pObjectName.valueList.add("foot-konnik");
			pObjectName.valueList.add("elite-foot-konnik");
			pObjectName.valueList.add("coustillier");
			pObjectName.valueList.add("elite-coustillier");
			pObjectName.valueList.add("arambai");
			pObjectName.valueList.add("elite-arambai");
			pObjectName.valueList.add("cataphract");
			pObjectName.valueList.add("elite-cataphract");
			pObjectName.valueList.add("woad-raider");
			pObjectName.valueList.add("elite-woad-raider");
			pObjectName.valueList.add("chu-ko-nu");
			pObjectName.valueList.add("elite-chu-ko-nu");
			pObjectName.valueList.add("kipchak");
			pObjectName.valueList.add("elite-kipchak");
			pObjectName.valueList.add("mercenary-kipchak");
			pObjectName.valueList.add("urumi-swordsman");
			pObjectName.valueList.add("elite-urumi-swordsman");
			pObjectName.valueList.add("shotel-warrior");
			pObjectName.valueList.add("elite-shotel-warrior");
			pObjectName.valueList.add("throwing-axeman");
			pObjectName.valueList.add("elite-throwing-axeman");
			pObjectName.valueList.add("monaspa");
			pObjectName.valueList.add("elite-monaspa");
			pObjectName.valueList.add("huskarl");
			pObjectName.valueList.add("elite-huskarl");
			pObjectName.valueList.add("chakram-thrower");
			pObjectName.valueList.add("elite-chakram-thrower");
			pObjectName.valueList.add("ghulam");
			pObjectName.valueList.add("elite-ghulam");
			pObjectName.valueList.add("tarkan");
			pObjectName.valueList.add("elite-tarkan");
			pObjectName.valueList.add("kamayuk");
			pObjectName.valueList.add("elite-kamayuk");
			pObjectName.valueList.add("elephant-archer");
			pObjectName.valueList.add("elite-elephant-archer");
			pObjectName.valueList.add("genoese-crossbowman");
			pObjectName.valueList.add("elite-genoese-crossbowman");
			pObjectName.valueList.add("samurai");
			pObjectName.valueList.add("elite-samurai");
			pObjectName.valueList.add("ballista-elephant");
			pObjectName.valueList.add("elite-ballista-elephant");
			pObjectName.valueList.add("war-wagon");
			pObjectName.valueList.add("elite-war-wagon");
			pObjectName.valueList.add("leitis");
			pObjectName.valueList.add("elite-leitis");
			pObjectName.valueList.add("magyar-huszar");
			pObjectName.valueList.add("elite-magyar-huszar");
			pObjectName.valueList.add("karambit-warrior");
			pObjectName.valueList.add("elite-karambit-warrior");
			pObjectName.valueList.add("gbeto");
			pObjectName.valueList.add("elite-gbeto");
			pObjectName.valueList.add("plumed-archer");
			pObjectName.valueList.add("elite-plumed-archer");
			pObjectName.valueList.add("mangudai");
			pObjectName.valueList.add("elite-mangudai");
			pObjectName.valueList.add("war-elephant");
			pObjectName.valueList.add("elite-war-elephant");
			pObjectName.valueList.add("obuch");
			pObjectName.valueList.add("elite-obuch");
			pObjectName.valueList.add("organ-gun");
			pObjectName.valueList.add("elite-organ-gun");
			pObjectName.valueList.add("centurion");
			pObjectName.valueList.add("elite-centurion");
			pObjectName.valueList.add("mameluke");
			pObjectName.valueList.add("elite-mameluke");
			pObjectName.valueList.add("serjeant");
			pObjectName.valueList.add("elite-serjeant");
			pObjectName.valueList.add("boyar");
			pObjectName.valueList.add("elite-boyar");
			pObjectName.valueList.add("conquistador");
			pObjectName.valueList.add("elite-conquistador");
			pObjectName.valueList.add("keshik");
			pObjectName.valueList.add("elite-keshik");
			pObjectName.valueList.add("flaming-camel");
			pObjectName.valueList.add("teutonic-knight");
			pObjectName.valueList.add("elite-teutonic-knight");
			pObjectName.valueList.add("janissary");
			pObjectName.valueList.add("elite-janissary");
			pObjectName.valueList.add("rattan-archer");
			pObjectName.valueList.add("elite-rattan-archer");
			pObjectName.valueList.add("berserk");
			pObjectName.valueList.add("elite-berserk");
			pObjectName.valueList.add("fishing-ship");
			pObjectName.valueList.add("trade-cog");
			pObjectName.valueList.add("transport-ship");
			pObjectName.valueList.add("galley");
			pObjectName.valueList.add("war-galley");
			pObjectName.valueList.add("galleon");
			pObjectName.valueList.add("fire-galley");
			pObjectName.valueList.add("fire-ship");
			pObjectName.valueList.add("fast-fire-ship");
			pObjectName.valueList.add("demo-raft");
			pObjectName.valueList.add("demolition-ship");
			pObjectName.valueList.add("heavy-demolition-ship");
			pObjectName.valueList.add("cannon-galleon");
			pObjectName.valueList.add("elite-cannon-galleon");
			pObjectName.valueList.add("dromon");
			pObjectName.valueList.add("thirisadai");
			pObjectName.valueList.add("turtle-ship");
			pObjectName.valueList.add("elite-turtle-ship");
			pObjectName.valueList.add("caravel");
			pObjectName.valueList.add("elite-caravel");
			pObjectName.valueList.add("longboat");
			pObjectName.valueList.add("elite-longboat");
			pObjectName.valueList.add("donjon-serjeant");
			pObjectName.valueList.add("elite-donjon-serjeant");
			pObjectName.valueList.add("krepost-konnik");
			pObjectName.valueList.add("elite-krepost-konnik");
			pObjectName.valueList.add("trade-cart");
			pObjectName.valueList.add("trade-cart");
			pObjectName.valueList.add("monk");
			pObjectName.valueList.add("missionary");
			pObjectName.valueList.add("warrior-priest");
			pObjectName.valueList.add("feudal-battering-ram");
			pObjectName.valueList.add("battering-ram");
			pObjectName.valueList.add("capped-ram");
			pObjectName.valueList.add("siege-ram");
			pObjectName.valueList.add("armored-elephant");
			pObjectName.valueList.add("siege-elephant");
			pObjectName.valueList.add("mangonel");
			pObjectName.valueList.add("onager");
			pObjectName.valueList.add("siege-onager");
			pObjectName.valueList.add("scorpion");
			pObjectName.valueList.add("heavy-scorpion");
			pObjectName.valueList.add("bombard-cannon");
			pObjectName.valueList.add("houfnice");
			pObjectName.valueList.add("scout-cavalry");
			pObjectName.valueList.add("light-cavalry");
			pObjectName.valueList.add("hussar");
			pObjectName.valueList.add("winged-hussar");
			pObjectName.valueList.add("knight");
			pObjectName.valueList.add("cavalier");
			pObjectName.valueList.add("paladin");
			pObjectName.valueList.add("savar");
			pObjectName.valueList.add("camel-scout");
			pObjectName.valueList.add("camel");
			pObjectName.valueList.add("heavy-camel");
			pObjectName.valueList.add("imperial-camel");
			pObjectName.valueList.add("battle-elephant");
			pObjectName.valueList.add("elite-battle-elephant");
			pObjectName.valueList.add("steppe-lancer");
			pObjectName.valueList.add("elite-steppe-lancer");
			pObjectName.valueList.add("shrivamsha-rider");
			pObjectName.valueList.add("elite-shrivamsha-rider");
			pObjectName.valueList.add("stable-tarkan");
			pObjectName.valueList.add("stable-elite-tarkan");
			pObjectName.valueList.add("villager");
			pObjectName.valueList.add("flemish-pikeman");
			pObjectName.valueList.add("town-center");
			pObjectName.valueList.add("town-center-foundation");
			pObjectName.valueList.add("house");
			pObjectName.valueList.add("mill");
			pObjectName.valueList.add("mining-camp");
			pObjectName.valueList.add("lumber-camp");
			pObjectName.valueList.add("mule-cart");
			pObjectName.valueList.add("dock");
			pObjectName.valueList.add("fish-trap");
			pObjectName.valueList.add("farm");
			pObjectName.valueList.add("blacksmith");
			pObjectName.valueList.add("market");
			pObjectName.valueList.add("monastery");
			pObjectName.valueList.add("university");
			pObjectName.valueList.add("wonder");
			pObjectName.valueList.add("fortified-church");
			pObjectName.valueList.add("caravanserai");
			pObjectName.valueList.add("feitoria");
			pObjectName.valueList.add("barracks");
			pObjectName.valueList.add("archery-range");
			pObjectName.valueList.add("stable");
			pObjectName.valueList.add("siege-workshop");
			pObjectName.valueList.add("outpost");
			pObjectName.valueList.add("palisade-wall");
			pObjectName.valueList.add("stone-wall");
			pObjectName.valueList.add("fortified-wall");
			pObjectName.valueList.add("watch-tower");
			pObjectName.valueList.add("guard-tower");
			pObjectName.valueList.add("keep");
			pObjectName.valueList.add("bombard-tower");
			pObjectName.valueList.add("castle");
			pObjectName.valueList.add("krepost");
			pObjectName.valueList.add("donjon");
			pObjectName.valueList.add("gate-ascending-closed");
			pObjectName.valueList.add("gate-ascending-open");
			pObjectName.valueList.add("gate,<br>gate-ascending");
			pObjectName.valueList.add("gate-descending-closed");
			pObjectName.valueList.add("gate-descending");
			pObjectName.valueList.add("gate-horizontal-closed");
			pObjectName.valueList.add("gate-horizontal-open");
			pObjectName.valueList.add("gate-horizontal-open");
			pObjectName.valueList.add("gate-horizontal");
			pObjectName.valueList.add("gate-vertical-closed");
			pObjectName.valueList.add("gate-vertical-open");
			pObjectName.valueList.add("gate-vertical-open");
			pObjectName.valueList.add("gate-vertical");
			pObjectName.valueList.add("flare");

			// pEscrowGoalId.allowsInteger = true;
			pEventId.allowsInteger = true;
			pGroupId.allowsInteger = true;
			pIndex.allowsInteger = true;
			pLanguageId.allowsInteger = true;
			pLocalIndex.allowsInteger = true;
			pLocalList.allowsInteger = true;
			pMaxDistance.allowsInteger = true;
			pMaxGarrison.allowsInteger = true;
			pMinDistance.allowsInteger = true;
			pMinGarrison.allowsInteger = true;
			pOnMainland.allowsInteger = true;
			pOption.allowsInteger = true;
			pOptionGoalId.allowsInteger = true;
			pPercent.allowsInteger = true;
			pPerimeter.allowsInteger = true;
			pPlayerNumber.allowsInteger = true;
			pRemoteIndex.allowsInteger = true;
			pRemoteList.allowsInteger = true;
			pSignalId.allowsInteger = true;
			pTauntId.allowsInteger = true;

			pId.allowsInteger = true;
			pPoint.allowsPoint = true;
			pString.allowsString = true;
			pTimerId.allowsTimer = true;

			pItemId.valueList.addAll(pObjectName.valueList);
			pItemId.valueList.addAll(pTechId.valueList);
			pItemId.valueList.addAll(pClassId.valueList);

			pUnitId.valueList.addAll(pObjectName.valueList);
			pUnitId.valueList.addAll(pLineId.valueList);
			pUnitId.valueList.addAll(pClassId.valueList);
			pUnitId.valueList.add("my-unique-unit");
			pUnitId.valueList.add("my-elite-unique-unit");
			pUnitId.valueList.add("my-unique-unit-line");

			pObjectId.valueList.addAll(pBuildingId.valueList);
			pObjectId.valueList.addAll(pUnitId.valueList);

			pTypeId.valueList.addAll(pObjectId.valueList);
			pTypeId.valueList.addAll(pLineId.valueList);

			pPlayerNumber.valueList.add("my-player-number");
			pPlayerNumber.valueList.add("target-player");
			pPlayerNumber.valueList.add("focus-player");
			pPlayerNumber.valueList.add("lobby-player-1");
			pPlayerNumber.valueList.add("lobby-player-2");
			pPlayerNumber.valueList.add("lobby-player-3");
			pPlayerNumber.valueList.add("lobby-player-4");
			pPlayerNumber.valueList.add("lobby-player-5");
			pPlayerNumber.valueList.add("lobby-player-6");
			pPlayerNumber.valueList.add("lobby-player-7");
			pPlayerNumber.valueList.add("lobby-player-8");
			pPlayerNumber.valueList.add("scenario-player-1");
			pPlayerNumber.valueList.add("scenario-player-2");
			pPlayerNumber.valueList.add("scenario-player-3");
			pPlayerNumber.valueList.add("scenario-player-4");
			pPlayerNumber.valueList.add("scenario-player-5");
			pPlayerNumber.valueList.add("scenario-player-6");
			pPlayerNumber.valueList.add("scenario-player-7");
			pPlayerNumber.valueList.add("scenario-player-8");

			pEscrowGoalId.valueList.add("with-escrow");
			pEscrowGoalId.valueList.add("without-escrow");

			pCompareOp.valueList.add("GREATER_EQUAL");
			pCompareOp.valueList.add("GREATER");
			pCompareOp.valueList.add("LESS_EQUAL");
			pCompareOp.valueList.add("LESS");
			pCompareOp.valueList.add("EQUAL_EQUAL");
			pCompareOp.valueList.add("BANG_EQUAL");

			pValue.allowsInteger = true;

			FactParameterAssociatedToFactId.put("escrow-amount", pResource);
			FactParameterAssociatedToFactId.put("commodity-buying-price", pCommodity);
			FactParameterAssociatedToFactId.put("commodity-selling-price", pCommodity);
			FactParameterAssociatedToFactId.put("dropsite-min-distance", pResource);
			FactParameterAssociatedToFactId.put("unit-type-count", pUnitId);
			FactParameterAssociatedToFactId.put("unit-type-count-total", pUnitId);
			FactParameterAssociatedToFactId.put("building-type-count", pBuildingId);
			FactParameterAssociatedToFactId.put("building-type-count-total", pBuildingId);
			FactParameterAssociatedToFactId.put("resource-amount", pResourceType);
			FactParameterAssociatedToFactId.put("allied-goal", pGoalId);
			FactParameterAssociatedToFactId.put("allied-sn", pSnId);
			FactParameterAssociatedToFactId.put("resource-percent", pResourceType);
			FactParameterAssociatedToFactId.put("players-in-game", pPlayerStance);
			FactParameterAssociatedToFactId.put("building-type-in-town", pBuildingId);
			FactParameterAssociatedToFactId.put("unit-type-in-town", pUnitId);
			FactParameterAssociatedToFactId.put("villager-type-in-town", pUnitId);
			FactParameterAssociatedToFactId.put("timer-status", pTimerId);
			FactParameterAssociatedToFactId.put("players-tribute", pResource);
			FactParameterAssociatedToFactId.put("players-tribute-memory", pResource);

			FactParameterAssociatedToFactId.put("gaia-type-count", null);
			FactParameterAssociatedToFactId.put("gaia-type-count-total", null);
			FactParameterAssociatedToFactId.put("cc-gaia-type-count", null);

			pDefconst.allowsString = true;

			// System.out.println(FactParameterAssociatedToFactId.containsKey("building-type-count"));
			/*
			 * FactParameterAssociatedToFactId.put("gaia-type-count", "Resource or UnitId");
			 * FactParameterAssociatedToFactId.put("gaia-type-count-total",
			 * "Resource or UnitId");
			 * FactParameterAssociatedToFactId.put("cc-gaia-type-count",
			 * "Resource or UnitId");
			 */

			alreadyFilled = true;
		}

	}

	public ParameterClass getParameterClassObjectOfName(String ParameterClassObjectName) {
		// to convert from String to ParameterClass
		for (ParameterClass parameterClass : parametersArray) {
			if (parameterClass.upParamName.equals(ParameterClassObjectName)) {
				return parameterClass;
			}
		}
		return null;
	}

	public ParameterClass getParameterClassOfAParamater(String parameter) {
		//to convert from String to ParameterClass
		for (ParameterClass parameterClass : parametersArray) {
			for (String para : parameterClass.valueList) {
				if (para.equals(parameter)) {
					return parameterClass;
				}
			}
		}
		return null;
	}

}
